addSbtPlugin("io.getkyo"          % "kyo-ffi-plugin"                % sys.props("plugin.version"))
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.3.2")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.3.2")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % sys.props("scalajs.version"))
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % sys.props("scalanative.version"))
