//> using scala 3.8.4

import java.io.File
import java.nio.file.Files
import java.security.MessageDigest
import java.util.Base64

/** Single source of truth for the checked-in pure-Scala tiktoken rank tables.
  *
  * Reads the reference `o200k_base.tiktoken` / `cl100k_base.tiktoken` vocab files (one
  * `<base64 token bytes> <decimal rank>` entry per line, tiktoken's `load_tiktoken_bpe` format),
  * verifies each against its pinned sha256, packs every entry as one length byte, that many token
  * bytes, then a LEB128 varint rank IN THE FILE'S RANK ORDER, and emits `O200kRanks.scala` /
  * `Cl100kRanks.scala` under `kyo-ai/shared/src/main/scala/kyo/ai/tokenizer` as ordinary committed sources
  * (NOT build-time `sourceManaged`, so they ship identically on JVM/JS/Native/Wasm with no resource
  * I/O). The packed blob is base64-encoded and split into <48000-char string literals so no constant
  * exceeds the JVM 65535-byte modified-UTF8 limit and no initializer method exceeds the 64 KB
  * bytecode limit; the runtime loader (`Tokenizer.internal.Ranks.decode`) base64-decodes and walks
  * the packed bytes with a pure-Scala decoder. Deterministic: emitting in the file's existing rank
  * order yields byte-identical output every run (no Map/Set iteration).
  *
  * A STANDALONE SCRIPT, not a build task. It regenerates committed sources from a reference vocabulary
  * that changes approximately never, so a task key, a settings entry and a `project/` source file were
  * three pieces of build surface for something nobody runs during a build. Run it directly:
  *
  * {{{
  * scala-cli run kyo-ai/scripts/TiktokenVocabGen.scala -- kyo-ai/reference-vocab kyo-ai/shared/src/main/scala/kyo/ai/tokenizer
  * }}}
  *
  * It was
  * NOT wired into `Compile / sourceGenerators` (the emitted files are committed, not regenerated per
  * build). Being build code it may use the JVM stdlib; the cross-platform constraint binds only the
  * emitted runtime loader, never this generator.
  */
object TiktokenVocabGen {

    private val ChunkChars = 48000

    private final case class Table(objectName: String, sourceFile: String, sha256: String)

    private val Tables = List(
        Table(
            "O200kRanks",
            "o200k_base.tiktoken",
            "446a9538cb6c348e3516120d7c08b09f57c36495e2acfffe59a5bf8b0cfb1a2d"
        ),
        Table(
            "Cl100kRanks",
            "cl100k_base.tiktoken",
            "223921b76ee99bde995b7ff738513eef100fb51d18c93597a113bcffe865b2a7"
        )
    )

    /** Regenerate both rank-table sources from the reference vocab under `vocabDir` into `outDir`. */
    def generate(vocabDir: File, outDir: File): Seq[File] = {
        Files.createDirectories(outDir.toPath)
        Tables.map { t =>
            val vocab = File(vocabDir, t.sourceFile)
            val raw   = Files.readAllBytes(vocab.toPath)
            verifySha(raw, t.sha256, vocab)
            val packed = pack(new String(raw, "US-ASCII"))
            val out    = File(outDir, s"${t.objectName}.scala")
            Files.write(out.toPath, render(t.objectName, packed).getBytes("UTF-8"))
            out
        }
    }

    private def verifySha(raw: Array[Byte], expected: String, f: File): Unit = {
        val md  = MessageDigest.getInstance("SHA-256")
        val hex = md.digest(raw).map(b => f"${b & 0xff}%02x").mkString
        if (hex != expected)
            sys.error(s"TiktokenVocabGen: sha256 mismatch for ${f.getName}: expected $expected, got $hex")
    }

    /** Pack the `.tiktoken` text into the length-prefixed + varint-rank byte blob, in file order. */
    private def pack(text: String): Array[Byte] = {
        val out = new java.io.ByteArrayOutputStream()
        text.linesIterator.foreach { line =>
            if (line.nonEmpty) {
                val sp         = line.indexOf(' ')
                val tokenBytes = Base64.getDecoder.decode(line.substring(0, sp))
                val rank       = line.substring(sp + 1).trim.toInt
                if (tokenBytes.length > 255)
                    sys.error(s"TiktokenVocabGen: token > 255 bytes (${tokenBytes.length}); widen the length prefix")
                out.write(tokenBytes.length)
                out.write(tokenBytes)
                writeVarint(out, rank)
            }
        }
        out.toByteArray
    }

    private def writeVarint(out: java.io.ByteArrayOutputStream, value: Int): Unit = {
        var v = value
        while ((v & ~0x7f) != 0) {
            out.write((v & 0x7f) | 0x80)
            v >>>= 7
        }
        out.write(v)
    }

    private def render(objectName: String, packed: Array[Byte]): String = {
        val b64    = Base64.getEncoder.withoutPadding.encodeToString(packed)
        val chunks = b64.grouped(ChunkChars).toList
        val sb     = new StringBuilder
        sb.append("// AUTO-GENERATED by kyo-ai/scripts/TiktokenVocabGen.scala from the reference tiktoken vocab.\n")
        sb.append("// DO NOT EDIT BY HAND. Edit that script and rerun it with scala-cli; it is a standalone\n")
        sb.append("// generator rather than a build task, so no sbt command regenerates these tables.\n")
        sb.append("package kyo.ai.tokenizer\n\n")
        sb.append("import kyo.ai.Tokenizer.internal.Ranks\n\n")
        sb.append(s"/** GENERATED packed rank table. Decoded once by `Ranks.decode`. */\n")
        sb.append(s"private[kyo] object $objectName:\n\n")
        sb.append("    private val chunks: Array[String] = Array(\n")
        chunks.zipWithIndex.foreach { case (c, i) =>
            val comma = if (i == chunks.length - 1) "" else ","
            sb.append("        \"").append(c).append("\"").append(comma).append("\n")
        }
        sb.append("    )\n\n")
        sb.append("    /** Decodes the packed table into the content-keyed byte-sequence -> rank map. Pure. */\n")
        sb.append(s"    def load(): Map[Ranks.Key, Int] = Ranks.decode(chunks)\n")
        sb.append(s"end $objectName\n")
        sb.toString
    }
}

@main def run(vocabDir: String, outDir: String): Unit =
    val written = TiktokenVocabGen.generate(File(vocabDir), File(outDir))
    written.foreach(f => println(s"wrote ${f.getPath}"))
