package kyo

import java.io.OutputStream
import java.io.OutputStreamWriter
import java.nio.charset.StandardCharsets

/** Amazon Ion Schema Language document generated from a kyo [[Schema]].
  *
  * `IonSchema` models the ISL document shape that kyo-schema can derive from its structural
  * metadata. It targets Ion Schema 2.0 by default and renders a valid ISL stream containing the
  * `$ion_schema_2_0` version marker followed by one named `type::{...}` definition.
  *
  * The generated schema describes the wire shape produced by kyo-schema codecs: products become
  * closed structs, collections become lists, optional values become `$null_or` type arguments, and
  * sealed traits become `one_of` alternatives matching their configured object representation. When
  * configured with [[Ion.AnnotationEmissionMode.Emit]], captured schema annotations are emitted as
  * ISL `annotations` constraints that describe the Ion type annotations written by the Ion codecs.
  *
  * This is a schema-generation surface, like [[Json.JsonSchema]]. Runtime value validation remains
  * available through `Schema.decode` and `Schema.validate`; a general-purpose ISL evaluator is a
  * separate concern because Ion Schema validates the full Ion data model, including annotations and
  * typed null distinctions that ordinary Scala value decoding intentionally erases.
  */
final case class IonSchema(version: IonSchema.Version, types: Chunk[IonSchema.TypeDefinition]) derives CanEqual

object IonSchema:

    /** Ion Schema Language version marker emitted by this generator. */
    enum Version derives CanEqual:
        case V2_0

        def marker: String =
            this match
                case V2_0 => "$ion_schema_2_0"
        end marker
    end Version

    /** Configuration for deriving an Ion Schema document from a kyo [[Schema]]. */
    final case class Config(
        version: Version = Version.V2_0,
        closedStructs: Boolean = true,
        annotationEmissionMode: Ion.AnnotationEmissionMode = Ion.AnnotationEmissionMode.Suppress
    ) derives CanEqual

    object Config:
        val Default: Config = Config()
        given Config        = Default
    end Config

    /** A named ISL type definition. */
    final case class TypeDefinition(name: String, tpe: TypeExpr, doc: Maybe[String] = Maybe.empty) derives CanEqual

    /** A field definition inside an ISL `fields` constraint. */
    final case class Field(name: String, tpe: TypeExpr, required: Boolean, doc: Maybe[String] = Maybe.empty) derives CanEqual

    /** Supported ISL type expression generated by kyo-schema. */
    enum TypeExpr derives CanEqual:
        case AnyType
        case Named(name: String)
        case Scalar(name: String)
        case Nullable(inner: TypeExpr)
        case ListOf(element: TypeExpr, distinct: Boolean)
        case Struct(fields: Chunk[Field], closed: Boolean)
        case MapOf(value: TypeExpr, distinctFieldNames: Boolean)
        case OneOf(options: Chunk[TypeExpr])
        case Constrained(base: TypeExpr, constraints: Chunk[Constraint])
    end TypeExpr

    /** Supported ISL constraints generated from kyo [[Schema.Constraint]] metadata. */
    enum Constraint derives CanEqual:
        case Annotations(names: Chunk[String])
        case ValidRange(min: Maybe[(Double, Boolean)], max: Maybe[(Double, Boolean)])
        case ValidValues(values: Chunk[String])
        case CodepointLength(min: Maybe[Int], max: Maybe[Int])
        case ContainerLength(min: Maybe[Int], max: Maybe[Int])
        case Regex(pattern: String)
    end Constraint

    /** Derives an Ion Schema document for type `A`. */
    inline def from[A](using schema: Schema[A]): IonSchema =
        fromSchema(schema)
    end from

    /** Derives an Ion Schema document from a runtime [[Schema]]. */
    def fromSchema[A](schema: Schema[A], config: Config = Config.Default): IonSchema =
        val constraints = constraintsByPath(schema.constraints)
        val root        = fromStructure(schema.structure, constraints, Seq.empty, schema, config, Set.empty)
        val name        = rootName(schema.structure)
        IonSchema(config.version, Chunk(TypeDefinition(name, root, schema.documentation)))
    end fromSchema

    /** Encodes an Ion Schema document as ISL text. */
    def encode(schema: IonSchema): String =
        val out = new java.lang.StringBuilder
        render(schema, out)
        out.toString
    end encode

    /** Encodes an Ion Schema document as UTF-8 ISL text to an output stream.
      *
      * The document is written incrementally as it renders, with no intermediate full-document
      * string materialized. The write happens synchronously on the calling thread. The stream is
      * flushed once rendering completes but is never closed; the caller owns its lifecycle.
      */
    def encodeTo(schema: IonSchema, out: OutputStream): Unit =
        val writer = new OutputStreamWriter(out, StandardCharsets.UTF_8)
        render(schema, writer)
        writer.flush()
    end encodeTo

    /** Appends `value` to `out`, discarding the chainable [[Appendable]] result.
      *
      * [[java.lang.StringBuilder]] and [[java.io.Writer]] both implement `Appendable`, so
      * rendering against this common interface lets the same render path write into an
      * in-memory buffer or stream directly onto a writer without an intermediate string.
      */
    private def emit(out: Appendable, value: CharSequence): Unit =
        val _ = out.append(value)
    end emit

    private def emit(out: Appendable, value: Char): Unit =
        val _ = out.append(value)
    end emit

    private def render(schema: IonSchema, out: Appendable): Unit =
        emit(out, schema.version.marker)
        schema.types.foreach { tpe =>
            emit(out, "\n\n")
            renderTypeDefinition(out, tpe, 0)
        }
    end render

    /** Derives and encodes an Ion Schema document for type `A` as ISL text. */
    inline def encode[A](config: Config = Config.Default)(using schema: Schema[A]): String =
        IonSchema.encode(fromSchema(schema, config))
    end encode

    /** Derives and encodes an Ion Schema document for type `A` as UTF-8 ISL text to an output
      * stream.
      *
      * The document is written incrementally as it renders, with no intermediate full-document
      * string materialized. The write happens synchronously on the calling thread. The stream is
      * flushed once rendering completes but is never closed; the caller owns its lifecycle.
      */
    inline def encodeTo[A](out: OutputStream, config: Config = Config.Default)(using schema: Schema[A]): Unit =
        IonSchema.encodeTo(fromSchema(schema, config), out)
    end encodeTo

    private def constraintsByPath(constraints: Seq[Schema.Constraint]): Map[Seq[String], Chunk[Schema.Constraint]] =
        constraints.foldLeft(Map.empty[Seq[String], Chunk[Schema.Constraint]]) { (acc, constraint) =>
            acc.updated(constraint.segments, acc.getOrElse(constraint.segments, Chunk.empty) :+ constraint)
        }
    end constraintsByPath

    private def rootName(structure: Structure.Type): String =
        structure match
            case p: Structure.Type.Product => p.name
            case s: Structure.Type.Sum     => s.name
            case _                         => "Root"
    end rootName

    private def fromStructure[A](
        structure: Structure.Type,
        constraints: Map[Seq[String], Chunk[Schema.Constraint]],
        path: Seq[String],
        schema: Schema[A],
        config: Config,
        seen: Set[String]
    ): TypeExpr =
        val base =
            structure match
                case p: Structure.Type.Primitive =>
                    primitive(p.kind)
                case Structure.Type.Optional(_, _, inner) =>
                    TypeExpr.Nullable(fromStructure(inner, constraints, path, schema, config, seen))
                case Structure.Type.Collection(_, _, elem) =>
                    TypeExpr.ListOf(fromStructure(elem, constraints, path :+ "*", schema, config, seen), distinct = false)
                case product: Structure.Type.Product =>
                    if seen.contains(product.name) then TypeExpr.AnyType
                    else
                        val nextSeen = seen + product.name
                        val renamed  = schema.renamedFields.toMap
                        val fields =
                            product.fields.flatMap { field =>
                                if schema.droppedFields.contains(field.name) then Chunk.empty
                                else
                                    val wireName  = renamed.getOrElse(field.name, field.name)
                                    val fieldPath = path :+ field.name
                                    val fieldType =
                                        fromStructure(field.fieldType, constraints, fieldPath, schema, config, nextSeen)
                                    Chunk(Field(
                                        wireName,
                                        applyAnnotations(fieldType, field.annotations, config),
                                        field.default.isEmpty && !field.optional,
                                        field.doc
                                    ))
                            }
                        TypeExpr.Struct(fields, config.closedStructs)
                case sum: Structure.Type.Sum =>
                    if seen.contains(sum.name) then TypeExpr.AnyType
                    else
                        val nextSeen = seen + sum.name
                        val wires    = Schema.effectiveVariantWires(sum, schema.variantNaming)
                        val options = sum.variants.zip(wires).map { (variant, wireName) =>
                            val payload = applyAnnotations(
                                fromStructure(variant.variantType, constraints, path :+ variant.name, schema, config, nextSeen),
                                variant.annotations,
                                config
                            )
                            sumRepresentation(schema).match
                                case Schema.UnionRepresentation.External =>
                                    TypeExpr.Struct(Chunk(Field(wireName, payload, required = true)), closed = true)
                                case Schema.UnionRepresentation.Internal(tagKey) =>
                                    flattenDiscriminatorType(tagKey, wireName, payload)
                                case Schema.UnionRepresentation.Adjacent(tagKey, contentKey) =>
                                    TypeExpr.Struct(
                                        Chunk(
                                            discriminatorField(tagKey, wireName),
                                            Field(contentKey, payload, required = true)
                                        ),
                                        closed = true
                                    )
                                case unsupported =>
                                    throw SchemaNotSerializableException(
                                        s"Ion Schema generation cannot describe union representation $unsupported"
                                    )(using Frame.internal)
                            end match
                        }
                        TypeExpr.OneOf(options)
                case Structure.Type.Mapping(_, _, keyType, valueType) =>
                    keyType match
                        case p: Structure.Type.Primitive
                            if p.kind == Structure.PrimitiveKind.String || p.kind == Structure.PrimitiveKind.Char =>
                            TypeExpr.MapOf(
                                fromStructure(valueType, constraints, path :+ "*", schema, config, seen),
                                distinctFieldNames = false
                            )
                        case _ =>
                            val key =
                                Field("key", fromStructure(keyType, constraints, path :+ "key", schema, config, seen), required = true)
                            val value = Field(
                                "value",
                                fromStructure(valueType, constraints, path :+ "value", schema, config, seen),
                                required = true
                            )
                            TypeExpr.ListOf(TypeExpr.Struct(Chunk(key, value), closed = true), distinct = false)
                    end match
                case _: Structure.Type.Open =>
                    TypeExpr.AnyType
        val annotated = applyAnnotations(base, Schema.annotationsFor(structure), config)
        applyConstraints(annotated, constraints.getOrElse(path, Chunk.empty))
    end fromStructure

    private def primitive(kind: Structure.PrimitiveKind): TypeExpr =
        kind match
            case Structure.PrimitiveKind.Boolean    => TypeExpr.Scalar("bool")
            case Structure.PrimitiveKind.Byte       => TypeExpr.Scalar("int")
            case Structure.PrimitiveKind.Short      => TypeExpr.Scalar("int")
            case Structure.PrimitiveKind.Int        => TypeExpr.Scalar("int")
            case Structure.PrimitiveKind.Long       => TypeExpr.Scalar("int")
            case Structure.PrimitiveKind.BigInt     => TypeExpr.Scalar("int")
            case Structure.PrimitiveKind.Float      => TypeExpr.Scalar("float")
            case Structure.PrimitiveKind.Double     => TypeExpr.Scalar("float")
            case Structure.PrimitiveKind.BigDecimal => TypeExpr.Scalar("decimal")
            case Structure.PrimitiveKind.String     => TypeExpr.Scalar("string")
            case Structure.PrimitiveKind.Char       => TypeExpr.Scalar("string")
            case Structure.PrimitiveKind.Bytes      => TypeExpr.Scalar("blob")
            case Structure.PrimitiveKind.Instant    => TypeExpr.Scalar("timestamp")
            case Structure.PrimitiveKind.Duration   => TypeExpr.Scalar("string")
            case Structure.PrimitiveKind.Unit       => TypeExpr.Struct(Chunk.empty, closed = true)
    end primitive

    private def sumRepresentation[A](schema: Schema[A]): Schema.UnionRepresentation =
        schema.representationChain match
            case Maybe.Present(chain) => chain.head
            case Maybe.Absent         => schema.representation
    end sumRepresentation

    private def discriminatorField(name: String, value: String): Field =
        Field(
            name,
            TypeExpr.Constrained(TypeExpr.Scalar("string"), Chunk(Constraint.ValidValues(Chunk(value)))),
            required = true
        )
    end discriminatorField

    private def flattenDiscriminatorType(tagKey: String, wireName: String, payload: TypeExpr): TypeExpr =
        val tag = discriminatorField(tagKey, wireName)
        payload match
            case TypeExpr.Struct(fields, _) =>
                TypeExpr.Struct(tag +: fields, closed = true)
            case TypeExpr.Constrained(TypeExpr.Struct(fields, _), constraints) =>
                TypeExpr.Constrained(TypeExpr.Struct(tag +: fields, closed = true), constraints)
            case _ =>
                TypeExpr.Struct(Chunk(tag), closed = true)
        end match
    end flattenDiscriminatorType

    private def applyConstraints(base: TypeExpr, constraints: Chunk[Schema.Constraint]): TypeExpr =
        if constraints.isEmpty then base
        else
            var minValue        = Maybe.empty[(Double, Boolean)]
            var maxValue        = Maybe.empty[(Double, Boolean)]
            var minCodepoints   = Maybe.empty[Int]
            var maxCodepoints   = Maybe.empty[Int]
            var minContainer    = Maybe.empty[Int]
            var maxContainer    = Maybe.empty[Int]
            var regexes         = Chunk.empty[Constraint]
            var distinctElement = false

            constraints.foreach {
                case Schema.Constraint.Min(_, value, exclusive) =>
                    minValue = Maybe((value, exclusive))
                case Schema.Constraint.Max(_, value, exclusive) =>
                    maxValue = Maybe((value, exclusive))
                case Schema.Constraint.MinLength(_, value) =>
                    minCodepoints = Maybe(value)
                case Schema.Constraint.MaxLength(_, value) =>
                    maxCodepoints = Maybe(value)
                case Schema.Constraint.Pattern(_, regex) =>
                    regexes = regexes :+ Constraint.Regex(regex)
                case Schema.Constraint.MinItems(_, value) =>
                    minContainer = Maybe(value)
                case Schema.Constraint.MaxItems(_, value) =>
                    maxContainer = Maybe(value)
                case Schema.Constraint.UniqueItems(_) =>
                    distinctElement = true
                case Schema.Constraint.Format(_, _) =>
                    ()
            }

            val distinctBase =
                if !distinctElement then base
                else
                    base match
                        case TypeExpr.ListOf(element, _) =>
                            TypeExpr.ListOf(element, distinct = true)
                        case TypeExpr.MapOf(value, _) =>
                            TypeExpr.MapOf(value, distinctFieldNames = true)
                        case other =>
                            other
                    end match

            var rendered = regexes
            if minValue.nonEmpty || maxValue.nonEmpty then
                rendered = Constraint.ValidRange(minValue, maxValue) +: rendered
            if minCodepoints.nonEmpty || maxCodepoints.nonEmpty then
                rendered = Constraint.CodepointLength(minCodepoints, maxCodepoints) +: rendered
            if minContainer.nonEmpty || maxContainer.nonEmpty then
                rendered = Constraint.ContainerLength(minContainer, maxContainer) +: rendered

            if rendered.isEmpty then distinctBase else appendConstraints(distinctBase, rendered)
        end if
    end applyConstraints

    private def applyAnnotations(base: TypeExpr, annotations: Chunk[Any], config: Config): TypeExpr =
        if config.annotationEmissionMode != Ion.AnnotationEmissionMode.Emit || annotations.isEmpty then base
        else appendConstraints(base, Chunk(Constraint.Annotations(annotations.map(annotationName))))
    end applyAnnotations

    private def appendConstraints(base: TypeExpr, constraints: Chunk[Constraint]): TypeExpr =
        base match
            case TypeExpr.Constrained(inner, existing) => TypeExpr.Constrained(inner, existing ++ constraints)
            case other                                 => TypeExpr.Constrained(other, constraints)
    end appendConstraints

    private def annotationName(value: Any): String =
        value.getClass.getName.stripSuffix("$")
    end annotationName

    private def renderTypeDefinition(out: Appendable, definition: TypeDefinition, indent: Int): Unit =
        indentLine(out, indent, "type::{")
        renderSymbolField(out, indent + 2, "name", definition.name)
        definition.doc.foreach(doc => renderField(out, indent + 2, "_doc", doc))
        renderTypeBody(out, definition.tpe, indent + 2, Maybe.empty)
        indentLine(out, indent, "}")
    end renderTypeDefinition

    private def renderTypeBody(out: Appendable, tpe: TypeExpr, indent: Int, occurs: Maybe[String]): Unit =
        val (base, constraints) = splitConstraints(tpe)
        renderTypeConstraint(out, base, indent)
        constraints.foreach(renderConstraint(out, _, indent))
        occurs.foreach(value => renderSymbolField(out, indent, "occurs", value))
    end renderTypeBody

    private def splitConstraints(tpe: TypeExpr): (TypeExpr, Chunk[Constraint]) =
        tpe match
            case TypeExpr.Constrained(base, constraints) => (base, constraints)
            case other                                   => (other, Chunk.empty)
    end splitConstraints

    private def renderTypeConstraint(out: Appendable, tpe: TypeExpr, indent: Int): Unit =
        tpe match
            case TypeExpr.AnyType =>
                ()
            case TypeExpr.Named(name) =>
                renderSymbolField(out, indent, "type", name)
            case TypeExpr.Scalar(name) =>
                renderSymbolField(out, indent, "type", name)
            case nullable: TypeExpr.Nullable =>
                writeIndent(out, indent)
                emit(out, "type: ")
                renderTypeArgument(out, nullable)
                emit(out, ",\n")
            case TypeExpr.ListOf(element, distinct) =>
                renderSymbolField(out, indent, "type", "list")
                writeIndent(out, indent)
                emit(out, "element: ")
                if distinct then emit(out, "distinct::")
                renderTypeArgument(out, element)
                emit(out, ",\n")
            case TypeExpr.Struct(fields, closed) =>
                renderSymbolField(out, indent, "type", "struct")
                writeIndent(out, indent)
                emit(out, "fields: ")
                if closed then emit(out, "closed::")
                emit(out, "{")
                if fields.nonEmpty then
                    emit(out, "\n")
                    fields.foreach(renderStructField(out, _, indent + 2))
                    writeIndent(out, indent)
                end if
                emit(out, "},\n")
            case TypeExpr.MapOf(value, distinctFieldNames) =>
                renderSymbolField(out, indent, "type", "struct")
                writeIndent(out, indent)
                emit(out, "field_names: ")
                if distinctFieldNames then emit(out, "distinct::")
                emit(out, "string,\n")
                writeIndent(out, indent)
                emit(out, "element: ")
                renderTypeArgument(out, value)
                emit(out, ",\n")
            case TypeExpr.OneOf(options) =>
                writeIndent(out, indent)
                emit(out, "one_of: [")
                if options.nonEmpty then
                    emit(out, "\n")
                    options.foreach { option =>
                        writeIndent(out, indent + 2)
                        renderInlineType(out, option, indent + 2)
                        emit(out, ",\n")
                    }
                    writeIndent(out, indent)
                end if
                emit(out, "],\n")
            case TypeExpr.Constrained(base, _) =>
                renderTypeConstraint(out, base, indent)
        end match
    end renderTypeConstraint

    private def renderStructField(out: Appendable, field: Field, indent: Int): Unit =
        writeIndent(out, indent)
        renderSymbol(out, field.name)
        emit(out, ": ")
        renderInlineType(out, field.tpe, indent, if field.required then Maybe("required") else Maybe.empty)
        emit(out, ",\n")
    end renderStructField

    private def renderInlineType(out: Appendable, tpe: TypeExpr, indent: Int, occurs: Maybe[String] = Maybe.empty): Unit =
        emit(out, "{ ")
        val scratch = new java.lang.StringBuilder
        renderTypeBody(scratch, tpe, indent + 2, occurs)
        val lines = Chunk.from(scratch.toString.linesIterator.map(_.trim.stripSuffix(","))).filter(_.nonEmpty)
        val body  = joinInlineLines(lines)
        if body.isEmpty then emit(out, "type: any")
        else emit(out, body)
        emit(out, " }")
    end renderInlineType

    /** Reassembles the trimmed lines of a nested type body into one Ion-valid line.
      *
      * A container's own opening line ends with `{` or `[` and its closing line is a bare `}`
      * or `]`; neither boundary takes a preceding comma; a leading comma right after an opening
      * brace, or right before a bare closing one, is invalid Ion struct/list grammar. Every other
      * pair of adjacent lines is a genuine field or element boundary and is comma-separated.
      */
    private def joinInlineLines(lines: Chunk[String]): String =
        lines.foldLeft("") { (acc, line) =>
            if acc.isEmpty then line
            else if acc.endsWith("{") || acc.endsWith("[") then s"$acc $line"
            else if line == "}" || line == "]" then s"$acc $line"
            else s"$acc, $line"
        }
    end joinInlineLines

    private def renderTypeArgument(out: Appendable, tpe: TypeExpr): Unit =
        tpe match
            case TypeExpr.Nullable(inner) =>
                emit(out, "$null_or::")
                renderTypeArgument(out, inner)
            case TypeExpr.Named(name) =>
                renderSymbol(out, name)
            case TypeExpr.Scalar(name) =>
                emit(out, name)
            case TypeExpr.AnyType =>
                emit(out, "any")
            case other =>
                renderInlineType(out, other, 0)
        end match
    end renderTypeArgument

    private def renderConstraint(out: Appendable, constraint: Constraint, indent: Int): Unit =
        constraint match
            case Constraint.Annotations(names) =>
                writeIndent(out, indent)
                emit(out, "annotations: required::[")
                var first = true
                names.foreach { name =>
                    if !first then emit(out, ", ")
                    first = false
                    renderSymbol(out, name)
                }
                emit(out, "],\n")
            case Constraint.ValidRange(min, max) =>
                writeIndent(out, indent)
                emit(out, "valid_values: range::[")
                renderRangeBound(out, min, "min")
                emit(out, ", ")
                renderRangeBound(out, max, "max")
                emit(out, "],\n")
            case Constraint.ValidValues(values) =>
                writeIndent(out, indent)
                emit(out, "valid_values: [")
                var first = true
                values.foreach { value =>
                    if !first then emit(out, ", ")
                    first = false
                    renderString(out, value)
                }
                emit(out, "],\n")
            case Constraint.CodepointLength(min, max) =>
                renderIntRange(out, indent, "codepoint_length", min, max)
            case Constraint.ContainerLength(min, max) =>
                renderIntRange(out, indent, "container_length", min, max)
            case Constraint.Regex(pattern) =>
                renderField(out, indent, "regex", pattern)
        end match
    end renderConstraint

    private def renderIntRange(out: Appendable, indent: Int, name: String, min: Maybe[Int], max: Maybe[Int]): Unit =
        writeIndent(out, indent)
        emit(out, name)
        emit(out, ": range::[")
        emit(out, min.map(_.toString).getOrElse("min"))
        emit(out, ", ")
        emit(out, max.map(_.toString).getOrElse("max"))
        emit(out, "],\n")
    end renderIntRange

    private def renderRangeBound(out: Appendable, bound: Maybe[(Double, Boolean)], fallback: String): Unit =
        bound match
            case Maybe.Present((value, exclusive)) =>
                if exclusive then emit(out, "exclusive::")
                emit(out, renderNumber(value))
            case Maybe.Absent =>
                emit(out, fallback)
    end renderRangeBound

    private def renderNumber(value: Double): String =
        if value.isWhole then value.toLong.toString else value.toString
    end renderNumber

    private def renderSymbolField(out: Appendable, indent: Int, name: String, value: String): Unit =
        writeIndent(out, indent)
        emit(out, name)
        emit(out, ": ")
        renderSymbol(out, value)
        emit(out, ",\n")
    end renderSymbolField

    private def renderField(out: Appendable, indent: Int, name: String, value: String): Unit =
        writeIndent(out, indent)
        emit(out, name)
        emit(out, ": ")
        renderString(out, value)
        emit(out, ",\n")
    end renderField

    private def indentLine(out: Appendable, indent: Int, value: String): Unit =
        writeIndent(out, indent)
        emit(out, value)
        emit(out, '\n')
    end indentLine

    private def writeIndent(out: Appendable, size: Int): Unit =
        var i = 0
        while i < size do
            emit(out, ' ')
            i += 1
        end while
    end writeIndent

    private def renderSymbol(out: Appendable, value: String): Unit =
        if isIdentifier(value) && !ReservedSymbols.contains(value) then emit(out, value)
        else
            emit(out, '\'')
            var i = 0
            while i < value.length do
                value.charAt(i) match
                    case '\'' => emit(out, "\\'")
                    case '\\' => emit(out, "\\\\")
                    case c    => emit(out, c)
                end match
                i += 1
            end while
            emit(out, '\'')
        end if
    end renderSymbol

    private def renderString(out: Appendable, value: String): Unit =
        emit(out, '"')
        var i = 0
        while i < value.length do
            value.charAt(i) match
                case '"'  => emit(out, "\\\"")
                case '\\' => emit(out, "\\\\")
                case '\n' => emit(out, "\\n")
                case '\r' => emit(out, "\\r")
                case '\t' => emit(out, "\\t")
                case c    => emit(out, c)
            end match
            i += 1
        end while
        emit(out, '"')
    end renderString

    private def isIdentifier(value: String): Boolean =
        if value.isEmpty then false
        else
            def start(c: Char): Boolean = c == '_' || c == '$' || c.isLetter
            def part(c: Char): Boolean  = start(c) || c.isDigit
            start(value.charAt(0)) && value.drop(1).forall(part)
        end if
    end isIdentifier

    private val ReservedSymbols: Set[String] =
        Set(
            "null",
            "true",
            "false",
            "nan",
            "+inf",
            "-inf"
        )
end IonSchema
