export declare class Stream {
  broadcast2<E>(bufferSize: number): Kyo<[Stream<V, Abort<E> & Async>, Stream<V, Abort<E> & Scope & Async>], Scope & Async & S>;
  broadcast3<E>(bufferSize: number): Kyo<[Stream<V, Abort<E> & Async>, Stream<V, Abort<E> & Async>, Stream<V, Abort<E> & Async>], Scope & Async & S>;
  broadcast4<E>(bufferSize: number): Kyo<[Stream<V, Abort<E> & Async>, Stream<V, Abort<E> & Async>, Stream<V, Abort<E> & Async>, Stream<V, Abort<E> & Async>], Scope & Async & S>;
  broadcast5<E>(bufferSize: number): Kyo<[Stream<V, Abort<E> & Async>, Stream<V, Abort<E> & Async>, Stream<V, Abort<E> & Async>, Stream<V, Abort<E> & Async>, Stream<V, Abort<E> & Async>], Scope & Async & S>;
  broadcastDynamic<E>(bufferSize: number): Kyo<StreamHub<V, E>, Scope & Async & S>;
  broadcastDynamicWith<E, A, S1>(bufferSize: number, fn: (x1: StreamHub<V, E>) => Kyo<A, S1>): Kyo<A, Scope & Async & S & S1>;
  broadcastDynamicWith<E, A, S1>(fn: (x1: StreamHub<V, E>) => Kyo<A, S1>): Kyo<A, Scope & Async & S & S1>;
  broadcastN<E>(numStreams: number, bufferSize: number): Kyo<Chunk<Stream<V, Abort<E> & Scope & Async>>, Scope & Async & S>;
  broadcasted<E>(bufferSize: number): Kyo<Stream<V, Abort<E> & Async & Scope>, Scope & Async & S>;
  changes<VV>(first: VV): Stream<VV, S>;
  changes<VV>(): Stream<VV, S>;
  collect<VV, V2, S2>(f: (x1: VV) => Kyo<Maybe<V2>, S2>): Stream<V2, S & S2>;
  collectPure<VV, V2>(f: (x1: VV) => Maybe<V2>): Stream<V2, S>;
  collectWhile<VV, V2, S2>(f: (x1: VV) => Kyo<Maybe<V2>, S2>): Stream<V2, S & S2>;
  collectWhilePure<VV, V2>(f: (x1: VV) => Maybe<V2>): Stream<V2, S>;
  concat<VV, S2>(other: Stream<VV, S2>): Stream<VV, S & S2>;
  discard<VV>(): Kyo<void, S>;
  drop<VV>(n: number): Stream<VV, S>;
  dropWhile<VV, S2>(f: (x1: VV) => Kyo<boolean, S2>): Stream<VV, S & S2>;
  dropWhilePure<VV>(f: (x1: VV) => boolean): Stream<VV, S>;
  readonly emit: Kyo<void, Emit<Chunk<V>> & S>;
  filter<VV, S2>(f: (x1: VV) => Kyo<boolean, S2>): Stream<VV, S & S2>;
  filterPure<VV>(f: (x1: VV) => boolean): Stream<VV, S>;
  flatMap<VV, S2, V2, S3>(f: (x1: VV) => Kyo<Stream<V2, S2>, S3>): Stream<V2, S & S2 & S3>;
  flatMapChunk<VV, S2, V2, S3>(f: (x1: Chunk<VV>) => Kyo<Stream<V2, S2>, S3>): Stream<V2, S & S2 & S3>;
  fold<VV, A, S2>(acc: A, f: (x1: A, x2: VV) => Kyo<A, S2>): Kyo<A, S & S2>;
  foldPure<VV, A>(acc: A, f: (x1: A, x2: VV) => A): Kyo<A, S>;
  foreach<VV, S2>(f: (x1: VV) => Kyo<unknown, S2>): Kyo<void, S & S2>;
  foreachChunk<VV, S2>(f: (x1: Chunk<VV>) => Kyo<unknown, S2>): Kyo<void, S & S2>;
  groupedWithin<E>(maxSize: number, maxTime: Duration, bufferSize: number): Stream<Chunk<V>, S & Abort<E> & Async>;
  handle<A, B, C, D, E, F, G, V1, S1>(f1: (x1: () => A) => B, f2: (x1: () => B) => C, f3: (x1: () => C) => D, f4: (x1: () => D) => E, f5: (x1: () => E) => F, f6: (x1: () => F) => G, f7: (x1: () => G) => Kyo<unknown, Emit<Chunk<V1>> & S1>): Stream<V1, S1>;
  handle<A, B, C, D, E, F, G, H, V1, S1>(f1: (x1: () => A) => B, f2: (x1: () => B) => C, f3: (x1: () => C) => D, f4: (x1: () => D) => E, f5: (x1: () => E) => F, f6: (x1: () => F) => G, f7: (x1: () => G) => H, f8: (x1: () => H) => Kyo<unknown, Emit<Chunk<V1>> & S1>): Stream<V1, S1>;
  handle<A, V1, S1>(f: (x1: () => A) => Kyo<unknown, Emit<Chunk<V1>> & S1>): Stream<V1, S1>;
  handle<A, B, V1, S1>(f1: (x1: () => A) => B, f2: (x1: () => B) => Kyo<unknown, Emit<Chunk<V1>> & S1>): Stream<V1, S1>;
  handle<A, B, C, D, E, V1, S1>(f1: (x1: () => A) => B, f2: (x1: () => B) => C, f3: (x1: () => C) => D, f4: (x1: () => D) => E, f5: (x1: () => E) => Kyo<unknown, Emit<Chunk<V1>> & S1>): Stream<V1, S1>;
  handle<A, B, C, V1, S1>(f1: (x1: () => A) => B, f2: (x1: () => B) => C, f3: (x1: () => C) => Kyo<unknown, Emit<Chunk<V1>> & S1>): Stream<V1, S1>;
  handle<A, B, C, D, E, F, V1, S1>(f1: (x1: () => A) => B, f2: (x1: () => B) => C, f3: (x1: () => C) => D, f4: (x1: () => D) => E, f5: (x1: () => E) => F, f6: (x1: () => F) => Kyo<unknown, Emit<Chunk<V1>> & S1>): Stream<V1, S1>;
  handle<A, B, C, D, E, F, G, H, I, J, V1, S1>(f1: (x1: () => A) => B, f2: (x1: () => B) => C, f3: (x1: () => C) => D, f4: (x1: () => D) => E, f5: (x1: () => E) => F, f6: (x1: () => F) => G, f7: (x1: () => G) => H, f8: (x1: () => H) => I, f9: (x1: () => I) => J, f10: (x1: () => J) => Kyo<unknown, Emit<Chunk<V1>> & S1>): Stream<V1, S1>;
  handle<A, B, C, D, E, F, G, H, I, V1, S1>(f1: (x1: () => A) => B, f2: (x1: () => B) => C, f3: (x1: () => C) => D, f4: (x1: () => D) => E, f5: (x1: () => E) => F, f6: (x1: () => F) => G, f7: (x1: () => G) => H, f8: (x1: () => H) => I, f9: (x1: () => I) => Kyo<unknown, Emit<Chunk<V1>> & S1>): Stream<V1, S1>;
  handle<A, B, C, D, V1, S1>(f1: (x1: () => A) => B, f2: (x1: () => B) => C, f3: (x1: () => C) => D, f4: (x1: () => D) => Kyo<unknown, Emit<Chunk<V1>> & S1>): Stream<V1, S1>;
  into<VV, A, S2>(sink: Sink<VV, A, S2>): Kyo<A, S & S2>;
  map<VV, V2, S2>(f: (x1: VV) => Kyo<V2, S2>): Stream<V2, S & S2>;
  mapChunk<VV, V2, S2>(f: (x1: Chunk<VV>) => Kyo<V2[], S2>): Stream<V2, S & S2>;
  mapChunkPar<E, V2, S2>(f: (x1: Chunk<V>) => Kyo<Chunk<V2>, Abort<E> & Async & S2>): Stream<V2, Abort<E> & Async & S & S2>;
  mapChunkPar<E, V2, S2>(parallel: number, bufferSize: number, f: (x1: Chunk<V>) => Kyo<Chunk<V2>, Abort<E> & Async & S2>): Stream<V2, Abort<E> & Async & S & S2>;
  mapChunkParUnordered<E, V2, S2>(f: (x1: Chunk<V>) => Kyo<Chunk<V2>, Abort<E> & Async & S2>): Stream<V2, Abort<E> & Async & S & S2>;
  mapChunkParUnordered<E, V2, S2>(parallel: number, bufferSize: number, f: (x1: Chunk<V>) => Kyo<Chunk<V2>, Abort<E> & Async & S2>): Stream<V2, Abort<E> & Async & S & S2>;
  mapChunkPure<VV, V2>(f: (x1: Chunk<VV>) => V2[]): Stream<V2, S>;
  mapPar<E, V2, S2>(parallel: number, bufferSize: number, f: (x1: V) => Kyo<V2, Abort<E> & Async & S2>): Stream<V2, Abort<E> & Async & S & S2>;
  mapPar<E, V2, S2>(f: (x1: V) => Kyo<V2, Abort<E> & Async & S2>): Stream<V2, Abort<E> & Async & S & S2>;
  mapParUnordered<E, V2, S2>(f: (x1: V) => Kyo<V2, Abort<E> & Async & S2>): Stream<V2, Abort<E> & Async & S & S2>;
  mapParUnordered<E, V2, S2>(parallel: number, bufferSize: number, f: (x1: V) => Kyo<V2, Abort<E> & Async & S2>): Stream<V2, Abort<E> & Async & S & S2>;
  mapPure<VV, V2>(f: (x1: VV) => V2): Stream<V2, S>;
  merge<E, S2>(other: Stream<V, Abort<E> & S & Async>, bufferSize: number): Stream<V, Abort<E> & S & Async>;
  mergeHalting<E, S2>(other: Stream<V, Abort<E> & S & Async>, bufferSize: number): Stream<V, Abort<E> & S & S2 & Async>;
  mergeHaltingLeft<E>(other: Stream<V, Abort<E> & S & Async>, bufferSize: number): Stream<V, Abort<E> & S & Async>;
  mergeHaltingRight<E>(other: Stream<V, Abort<E> & S & Async>, bufferSize: number): Stream<V, Abort<E> & S & Async>;
  rechunk<VV>(chunkSize: number): Stream<VV, S>;
  run<VV>(): Kyo<Chunk<VV>, S>;
  splitAt<VV>(n: number): Kyo<[Chunk<VV>, Stream<VV, S>], S>;
  subscribe<T>(subscriber: Subscriber<unknown>): Kyo<Subscription, Scope & Sync & S>;
  take<VV>(n: number): Stream<VV, S>;
  takeWhile<VV, S2>(f: (x1: VV) => Kyo<boolean, S2>): Stream<VV, S & S2>;
  takeWhilePure<VV>(f: (x1: VV) => boolean): Stream<VV, S>;
  tap<VV, S1>(f: (x1: VV) => Kyo<unknown, S1>): Stream<VV, S & S1>;
  tapChunk<VV, S1>(f: (x1: Chunk<VV>) => Kyo<unknown, S1>): Stream<VV, S & S1>;
  toPublisher<T>(): Kyo<Publisher<T>, Scope & Sync & S>;

  static empty<V>(): Stream<V, unknown>;
  static unfold<A, V, S>(acc: A, chunkSize: number, f: (x1: A) => Kyo<Maybe<[V, A]>, S>): Stream<V, S>;
};