package kyo.grpc

import io.grpc.ServerServiceDefinition

/** A trait representing a Kyo gRPC service.
  *
  * This trait provides a common interface for all gRPC services, requiring implementations to provide a [[ServerServiceDefinition]] that
  * describes the service's methods and their handlers.
  *
  * Services implementing this trait can be easily converted to gRPC's `ServerServiceDefinition` through the provided implicit conversion.
  *
  * @note
  *   Implementations of this trait are typically generated by `kyo-grpc-code-gen` from protobuf service definitions rather than being
  *   manually implemented.
  */
trait Service:

    /** Returns the gRPC server service definition for this service.
      *
      * @return
      *   the [[ServerServiceDefinition]] that describes this service
      */
    def definition: ServerServiceDefinition

end Service

/** Companion object for [[Service]] providing utility conversions.
  */
object Service:

    /** Implicit conversion from [[Service]] to [[ServerServiceDefinition]].
      *
      * This conversion allows `Service` instances to be used directly wherever a `ServerServiceDefinition` is expected, providing seamless
      * integration with gRPC server builders and other APIs.
      *
      * @return
      *   a conversion function that extracts the `definition` from a `Service`
      */
    given Conversion[Service, ServerServiceDefinition] = _.definition

end Service
