name: Feature Request
description: Suggest a new feature or enhancement
title: "[feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Please describe the use case.
    validations:
      required: false

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see. Include example API usage if possible.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: current-workaround
    attributes:
      label: Current Workaround
      description: How are you currently working around this limitation?
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or references about the feature request here.
    validations:
      required: false