import java.nio.ByteBuffer
import java.nio.charset.CharacterCodingException
import java.nio.charset.CodingErrorAction
import java.nio.charset.StandardCharsets
import java.security.MessageDigest
import sbt.*

/** Turns vendored third-party test-vector files into a test source, so every platform reads them without a file system.
  *
  * A vector set is a directory under the module's `shared/src/test/vectors/` holding the upstream files byte for byte and a `MANIFEST`:
  *
  * {{{
  * source <url the files were fetched from: an archive, a document, or a repository tree pinned to a commit>
  * source-sha256 <sha-256 of what that url served, when it is a single archive or document>
  * license <terms the upstream publishes the files under>
  * file <name> <sha-256 of the file> <path inside the source>
  * }}}
  *
  * Only the `file` lines are read by the build; the others record provenance for a reviewer.
  *
  * The generator fails the build when a file in the set is not listed, a listed file is missing, or a digest differs, so a checked-in file
  * cannot drift from what its manifest says was fetched. It emits one object whose `text(set, name)` returns a file's content and
  * `sha256(set, name)` its manifest digest; parsing a format (CAVP `.rsp`, Wycheproof JSON) is left to the test that consumes it.
  *
  * Content is decoded as strict UTF-8 and embedded as string literals of at most `ChunkChars` characters, which keeps each literal inside
  * the JVM's 65535-byte constant limit. Files are written only when their text changes, so an unchanged set does not recompile the tests.
  */
object TestVectorsGen {

    private val ChunkChars = 16000

    final case class Entry(set: String, name: String, sha256: String, text: String)

    def generate(vectorsDir: File, outDir: File, pkg: String, objectName: String): Seq[File] = {
        val entries =
            if (!vectorsDir.exists) Seq.empty
            else IO.listFiles(vectorsDir).filter(_.isDirectory).sortBy(_.getName).toSeq.flatMap(readSet)
        val target = outDir / pkg.replace('.', '/') / s"$objectName.scala"
        val source = render(pkg, objectName, entries)
        if (!target.exists || IO.read(target, StandardCharsets.UTF_8) != source)
            IO.write(target, source, StandardCharsets.UTF_8)
        Seq(target)
    }

    private def readSet(dir: File): Seq[Entry] = {
        val set      = dir.getName
        val manifest = dir / "MANIFEST"
        if (!manifest.exists) sys.error(s"test vectors: $dir has no MANIFEST")
        val listed = IO
            .readLines(manifest, StandardCharsets.UTF_8)
            .map(_.trim)
            .filter(line => line.startsWith("file "))
            .map { line =>
                line.split("\\s+").toList match {
                    case _ :: name :: digest :: _ => name -> digest.toLowerCase
                    case _                        => sys.error(s"test vectors: malformed MANIFEST line in $set: $line")
                }
            }
        val present  = IO.listFiles(dir).filter(_.isFile).map(_.getName).filter(_ != "MANIFEST").toSet
        val unlisted = present -- listed.map(_._1)
        if (unlisted.nonEmpty)
            sys.error(s"test vectors: $set has files its MANIFEST does not list: ${unlisted.toSeq.sorted.mkString(", ")}")
        listed.map { case (name, expected) =>
            val file = dir / name
            if (!file.exists) sys.error(s"test vectors: $set/$name is listed in MANIFEST but missing")
            val bytes  = IO.readBytes(file)
            val actual = MessageDigest.getInstance("SHA-256").digest(bytes).map(b => f"${b & 0xff}%02x").mkString
            if (actual != expected) sys.error(s"test vectors: $set/$name has sha-256 $actual, MANIFEST says $expected")
            val text =
                try
                    StandardCharsets.UTF_8
                        .newDecoder()
                        .onMalformedInput(CodingErrorAction.REPORT)
                        .onUnmappableCharacter(CodingErrorAction.REPORT)
                        .decode(ByteBuffer.wrap(bytes))
                        .toString
                catch { case e: CharacterCodingException => sys.error(s"test vectors: $set/$name is not UTF-8: $e") }
            Entry(set, name, expected, text)
        }
    }

    private def render(pkg: String, objectName: String, entries: Seq[Entry]): String = {
        val sb = new StringBuilder
        sb.append(s"package $pkg\n\n")
        sb.append("// Generated by project/TestVectorsGen.scala from shared/src/test/vectors. Do not edit.\n")
        sb.append(s"object $objectName {\n\n")
        sb.append("    def names(set: String): Seq[String] = set match {\n")
        entries.groupBy(_.set).toSeq.sortBy(_._1).foreach { case (set, es) =>
            sb.append(s"        case ${literal(set)} => Seq(${es.map(e => literal(e.name)).mkString(", ")})\n")
        }
        sb.append("        case _ => Seq.empty\n    }\n\n")
        sb.append("    def sha256(set: String, name: String): String = s\"$set/$name\" match {\n")
        entries.foreach(e => sb.append(s"        case ${literal(e.set + "/" + e.name)} => ${literal(e.sha256)}\n"))
        sb.append("        case other => throw new NoSuchElementException(other)\n    }\n\n")
        sb.append("    def text(set: String, name: String): String = s\"$set/$name\" match {\n")
        entries.zipWithIndex.foreach { case (e, i) => sb.append(s"        case ${literal(e.set + "/" + e.name)} => file$i()\n") }
        sb.append("        case other => throw new NoSuchElementException(other)\n    }\n")
        entries.zipWithIndex.foreach { case (e, i) =>
            sb.append(s"\n    private def file$i(): String = {\n")
            sb.append(s"        val sb = new java.lang.StringBuilder(${e.text.length})\n")
            e.text.grouped(ChunkChars).foreach(chunk => sb.append(s"        sb.append(${literal(chunk)})\n"))
            sb.append("        sb.toString\n    }\n")
        }
        sb.append("}\n")
        sb.toString
    }

    private def literal(value: String): String = {
        val sb = new StringBuilder("\"")
        value.foreach {
            case '\\'                      => sb.append("\\\\")
            case '"'                       => sb.append("\\\"")
            case '\n'                      => sb.append("\\n")
            case '\r'                      => sb.append("\\r")
            case '\t'                      => sb.append("\\t")
            case c if c < 0x20 || c > 0x7e => sb.append(f"\\u${c.toInt}%04x")
            case c                         => sb.append(c)
        }
        sb.append('"').toString
    }
}
