Subject:  test
MIME-Version: 1.0
Content-Type: multipart/mixed;
	boundary="--boundary.1652331600846930886"

----boundary.1652331600846930886
Content-Type: multipart/alternative;
	boundary="--boundary.1652331600846930886-1"

----boundary.1652331600846930886-1
Content-Type: text/plain; charset=utf-8

Please see attachment for report Daily_Stats-2022-05-12-0700
----boundary.1652331600846930886-1
Content-Type: text/html; charset=utf-8

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	</head>
	<body>
		<p>Please see attachment for report Daily_Stats-2022-05-12-0700.</p>
	</body>
</html>
----boundary.1652331600846930886-1--
----boundary.1652331600846930886
Content-Type: application/pdf;
	name="Daily_Stats-2022-05-12-0700.pdf"
Content-Transfer-Encoding: base64
Content-Disposition: Attachment;
	filename="Daily_Stats-2022-05-12-0700.pdf"

JVBERi0xLj4Kc3RhcnR4cmVmCjUzNjEwCiUlRU9GCg==

----boundary.1652331600846930886--
