Return-Path: something@example.com
Date: Thu, 11 Apr 1996 01:10:30 -0500
From: Me <me@example.com>
MIME-Version: 1.0
Content-Type: multipart/digest; boundary="------------299A70B339B65A93542D2AE"

This is a multi-part message in MIME format.

--------------299A70B339B65A93542D2AE

Return-Path: something@example.com
Date: Thu, 11 Apr 1996 01:10:30 -0500
From: Me <me@example.com>
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="------------299A70B339B65A93542D2AF"

This is a nested multi-part message in MIME format.

--------------299A70B339B65A93542D2AF

--------------299A70B339B65A93542D2AF--

Nested epilogue
--------------299A70B339B65A93542D2AE--

Epilogue
