package kyo.internal.tools

import java.io.PrintWriter
import java.math.BigInteger
import java.nio.file.Files
import java.nio.file.Paths

/** Standalone generator that emits [[kyo.internal.FastFloatPow10Table]].
  *
  * Ported from Go's `strconv/atofeisel_pow10_gen.go` ([[https://github.com/golang/go/blob/master/src/strconv/atofeisel_pow10_gen.go
  * pow10gen.go]], BSD-3-Clause) to produce the same 128-bit powers-of-ten table used by the Eisel-Lemire algorithm.
  *
  * Algorithm reference: Daniel Lemire, "Number Parsing at a Gigabyte per Second", Software: Practice and Experience, 2021
  * ([[https://arxiv.org/abs/2101.11408 arXiv:2101.11408]]).
  *
  * Run via `sbt "kyo-schemaJVM/runMain kyo.internal.tools.FastFloatPow10Gen"` whenever the table needs regeneration; the emitted file is
  * checked in for build reproducibility.
  */
@main def FastFloatPow10Gen(): Unit =
    val minExp = -348
    val maxExp = 347

    val one    = BigInteger.ONE
    val ten    = BigInteger.TEN
    val b1p64  = one.shiftLeft(64)
    val b1p128 = one.shiftLeft(128)

    // For each exponent e, compute 10^e as a rational number, then scale it
    // into [2^127, 2^128) by multiplying or dividing by 2.
    // That gives a 128-bit integer d in [2^127, 2^128).
    // Split d into (hi, lo) = (d >> 64, d & (2^64 - 1)).
    //
    // This is a direct port of Go's pow10gen.go logic.
    val entries = (minExp to maxExp).map { e =>
        // Compute 10^e as a (numerator, denominator) rational
        val (num, den) =
            if e >= 0 then
                (ten.pow(e), one)
            else
                (one, ten.pow(-e))

        // Scale rational into [2^127, 2^128) by multiplying/dividing by 2.
        // We track the scaling exponent `be` but don't need it for the table.
        // Use mutable state to mirror Go's r.Mul(r, r2) / r.Quo(r, r2).
        var curNum = num
        var curDen = den

        // Scale up while rational < 2^128
        while {
            // Check if curNum/curDen < b1p128
            // i.e. curNum < b1p128 * curDen
            curNum.compareTo(b1p128.multiply(curDen)) < 0
        } do
            curNum = curNum.shiftLeft(1) // multiply by 2
        end while

        // Scale down while rational >= 2^128
        while {
            curNum.compareTo(b1p128.multiply(curDen)) >= 0
        } do
            curDen = curDen.shiftLeft(1) // divide by 2
        end while

        // d = floor(curNum / curDen) — the 128-bit integer in [2^127, 2^128)
        val d = curNum.divide(curDen)

        // Split into hi (top 64 bits) and lo (bottom 64 bits)
        val hi = d.shiftRight(64)
        val lo = d.and(b1p64.subtract(one))

        (hi.longValue(), lo.longValue())
    }

    // Self-test: verify spot-check values against Go's published table
    case class Check(idx: Int, expectedHi: Long, expectedLo: Long, label: String)
    val checks = List(
        Check(0, 0xfa8fd5a0081c0288L, 0x1732c869cd60e453L, "10^-348"),
        Check(348, 0x8000000000000000L, 0x0000000000000000L, "10^0"),
        Check(349, 0xa000000000000000L, 0x0000000000000000L, "10^1"),
        Check(370, 0x878678326eac9000L, 0x0000000000000000L, "10^22"),
        Check(695, 0xd13eb46469447567L, 0x4b7195f2d2d1a9fbL, "10^347")
    )
    for c <- checks do
        val (gotHi, gotLo) = entries(c.idx)
        if gotHi != c.expectedHi || gotLo != c.expectedLo then
            System.err.println(
                s"SPOT-CHECK FAILED for ${c.label} (index ${c.idx}):\n" +
                    s"  expected hi=${fmtHex(c.expectedHi)} lo=${fmtHex(c.expectedLo)}\n" +
                    s"  got     hi=${fmtHex(gotHi)} lo=${fmtHex(gotLo)}"
            )
            sys.exit(1)
        end if
    end for
    System.err.println(s"All ${checks.length} spot-checks passed.")

    // Build output
    val sb = new StringBuilder
    sb.append("package kyo.internal\n\n")
    sb.append("// Generated by FastFloatPow10Gen. Do not edit by hand.\n")
    sb.append("// Powers of ten 10^q for q in [-348, +347], split into (hi: Array[Long], lo: Array[Long]).\n")
    sb.append("// Each (hi(i), lo(i)) is the 128-bit approximation of 10^(pow10Min + i) normalized so hi's top bit is set.\n")
    sb.append("// Used by the Eisel-Lemire fast-path double parsing.\n")
    sb.append("private[internal] object FastFloatPow10Table:\n")
    sb.append("    val pow10Min: Int = -348\n")
    sb.append("    val pow10Max: Int = 347\n")
    sb.append("\n")

    // pow10Hi array
    sb.append("    val pow10Hi: Array[Long] = Array(\n")
    for i <- entries.indices do
        val e       = minExp + i
        val hi      = entries(i)._1
        val comment = s"// 10^$e"
        val sep     = if i < entries.length - 1 then "," else ""
        sb.append(s"        ${fmtHex(hi)}$sep  $comment\n")
    end for
    sb.append("    )\n\n")

    // pow10Lo array
    sb.append("    val pow10Lo: Array[Long] = Array(\n")
    for i <- entries.indices do
        val e       = minExp + i
        val lo      = entries(i)._2
        val comment = s"// 10^$e"
        val sep     = if i < entries.length - 1 then "," else ""
        sb.append(s"        ${fmtHex(lo)}$sep  $comment\n")
    end for
    sb.append("    )\n")

    // Resolve the output path.
    // When run via `sbt "kyo-schema/runMain ..."` (forked), user.dir = <worktree>/kyo-schema/jvm.
    // Walk up two levels to reach the worktree root, then resolve the shared path.
    val jvmDir   = Paths.get(System.getProperty("user.dir"))
    val worktree = jvmDir.getParent.getParent // kyo-schema/jvm -> kyo-schema -> worktree
    val outPath  = worktree.resolve("kyo-schema/shared/src/main/scala/kyo/internal/FastFloatPow10Table.scala")
    Files.createDirectories(outPath.getParent)
    Files.writeString(outPath, sb.toString())
    System.err.println(s"Wrote ${entries.length} entries to $outPath")

end FastFloatPow10Gen

private def fmtHex(v: Long): String =
    // Format as 0x...L with exactly 16 hex digits
    val hex    = java.lang.Long.toUnsignedString(v, 16)
    val padded = "0" * (16 - hex.length) + hex
    s"0x${padded}L"
end fmtHex

extension (s: String)
    private def padLeft(n: Int): String =
        "0" * (n - s.length) + s
