package kyo.ffi.codegen.emitters

import EmitterFixtures.*
import kyo.ffi.codegen.model.*

/** Round-trip test: verifies that each emitter produces output that is
  *   1. Non-empty and structurally well-formed (contains expected Scala markers),
  *   2. Syntactically valid Scala 3 (as confirmed by ScalaParseProbe), and
  *   3. Consistently produced by all three emitters for a shared fixture.
  */
class EmitterRoundTripTest extends kyo.test.Test[Any]:

    // -------------------------------------------------------------------------
    // Shared fixtures
    // -------------------------------------------------------------------------

    private val simpleSpec = mkTrait(
        "Simple",
        "simple",
        List(
            mkMethod("noop", "noop", Nil, ReturnShape.Void)
        )
    )

    private val multiMethodSpec = mkTrait(
        "TcpBindings",
        "kyo_tcp",
        List(
            mkMethod(
                "tcpClose",
                "tcp_close",
                List(ParamSpec("fd", TypeRef.IntT)),
                ReturnShape.Void
            ),
            mkMethod(
                "tcpRead",
                "tcp_read",
                List(
                    ParamSpec("fd", TypeRef.IntT),
                    ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT)),
                    ParamSpec("maxLen", TypeRef.IntT)
                ),
                ReturnShape.Primitive(TypeRef.IntT),
                blocking = true
            ),
            mkMethod(
                "tcpWrite",
                "tcp_write",
                List(
                    ParamSpec("fd", TypeRef.IntT),
                    ParamSpec("data", TypeRef.ArrayT(TypeRef.ByteT)),
                    ParamSpec("len", TypeRef.IntT)
                ),
                ReturnShape.Primitive(TypeRef.IntT)
            )
        )
    )

    private val structSpec: TraitSpec =
        val cr = StructSpec(
            "kyo.example.ConnectResult",
            "ConnectResult",
            List(StructField("fd", TypeRef.IntT), StructField("pending", TypeRef.IntT)),
            packed = false
        )
        mkTrait(
            "TcpConnect",
            "kyo_tcp",
            List(
                mkMethod(
                    "tcpConnect",
                    "tcp_connect",
                    List(ParamSpec("host", TypeRef.StringT), ParamSpec("port", TypeRef.IntT)),
                    ReturnShape.MultiValue(cr),
                    blocking = true
                )
            ),
            structs = List(cr)
        )
    end structSpec

    // -------------------------------------------------------------------------
    // Helper: count opening vs closing braces
    // -------------------------------------------------------------------------

    private def hasBalancedBraces(src: String): Boolean =
        var depth = 0
        for ch <- src do
            if ch == '{' then depth += 1
            else if ch == '}' then depth -= 1
        depth == 0
    end hasBalancedBraces

    // -------------------------------------------------------------------------
    // JvmEmitter round-trip
    // -------------------------------------------------------------------------

    "JvmEmitter round-trip, simple spec" - {

        "output is non-empty" in {
            val src = JvmEmitter.emit(simpleSpec)
            assert(src.nonEmpty)
        }

        "output parses as valid Scala 3" in {
            val src            = JvmEmitter.emit(simpleSpec)
            val (ok, errorMsg) = ScalaParseProbe.parses(src)
            assert(ok == true, s"Parse errors:\n$errorMsg\n\nSource:\n$src\n")
        }

        "output contains the AUTO-GENERATED banner" in {
            val src = JvmEmitter.emit(simpleSpec)
            assert(src.startsWith("// AUTO-GENERATED by kyo-ffi-codegen"))
        }

        "output contains the package declaration" in {
            val src = JvmEmitter.emit(simpleSpec)
            assert(src.contains("package kyo.example"))
        }

        "output contains the impl class declaration" in {
            val src = JvmEmitter.emit(simpleSpec)
            assert(src.contains("class SimpleImpl"))
        }

        "output contains AbiCheck.verify" in {
            val src = JvmEmitter.emit(simpleSpec)
            assert(src.contains("AbiCheck.verify"))
        }

        "output contains NativeLoader.load" in {
            val src = JvmEmitter.emit(simpleSpec)
            assert(src.contains("NativeLoader.load"))
        }

        "output has balanced braces" in {
            val src = JvmEmitter.emit(simpleSpec)
            assert(hasBalancedBraces(src) == true)
        }
    }

    "JvmEmitter round-trip, multi-method spec" - {

        "output parses as valid Scala 3" in {
            val src            = JvmEmitter.emit(multiMethodSpec)
            val (ok, errorMsg) = ScalaParseProbe.parses(src)
            assert(ok == true, s"Parse errors:\n$errorMsg\n\nSource:\n$src\n")
        }

        "output contains impl class declaration" in {
            val src = JvmEmitter.emit(multiMethodSpec)
            assert(src.contains("class TcpBindingsImpl"))
        }

        "output contains def for each method" in {
            val src = JvmEmitter.emit(multiMethodSpec)
            assert(src.contains("def tcpClose"))
            assert(src.contains("def tcpRead"))
            assert(src.contains("def tcpWrite"))
        }

        "output has balanced braces" in {
            val src = JvmEmitter.emit(multiMethodSpec)
            assert(hasBalancedBraces(src) == true)
        }
    }

    "JvmEmitter round-trip, struct/multi-value spec" - {

        "output parses as valid Scala 3" in {
            val src            = JvmEmitter.emit(structSpec)
            val (ok, errorMsg) = ScalaParseProbe.parses(src)
            assert(ok == true, s"Parse errors:\n$errorMsg\n\nSource:\n$src\n")
        }

        "output contains def for the multi-value method" in {
            val src = JvmEmitter.emit(structSpec)
            assert(src.contains("def tcpConnect"))
        }

        "output has balanced braces" in {
            val src = JvmEmitter.emit(structSpec)
            assert(hasBalancedBraces(src) == true)
        }
    }

    // -------------------------------------------------------------------------
    // NativeEmitter round-trip
    // -------------------------------------------------------------------------

    "NativeEmitter round-trip, simple spec" - {

        "output is non-empty" in {
            val src = NativeEmitter.emit(simpleSpec)
            assert(src.nonEmpty)
        }

        "output parses as valid Scala 3" in {
            val src            = NativeEmitter.emit(simpleSpec)
            val (ok, errorMsg) = ScalaParseProbe.parses(src)
            assert(ok == true, s"Parse errors:\n$errorMsg\n\nSource:\n$src\n")
        }

        "output contains the AUTO-GENERATED banner" in {
            val src = NativeEmitter.emit(simpleSpec)
            assert(src.startsWith("// AUTO-GENERATED by kyo-ffi-codegen"))
        }

        "output contains the package declaration" in {
            val src = NativeEmitter.emit(simpleSpec)
            assert(src.contains("package kyo.example"))
        }

        "output contains the impl class declaration" in {
            val src = NativeEmitter.emit(simpleSpec)
            assert(src.contains("class SimpleImpl"))
        }

        "output contains AbiCheck.verify" in {
            val src = NativeEmitter.emit(simpleSpec)
            assert(src.contains("AbiCheck.verify"))
        }

        "output has balanced braces" in {
            val src = NativeEmitter.emit(simpleSpec)
            assert(hasBalancedBraces(src) == true)
        }
    }

    "NativeEmitter round-trip, multi-method spec" - {

        "output parses as valid Scala 3" in {
            val src            = NativeEmitter.emit(multiMethodSpec)
            val (ok, errorMsg) = ScalaParseProbe.parses(src)
            assert(ok == true, s"Parse errors:\n$errorMsg\n\nSource:\n$src\n")
        }

        "output contains impl class declaration" in {
            val src = NativeEmitter.emit(multiMethodSpec)
            assert(src.contains("class TcpBindingsImpl"))
        }

        "output contains def for each method" in {
            val src = NativeEmitter.emit(multiMethodSpec)
            assert(src.contains("def tcpClose"))
            assert(src.contains("def tcpRead"))
            assert(src.contains("def tcpWrite"))
        }

        "output has balanced braces" in {
            val src = NativeEmitter.emit(multiMethodSpec)
            assert(hasBalancedBraces(src) == true)
        }
    }

    "NativeEmitter round-trip, struct/multi-value spec" - {

        "output parses as valid Scala 3" in {
            val src            = NativeEmitter.emit(structSpec)
            val (ok, errorMsg) = ScalaParseProbe.parses(src)
            assert(ok == true, s"Parse errors:\n$errorMsg\n\nSource:\n$src\n")
        }

        "output contains def for the multi-value method" in {
            val src = NativeEmitter.emit(structSpec)
            assert(src.contains("def tcpConnect"))
        }

        "output has balanced braces" in {
            val src = NativeEmitter.emit(structSpec)
            assert(hasBalancedBraces(src) == true)
        }
    }

    // -------------------------------------------------------------------------
    // JsEmitter round-trip
    // -------------------------------------------------------------------------

    "JsEmitter round-trip, simple spec" - {

        "output is non-empty" in {
            val src = JsEmitter.emit(simpleSpec)
            assert(src.nonEmpty)
        }

        "output parses as valid Scala 3" in {
            val src            = JsEmitter.emit(simpleSpec)
            val (ok, errorMsg) = ScalaParseProbe.parses(src)
            assert(ok == true, s"Parse errors:\n$errorMsg\n\nSource:\n$src\n")
        }

        "output contains the AUTO-GENERATED banner" in {
            val src = JsEmitter.emit(simpleSpec)
            assert(src.startsWith("// AUTO-GENERATED by kyo-ffi-codegen"))
        }

        "output contains the package declaration" in {
            val src = JsEmitter.emit(simpleSpec)
            assert(src.contains("package kyo.example"))
        }

        "output contains the impl class declaration" in {
            val src = JsEmitter.emit(simpleSpec)
            assert(src.contains("class SimpleImpl"))
        }

        "output contains AbiCheck.verify" in {
            val src = JsEmitter.emit(simpleSpec)
            assert(src.contains("AbiCheck.verify"))
        }

        "output contains NativeLoader.jsResolve" in {
            val src = JsEmitter.emit(simpleSpec)
            assert(src.contains("NativeLoader.jsResolve"))
        }

        "output has balanced braces" in {
            val src = JsEmitter.emit(simpleSpec)
            assert(hasBalancedBraces(src) == true)
        }
    }

    "JsEmitter round-trip, multi-method spec" - {

        "output parses as valid Scala 3" in {
            val src            = JsEmitter.emit(multiMethodSpec)
            val (ok, errorMsg) = ScalaParseProbe.parses(src)
            assert(ok == true, s"Parse errors:\n$errorMsg\n\nSource:\n$src\n")
        }

        "output contains impl class declaration" in {
            val src = JsEmitter.emit(multiMethodSpec)
            assert(src.contains("class TcpBindingsImpl"))
        }

        "output contains def for each method" in {
            val src = JsEmitter.emit(multiMethodSpec)
            assert(src.contains("def tcpClose"))
            assert(src.contains("def tcpRead"))
            assert(src.contains("def tcpWrite"))
        }

        "output has balanced braces" in {
            val src = JsEmitter.emit(multiMethodSpec)
            assert(hasBalancedBraces(src) == true)
        }
    }

    "JsEmitter round-trip, struct/multi-value spec" - {

        "output parses as valid Scala 3" in {
            val src            = JsEmitter.emit(structSpec)
            val (ok, errorMsg) = ScalaParseProbe.parses(src)
            assert(ok == true, s"Parse errors:\n$errorMsg\n\nSource:\n$src\n")
        }

        "output contains def for the multi-value method" in {
            val src = JsEmitter.emit(structSpec)
            assert(src.contains("def tcpConnect"))
        }

        "output has balanced braces" in {
            val src = JsEmitter.emit(structSpec)
            assert(hasBalancedBraces(src) == true)
        }
    }

    // -------------------------------------------------------------------------
    // Cross-emitter consistency
    // -------------------------------------------------------------------------

    "all three emitters produce non-empty output for the same fixture" in {
        val jvmSrc    = JvmEmitter.emit(simpleSpec)
        val nativeSrc = NativeEmitter.emit(simpleSpec)
        val jsSrc     = JsEmitter.emit(simpleSpec)
        assert(jvmSrc.nonEmpty)
        assert(nativeSrc.nonEmpty)
        assert(jsSrc.nonEmpty)
    }

    "all three emitters produce syntactically valid Scala for the multi-method fixture" in {
        val fixtures = List(simpleSpec, multiMethodSpec, structSpec)
        for fixture <- fixtures do
            val jvmSrc    = JvmEmitter.emit(fixture)
            val nativeSrc = NativeEmitter.emit(fixture)
            val jsSrc     = JsEmitter.emit(fixture)

            val (jvmOk, jvmErrors)       = ScalaParseProbe.parses(jvmSrc)
            val (nativeOk, nativeErrors) = ScalaParseProbe.parses(nativeSrc)
            val (jsOk, jsErrors)         = ScalaParseProbe.parses(jsSrc)

            assert(jvmOk == true, s"JVM parse errors for ${fixture.simpleName}:\n$jvmErrors")
            assert(nativeOk == true, s"Native parse errors for ${fixture.simpleName}:\n$nativeErrors")
            assert(jsOk == true, s"JS parse errors for ${fixture.simpleName}:\n$jsErrors")
        end for
    }

    "all three emitters include the impl class name in their output" in {
        val fixtures = List(simpleSpec, multiMethodSpec, structSpec)
        for fixture <- fixtures do
            val implClassName = s"${fixture.simpleName}Impl"
            val jvmSrc        = JvmEmitter.emit(fixture)
            val nativeSrc     = NativeEmitter.emit(fixture)
            val jsSrc         = JsEmitter.emit(fixture)
            assert(jvmSrc.contains(implClassName), s"JVM missing impl class for ${fixture.simpleName}")
            assert(nativeSrc.contains(implClassName), s"Native missing impl class for ${fixture.simpleName}")
            assert(jsSrc.contains(implClassName), s"JS missing impl class for ${fixture.simpleName}")
        end for
    }

end EmitterRoundTripTest
