package kyo.ffi.codegen.emitters

import EmitterFixtures.*
import kyo.ffi.codegen.model.*

class JsEmitterTest extends kyo.test.Test[Any]:

    // -------------------------------------------------------------------------
    // Section 1: header / companion basics
    // -------------------------------------------------------------------------

    "emits an AUTO-GENERATED banner, package clause, and JS imports" in {
        val spec = mkTrait(
            "Simple",
            "simple",
            List(mkMethod("noop", "noop", Nil, ReturnShape.Void))
        )
        val src = JsEmitter.emit(spec)
        assert(src.startsWith("// AUTO-GENERATED by kyo-ffi-codegen"))
        assert(src.contains("package kyo.example"))
        assert(src.contains("import scala.scalajs.js"))
        assert(src.contains("import scala.scalajs.js.annotation.*"))
        assert(src.contains("import scala.scalajs.js.typedarray.*"))
        assert(src.contains("import scala.scalajs.reflect.annotation.EnableReflectiveInstantiation"))
        assert(src.contains("import kyo.ffi.*"))
        assert(src.contains(
            "import kyo.ffi.internal.{AbiCheck, JsRawSegment, KoffiFacade, KoffiFn, NativeLoader, StructAbiCheck}"
        ))
    }

    "impl class is annotated with @EnableReflectiveInstantiation so Ffi.load can reach it" in {
        val spec = mkTrait(
            "Simple",
            "simple",
            List(mkMethod("noop", "noop", Nil, ReturnShape.Void))
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("@EnableReflectiveInstantiation final class SimpleImpl extends Simple:"))
    }

    "companion calls AbiCheck.verify and loads via NativeLoader.jsResolve" in {
        val spec = mkTrait(
            "TcpBindings",
            "kyo_tcp",
            List(mkMethod("tcpClose", "tcp_close", List(ParamSpec("fd", TypeRef.IntT)), ReturnShape.Void))
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("""AbiCheck.verify(1, "kyo.example.TcpBindings")"""))
        assert(src.contains("""NativeLoader.jsResolve("kyo_tcp")"""))
        assert(src.contains("private val facade = KoffiFacade.load("))
    }

    // -------------------------------------------------------------------------
    // Section 2: KoffiFn emission per-method
    // -------------------------------------------------------------------------

    "emits a KoffiFn with scalaName, cSymbol, result, and arg types" in {
        val spec = mkTrait(
            "TcpBindings",
            "kyo_tcp",
            List(
                mkMethod(
                    "tcpClose",
                    "tcp_close",
                    List(ParamSpec("fd", TypeRef.IntT)),
                    ReturnShape.Void
                )
            )
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("""KoffiFn("tcpClose", "tcp_close", "void", Seq[js.Any]("int".asInstanceOf[js.Any]))"""))
    }

    "multi-value return appends `<T>*` trailing entries to the KoffiFn args list" in {
        val cr = StructSpec(
            "kyo.example.ConnectResult",
            "ConnectResult",
            List(StructField("fd", TypeRef.IntT), StructField("pending", TypeRef.IntT)),
            packed = false
        )
        val spec = mkTrait(
            "TcpBindings",
            "kyo_tcp",
            List(mkMethod(
                "tcpConnect",
                "tcp_connect",
                List(ParamSpec("host", TypeRef.StringT), ParamSpec("port", TypeRef.IntT)),
                ReturnShape.MultiValue(cr),
                blocking = true
            )),
            structs = List(cr)
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains(
            """KoffiFn("tcpConnect", "tcp_connect", "int", Seq[js.Any]("string".asInstanceOf[js.Any], "int".asInstanceOf[js.Any], "int*".asInstanceOf[js.Any]))"""
        ))
    }

    "Buffer params map to \"void*\" in the KoffiFn args" in {
        val spec = mkTrait(
            "TcpBindings",
            "kyo_tcp",
            List(mkMethod(
                "tcpRead",
                "tcp_read",
                List(
                    ParamSpec("fd", TypeRef.IntT),
                    ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT)),
                    ParamSpec("maxLen", TypeRef.IntT)
                ),
                ReturnShape.Primitive(TypeRef.IntT),
                blocking = true
            ))
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains(
            """KoffiFn("tcpRead", "tcp_read", "int", Seq[js.Any]("int".asInstanceOf[js.Any], "void*".asInstanceOf[js.Any], "int".asInstanceOf[js.Any]))"""
        ))
    }

    // -------------------------------------------------------------------------
    // Section 2b: Boolean return / param / struct field marshalling (C `int` ABI)
    // -------------------------------------------------------------------------

    "Boolean-return method registers koffi result \"int\" (not \"bool\") and converts via != 0" in {
        // The C ABI for a Boolean-typed binding is `int` (1/0). The koffi registration must agree with the
        // Scala-side `.asInstanceOf[Int] != 0` conversion (matching JvmEmitter's JAVA_INT / NativeEmitter's
        // CInt). Registering "bool" while casting to Int mis-marshals the result (the original JS bug).
        val spec = mkTrait(
            "ProbeBindings",
            "kyo_probe",
            List(mkMethod("available", "probe_available", Nil, ReturnShape.Primitive(TypeRef.BooleanT)))
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("""KoffiFn("available", "probe_available", "int", Seq[js.Any]())"""))
        assert(src.contains("val retVal = facade.available().asInstanceOf[Int]"))
        assert(src.contains("retVal != 0"))
        assert(!src.contains("\"bool\""))
    }

    "Boolean param registers koffi arg \"int\" and passes 1/0" in {
        val spec = mkTrait(
            "FlagBindings",
            "kyo_flag",
            List(mkMethod("setFlag", "set_flag", List(ParamSpec("on", TypeRef.BooleanT)), ReturnShape.Void))
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("""KoffiFn("setFlag", "set_flag", "void", Seq[js.Any]("int".asInstanceOf[js.Any]))"""))
        assert(src.contains("facade.setFlag(if on then 1 else 0)"))
        assert(!src.contains("\"bool\""))
    }

    "Boolean struct field registers koffi \"int\" and the multi-value out-param uses \"int*\"" in {
        val rr = StructSpec(
            "kyo.example.ReadResult",
            "ReadResult",
            List(StructField("bytesRead", TypeRef.IntT), StructField("eof", TypeRef.BooleanT)),
            packed = false
        )
        val spec = mkTrait(
            "ReadBindings",
            "kyo_read",
            List(mkMethod(
                "readInto",
                "read_into",
                List(ParamSpec("fd", TypeRef.IntT), ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT))),
                ReturnShape.MultiValue(rr),
                blocking = true
            )),
            structs = List(rr)
        )
        val src = JsEmitter.emit(spec)
        // struct registration: Boolean field → "int"
        assert(src.contains("""js.Dynamic.literal("bytesRead" -> "int".asInstanceOf[js.Any], "eof" -> "int".asInstanceOf[js.Any])"""))
        // out-param koffi type for the Boolean tail field → "int*"
        assert(src.contains("\"int*\".asInstanceOf[js.Any]"))
        // out-cell allocated as an int cell, read and converted via != 0
        assert(src.contains("val eofOut = KoffiFacade.outInt()"))
        assert(src.contains("eofOut.read().asInstanceOf[Int] != 0"))
        assert(!src.contains("\"bool\""))
        assert(!src.contains("\"bool*\""))
    }

    "Boolean callback param/return keep koffi proto \"bool\" (Scala side is a genuine Boolean)" in {
        // Callback (proto) positions are NOT func-ABI positions: the Scala wrapper exchanges a real Boolean
        // with koffi there, so they stay "bool" while func/struct/out-param Booleans become "int". This mirrors
        // JvmEmitter's callbackValueLayout (JAVA_BOOLEAN) vs paramLayout (JAVA_INT) split.
        val spec = mkTrait(
            "PredBindings",
            "kyo_pred",
            List(mkMethod(
                "filter",
                "filter",
                List(
                    ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT)),
                    ParamSpec("pred", TypeRef.FnPtrT(List(TypeRef.BooleanT), TypeRef.BooleanT))
                ),
                ReturnShape.Void,
                kind = CallbackKind.Transient
            ))
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("""KoffiFacade.proto("filter_pred_proto", "bool", Seq[String]("bool"))"""))
    }

    // -------------------------------------------------------------------------
    // Section 3: impl-class body, marshalling
    // -------------------------------------------------------------------------

    "primitive-only method body calls facade (no errno capture for plain returns)" in {
        val spec = mkTrait(
            "Math",
            "kyo_math",
            List(
                mkMethod(
                    "add",
                    "add_ints",
                    List(ParamSpec("a", TypeRef.IntT), ParamSpec("b", TypeRef.IntT)),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            )
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("def add(a: Int, b: Int)(using kyo.AllowUnsafe): Int ="))
        assert(src.contains("val retVal = facade.add(a, b).asInstanceOf[Int]"))
        assert(!src.contains("val __errno = KoffiFacade.errno()"))
    }

    "Buffer param casts .raw to Uint8Array" in {
        val spec = mkTrait(
            "TcpBindings",
            "kyo_tcp",
            List(
                mkMethod(
                    "tcpRead",
                    "tcp_read",
                    List(
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("maxLen", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                )
            )
        )
        val src = JsEmitter.emit(spec)
        // `Buffer.Raw` unwrap routes through `FfiUnsafe.expect`.
        assert(src.contains(
            """val bufU8 = kyo.ffi.internal.FfiUnsafe.expect[JsRawSegment](buf.raw.asInstanceOf[AnyRef], classOf[JsRawSegment], "JsRawSegment on JS", "kyo.example.TcpBindings", "tcpRead").u8a"""
        ))
        // tcpRead is @Ffi.blocking: the koffi call runs via `BlockingBridge.runAsync` (which dispatches through
        // `KoffiFacade.callAsync`) on a libuv worker; the unwrapped `bufU8` is threaded into the async arg array.
        assert(src.contains(
            """kyo.ffi.internal.BlockingBridge.runAsync(facade, "tcpRead", js.Array[js.Any](fd, bufU8, maxLen), (raw: js.Any) =>"""
        ))
    }

    "multi-value return allocates KoffiFacade.outInt() cells and reads them post-call" in {
        val cr = StructSpec(
            "kyo.example.ConnectResult",
            "ConnectResult",
            List(StructField("fd", TypeRef.IntT), StructField("pending", TypeRef.IntT)),
            packed = false
        )
        val spec = mkTrait(
            "TcpBindings",
            "kyo_tcp",
            List(mkMethod(
                "tcpConnect",
                "tcp_connect",
                List(ParamSpec("host", TypeRef.StringT), ParamSpec("port", TypeRef.IntT)),
                ReturnShape.MultiValue(cr),
                blocking = true
            )),
            structs = List(cr)
        )
        val src = JsEmitter.emit(spec)
        // The out-cell is allocated before the async call so it outlives the call and is read back in the
        // completion callback. tcpConnect is @Ffi.blocking: the koffi return `raw` is marshalled in the callback.
        assert(src.contains("val pendingOut = KoffiFacade.outInt()"))
        assert(src.contains(
            """kyo.ffi.internal.BlockingBridge.runAsync(facade, "tcpConnect", js.Array[js.Any](host, port, pendingOut.buf), (raw: js.Any) =>"""
        ))
        assert(src.contains("val retVal = raw.asInstanceOf[Int]"))
        assert(src.contains("kyo.example.ConnectResult(retVal, pendingOut.read().asInstanceOf[Int])"))
    }

    "Unit-return method calls facade, then `()`, no retVal cast" in {
        val spec = mkTrait(
            "Simple",
            "simple",
            List(mkMethod("close", "do_close", List(ParamSpec("fd", TypeRef.IntT)), ReturnShape.Void))
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("facade.close(fd)"))
        assert(!src.contains("val retVal"))
    }

    // -------------------------------------------------------------------------
    // Section 3b: callback emission (transient + retained)
    // -------------------------------------------------------------------------

    "transient callback: body passes the raw Scala function directly to the facade call (no register/unregister)" in {
        val spec = mkTrait(
            "SortBindings",
            "kyo_sort",
            List(
                mkMethod(
                    "qsort",
                    "qsort",
                    List(
                        ParamSpec("base", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("count", TypeRef.IntT),
                        ParamSpec("elemSize", TypeRef.IntT),
                        ParamSpec("cmp", TypeRef.FnPtrT(List(TypeRef.IntT, TypeRef.IntT), TypeRef.IntT))
                    ),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src = JsEmitter.emit(spec)
        // Signature uses the function type, not a guard.
        assert(src.contains(
            "def qsort(base: Buffer[Byte], count: Int, elemSize: Int, cmp: (Int, Int) => Int)(using kyo.AllowUnsafe): Unit ="
        ))
        // The user callback is wrapped in a safe closure that catches exceptions and returns a typed zero
        // (here `0` for `Int`). The wrapped `cmpSafe` is passed to facade.
        assert(src.contains("val cmpSafe: (Int, Int) => Int = (a0: Int, a1: Int) =>"))
        assert(src.contains("try cmp(a0, a1)"))
        assert(src.contains("catch case t: Throwable =>"))
        assert(src.contains("""kyo.ffi.internal.FfiGenErrors.reportCallbackFailed("kyo.example.SortBindings", "qsort", "transient", t)"""))
        assert(src.contains("facade.qsort(baseU8, count, elemSize, cmpSafe)"))
        // No KoffiFacade.register / unregister calls in the transient body.
        assert(!src.contains("KoffiFacade.register(cmp"))
        assert(!src.contains("KoffiFacade.unregister"))
        // No guard retain on transient.
        assert(!src.contains("asInstanceOf[kyo.ffi.internal.JsGuard]"))
    }

    "transient callback: companion declares the proto up-front and KoffiFn emits KoffiFacade.pointer at the callback slot" in {
        val spec = mkTrait(
            "SortBindings",
            "kyo_sort",
            List(
                mkMethod(
                    "qsort",
                    "qsort",
                    List(
                        ParamSpec("base", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("count", TypeRef.IntT),
                        ParamSpec("elemSize", TypeRef.IntT),
                        ParamSpec("cmp", TypeRef.FnPtrT(List(TypeRef.IntT, TypeRef.IntT), TypeRef.IntT))
                    ),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src = JsEmitter.emit(spec)
        // Proto registration in the companion, the Seq[KoffiFn] entry references this handle through KoffiFacade.pointer.
        assert(src.contains(
            """KoffiFacade.proto("qsort_cmp_proto", "int", Seq[String]("int", "int"))"""
        ))
        // KoffiFn entry threads the proto handle via `KoffiFacade.pointer(<protoVal>)` at the callback arg slot.
        assert(src.contains(
            """KoffiFn("qsort", "qsort", "void", Seq[js.Any]("void*".asInstanceOf[js.Any], "int".asInstanceOf[js.Any], "int".asInstanceOf[js.Any], KoffiFacade.pointer(qsort_cmp_proto)))"""
        ))
    }

    "retained callback: body registers the stub, pins it on the guard, and does NOT unregister post-call" in {
        val spec = mkTrait(
            "Epoll",
            "kyo_epoll",
            List(
                mkMethod(
                    "epollAdd",
                    "epoll_add",
                    List(
                        ParamSpec("guard", TypeRef.GuardT),
                        ParamSpec("epfd", TypeRef.IntT),
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("onEvent", TypeRef.FnPtrT(List(TypeRef.IntT), TypeRef.UnitT))
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    kind = CallbackKind.Retained
                )
            )
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("def epollAdd(guard: Ffi.Guard, epfd: Int, fd: Int, onEvent: Int => Unit)(using kyo.AllowUnsafe): Int ="))
    }

    "retained callback: body registers the handle, schedules close-time unregister on the guard, and does NOT unregister post-call" in {
        val spec = mkTrait(
            "Epoll",
            "kyo_epoll",
            List(
                mkMethod(
                    "epollAdd",
                    "epoll_add",
                    List(
                        ParamSpec("guard", TypeRef.GuardT),
                        ParamSpec("epfd", TypeRef.IntT),
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("onEvent", TypeRef.FnPtrT(List(TypeRef.IntT), TypeRef.UnitT))
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    kind = CallbackKind.Retained
                )
            )
        )
        val src = JsEmitter.emit(spec)
        // Proto registered once in the companion as a private `val`; body forwards the handle into
        // `KoffiFacade.register`'s `js.Any` slot, wrapped in `KoffiFacade.pointer(...)`.
        // The user callback is wrapped in a try/catch and THEN registered with koffi.
        assert(src.contains("val onEventSafe: Int => Unit = (a0: Int) =>"))
        assert(src.contains("""kyo.ffi.internal.FfiGenErrors.reportCallbackFailed("kyo.example.Epoll", "epollAdd", "retained", t)"""))
        assert(src.contains(
            """val onEventH = KoffiFacade.register(onEventSafe, KoffiFacade.pointer(epollAdd_onEvent_proto))"""
        ))
        assert(src.contains(
            "guard.asInstanceOf[kyo.ffi.internal.JsGuard].unsafeRetainCleanup(() => KoffiFacade.unregister(onEventH))"
        ))
        assert(src.contains("facade.epollAdd(epfd, fd, onEventH)"))
        // Retained path: the guard owns unregistration, so no KoffiFacade.unregister in the method body.
        assert(!src.contains("KoffiFacade.unregister(onEventH)\n"))
    }

    "retained callback: companion emits proto + KoffiFn with guard-slot dropped and KoffiFacade.pointer at callback slot" in {
        val spec = mkTrait(
            "Epoll",
            "kyo_epoll",
            List(
                mkMethod(
                    "epollAdd",
                    "epoll_add",
                    List(
                        ParamSpec("guard", TypeRef.GuardT),
                        ParamSpec("epfd", TypeRef.IntT),
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("onEvent", TypeRef.FnPtrT(List(TypeRef.IntT), TypeRef.UnitT))
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    kind = CallbackKind.Retained
                )
            )
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains(
            """KoffiFacade.proto("epollAdd_onEvent_proto", "void", Seq[String]("int"))"""
        ))
        // Guard never crosses the FFI boundary; koffi arg list starts with the int params then the callback proto handle.
        assert(src.contains(
            """KoffiFn("epollAdd", "epoll_add", "int", Seq[js.Any]("int".asInstanceOf[js.Any], "int".asInstanceOf[js.Any], KoffiFacade.pointer(epollAdd_onEvent_proto)))"""
        ))
    }

    "transient callback: source parses under Scala 3" in {
        val spec = mkTrait(
            "SortBindings",
            "kyo_sort",
            List(
                mkMethod(
                    "qsort",
                    "qsort",
                    List(
                        ParamSpec("base", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("count", TypeRef.IntT),
                        ParamSpec("elemSize", TypeRef.IntT),
                        ParamSpec("cmp", TypeRef.FnPtrT(List(TypeRef.IntT, TypeRef.IntT), TypeRef.IntT))
                    ),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src        = JsEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    "retained callback: source parses under Scala 3" in {
        val spec = mkTrait(
            "Epoll",
            "kyo_epoll",
            List(
                mkMethod(
                    "epollAdd",
                    "epoll_add",
                    List(
                        ParamSpec("guard", TypeRef.GuardT),
                        ParamSpec("epfd", TypeRef.IntT),
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("onEvent", TypeRef.FnPtrT(List(TypeRef.IntT), TypeRef.UnitT))
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    kind = CallbackKind.Retained
                )
            )
        )
        val src        = JsEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -------------------------------------------------------------------------
    // Section 4: TcpBindings full fixture
    // -------------------------------------------------------------------------

    "TcpBindings fixture emits all four methods with expected shapes" in {
        val cr = StructSpec(
            "kyo.example.ConnectResult",
            "ConnectResult",
            List(StructField("fd", TypeRef.IntT), StructField("pending", TypeRef.IntT)),
            packed = false
        )
        val spec = mkTrait(
            "TcpBindings",
            "kyo_tcp",
            List(
                mkMethod(
                    "tcpConnect",
                    "tcp_connect",
                    List(ParamSpec("host", TypeRef.StringT), ParamSpec("port", TypeRef.IntT)),
                    ReturnShape.MultiValue(cr),
                    blocking = true
                ),
                mkMethod(
                    "tcpClose",
                    "tcp_close",
                    List(ParamSpec("fd", TypeRef.IntT)),
                    ReturnShape.Void
                ),
                mkMethod(
                    "tcpRead",
                    "tcp_read",
                    List(
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("maxLen", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                ),
                mkMethod(
                    "tcpWrite",
                    "tcp_write",
                    List(
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("len", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                )
            ),
            structs = List(cr)
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("final class TcpBindingsImpl extends TcpBindings:"))
        // Wildcard import, brings in `facade` plus any callback-proto handles the companion registered.
        assert(src.contains("import TcpBindingsImpl.*"))
        assert(src.contains("end TcpBindingsImpl"))

        // Every binding method takes a trailing `(using kyo.AllowUnsafe)`; the three @Ffi.blocking methods return
        // `kyo.Fiber.Unsafe[…, Any]`; tcpClose is non-blocking and returns a plain value.
        assert(src.contains(
            "def tcpConnect(host: String, port: Int)(using kyo.AllowUnsafe): kyo.Fiber.Unsafe[kyo.example.ConnectResult, Any] ="
        ))
        assert(src.contains("def tcpClose(fd: Int)(using kyo.AllowUnsafe): Unit ="))
        assert(src.contains("def tcpRead(fd: Int, buf: Buffer[Byte], maxLen: Int)(using kyo.AllowUnsafe): kyo.Fiber.Unsafe[Int, Any] ="))
        assert(src.contains("def tcpWrite(fd: Int, buf: Buffer[Byte], len: Int)(using kyo.AllowUnsafe): kyo.Fiber.Unsafe[Int, Any] ="))

        assert(src.contains(
            """KoffiFn("tcpConnect", "tcp_connect", "int", Seq[js.Any]("string".asInstanceOf[js.Any], "int".asInstanceOf[js.Any], "int*".asInstanceOf[js.Any]))"""
        ))
        assert(src.contains("""KoffiFn("tcpClose", "tcp_close", "void", Seq[js.Any]("int".asInstanceOf[js.Any]))"""))
        assert(src.contains(
            """KoffiFn("tcpRead", "tcp_read", "int", Seq[js.Any]("int".asInstanceOf[js.Any], "void*".asInstanceOf[js.Any], "int".asInstanceOf[js.Any]))"""
        ))
        assert(src.contains(
            """KoffiFn("tcpWrite", "tcp_write", "int", Seq[js.Any]("int".asInstanceOf[js.Any], "void*".asInstanceOf[js.Any], "int".asInstanceOf[js.Any]))"""
        ))
    }

    // -------------------------------------------------------------------------
    // Section 5: Scala-parser syntactic validation
    // -------------------------------------------------------------------------

    "emitted source parses under the Scala 3 parser (smoke)" in {
        val cr = StructSpec(
            "kyo.example.ConnectResult",
            "ConnectResult",
            List(StructField("fd", TypeRef.IntT), StructField("pending", TypeRef.IntT)),
            packed = false
        )
        val spec = mkTrait(
            "TcpBindings",
            "kyo_tcp",
            List(
                mkMethod(
                    "tcpConnect",
                    "tcp_connect",
                    List(ParamSpec("host", TypeRef.StringT), ParamSpec("port", TypeRef.IntT)),
                    ReturnShape.MultiValue(cr),
                    blocking = true
                ),
                mkMethod(
                    "tcpClose",
                    "tcp_close",
                    List(ParamSpec("fd", TypeRef.IntT)),
                    ReturnShape.Void
                ),
                mkMethod(
                    "tcpRead",
                    "tcp_read",
                    List(
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("maxLen", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                )
            ),
            structs = List(cr)
        )
        val src        = JsEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -------------------------------------------------------------------------
    // Section 6: Long ↔ js.BigInt marshalling
    // -------------------------------------------------------------------------

    "Long param is marshalled through js.BigInt(param.toString)" in {
        val spec = mkTrait(
            "Bignum",
            "kyo_bignum",
            List(
                mkMethod(
                    "add64",
                    "add_i64",
                    List(ParamSpec("a", TypeRef.LongT), ParamSpec("b", TypeRef.LongT)),
                    ReturnShape.Primitive(TypeRef.LongT)
                )
            )
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("def add64(a: Long, b: Long)(using kyo.AllowUnsafe): Long ="))
        assert(src.contains("facade.add64(js.BigInt(a.toString), js.BigInt(b.toString))"))
    }

    "Long return is marshalled through .asInstanceOf[js.BigInt].toString.toLong" in {
        val spec = mkTrait(
            "Bignum",
            "kyo_bignum",
            List(
                mkMethod(
                    "now",
                    "now_ms",
                    Nil,
                    ReturnShape.Primitive(TypeRef.LongT)
                )
            )
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("val retVal = facade.now().asInstanceOf[js.BigInt].toString.toLong"))
    }

    "Long out-param uses KoffiFacade.outLong() and decodes via js.BigInt" in {
        val sSpec = StructSpec(
            "kyo.example.TimePair",
            "TimePair",
            List(StructField("sec", TypeRef.IntT), StructField("nanos", TypeRef.LongT)),
            packed = false
        )
        val spec = mkTrait(
            "Time",
            "kyo_time",
            List(
                mkMethod(
                    "gettime",
                    "get_time",
                    Nil,
                    ReturnShape.MultiValue(sSpec)
                )
            ),
            structs = List(sSpec)
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("val nanosOut = KoffiFacade.outLong()"))
        assert(src.contains("nanosOut.read().asInstanceOf[js.BigInt].toString.toLong"))
        assert(src.contains("""KoffiFn("gettime", "get_time", "int", Seq[js.Any]("int64*".asInstanceOf[js.Any]))"""))
    }

    "Long struct-return field is decoded via js.BigInt.toString.toLong" in {
        val sSpec = StructSpec(
            "kyo.example.Stamp",
            "Stamp",
            List(StructField("tag", TypeRef.IntT), StructField("ticks", TypeRef.LongT)),
            packed = false
        )
        val spec = mkTrait(
            "Clock",
            "kyo_clock",
            List(
                mkMethod(
                    "stamp",
                    "make_stamp",
                    Nil,
                    ReturnShape.Struct(sSpec)
                )
            ),
            structs = List(sSpec)
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("""result.selectDynamic("ticks").asInstanceOf[js.BigInt].toString.toLong"""))
    }

    "Long struct-param field is written through js.BigInt(f.toString)" in {
        val sSpec = StructSpec(
            "kyo.example.StampIn",
            "StampIn",
            List(StructField("tag", TypeRef.IntT), StructField("ticks", TypeRef.LongT)),
            packed = false
        )
        val spec = mkTrait(
            "Clock",
            "kyo_clock",
            List(
                mkMethod(
                    "consume",
                    "consume_stamp",
                    List(ParamSpec("s", TypeRef.StructT(sSpec.fqcn))),
                    ReturnShape.Void
                )
            ),
            structs = List(sSpec)
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("""js.BigInt(s.ticks.toString).asInstanceOf[js.Any]"""))
    }

    "emitted Long-heavy source parses under the Scala 3 parser" in {
        val sSpec = StructSpec(
            "kyo.example.TimePair",
            "TimePair",
            List(StructField("sec", TypeRef.IntT), StructField("nanos", TypeRef.LongT)),
            packed = false
        )
        val spec = mkTrait(
            "Time",
            "kyo_time",
            List(
                mkMethod(
                    "add64",
                    "add_i64",
                    List(ParamSpec("a", TypeRef.LongT), ParamSpec("b", TypeRef.LongT)),
                    ReturnShape.Primitive(TypeRef.LongT)
                ),
                mkMethod(
                    "gettime",
                    "get_time",
                    Nil,
                    ReturnShape.MultiValue(sSpec)
                )
            ),
            structs = List(sSpec)
        )
        val src        = JsEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -------------------------------------------------------------------------
    // Section 7: struct registration, nested structs, @packed via koffi.pack,
    //            pointer + String fields in return-position structs.
    // -------------------------------------------------------------------------

    "non-packed struct is registered via KoffiFacade.struct with field descriptor literal" in {
        val ts = StructSpec(
            "kyo.example.Timespec",
            "Timespec",
            List(StructField("sec", TypeRef.LongT), StructField("nsec", TypeRef.LongT)),
            packed = false
        )
        val spec = mkTrait(
            "Time",
            "kyo_time",
            List(mkMethod(
                "sleep",
                "sleep_ts",
                List(ParamSpec("ts", TypeRef.StructT(ts.fqcn))),
                ReturnShape.Primitive(TypeRef.IntT)
            )),
            structs = List(ts)
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains(
            """KoffiFacade.struct("Timespec", js.Dynamic.literal("sec" -> "int64".asInstanceOf[js.Any], "nsec" -> "int64".asInstanceOf[js.Any]))"""
        ))
        // koffi type for the struct parameter is the simpleName (matching the registered name).
        // Struct param is marshalled as a POINTER ("Timespec*") to mirror the JVM emitter's
        // ADDRESS convention, see comment in JsEmitter.emitKoffiFn for the rationale.
        assert(src.contains("""KoffiFn("sleep", "sleep_ts", "int", Seq[js.Any]("Timespec*".asInstanceOf[js.Any]))"""))
    }

    "packed struct is registered via KoffiFacade.pack (not .struct)" in {
        val ps = StructSpec(
            "kyo.example.Wire",
            "Wire",
            List(StructField("flag", TypeRef.ByteT), StructField("value", TypeRef.IntT)),
            packed = true
        )
        val spec = mkTrait(
            "Wires",
            "kyo_wire",
            List(mkMethod(
                "send",
                "send_wire",
                List(ParamSpec("w", TypeRef.StructT(ps.fqcn))),
                ReturnShape.Primitive(TypeRef.IntT)
            )),
            structs = List(ps)
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains(
            """KoffiFacade.pack("Wire", js.Dynamic.literal("flag" -> "int8".asInstanceOf[js.Any], "value" -> "int".asInstanceOf[js.Any]))"""
        ))
        assert(!src.contains("KoffiFacade.struct(\"Wire\""))
    }

    "nested struct field in param is marshalled as a nested js.Dynamic.literal" in {
        val inner = StructSpec(
            "kyo.example.Timeval",
            "Timeval",
            List(StructField("sec", TypeRef.LongT), StructField("usec", TypeRef.LongT)),
            packed = false
        )
        val outer = StructSpec(
            "kyo.example.Rusage",
            "Rusage",
            List(
                StructField("utime", TypeRef.StructT(inner.fqcn)),
                StructField("maxrss", TypeRef.LongT)
            ),
            packed = false
        )
        val spec = mkTrait(
            "Rusages",
            "kyo_rusage",
            List(mkMethod(
                "push",
                "push_rusage",
                List(ParamSpec("r", TypeRef.StructT(outer.fqcn))),
                ReturnShape.Primitive(TypeRef.IntT)
            )),
            structs = List(outer, inner)
        )
        val src = JsEmitter.emit(spec)
        // Outer literal contains nested literal for `utime`.
        assert(src.contains("""js.Dynamic.literal("utime" -> js.Dynamic.literal("""))
        assert(src.contains("""r.utime.sec.toString"""))
        assert(src.contains("""r.utime.usec.toString"""))
    }

    "nested struct field in return is read via recursive selectDynamic" in {
        val inner = StructSpec(
            "kyo.example.Timeval",
            "Timeval",
            List(StructField("sec", TypeRef.LongT), StructField("usec", TypeRef.LongT)),
            packed = false
        )
        val outer = StructSpec(
            "kyo.example.Rusage",
            "Rusage",
            List(
                StructField("utime", TypeRef.StructT(inner.fqcn)),
                StructField("maxrss", TypeRef.LongT)
            ),
            packed = false
        )
        val spec = mkTrait(
            "Rusages",
            "kyo_rusage",
            List(mkMethod(
                "current",
                "get_rusage",
                Nil,
                ReturnShape.Struct(outer)
            )),
            structs = List(outer, inner)
        )
        val src = JsEmitter.emit(spec)
        // Nested selectDynamic on the asInstanceOf[js.Dynamic] cast.
        assert(src.contains("""result.selectDynamic("utime").asInstanceOf[js.Dynamic].selectDynamic("sec")"""))
        assert(src.contains("kyo.example.Rusage(kyo.example.Timeval("))
    }

    "Buffer[A] field in return-position struct is wrapped as borrowed Buffer with inferred sibling size" in {
        val iov = StructSpec(
            "kyo.example.IoVec",
            "IoVec",
            List(StructField("base", TypeRef.BufferT(TypeRef.ByteT)), StructField("len", TypeRef.LongT)),
            packed = false
        )
        val spec = mkTrait(
            "Io",
            "kyo_io",
            List(mkMethod(
                "slice",
                "io_slice",
                List(ParamSpec("fd", TypeRef.IntT)),
                ReturnShape.Struct(iov)
            )),
            structs = List(iov)
        )
        val src = JsEmitter.emit(spec)
        // Size is read from the sole Int/Long sibling `len` (Long → js.BigInt → Long → Int).
        assert(src.contains(
            """Buffer.Unsafe.wrapBorrowed[Byte](result.selectDynamic("base").asInstanceOf[Uint8Array], result.selectDynamic("len").asInstanceOf[js.BigInt].toString.toLong.toInt)"""
        ))
        assert(!src.contains("Int.MaxValue"))
        assert(src.contains("kyo.example.IoVec("))
    }

    "String field in return-position struct is decoded via asInstanceOf[String]" in {
        val us = StructSpec(
            "kyo.example.User",
            "User",
            List(StructField("id", TypeRef.IntT), StructField("name", TypeRef.StringT)),
            packed = false
        )
        val spec = mkTrait(
            "Users",
            "kyo_users",
            List(mkMethod(
                "lookup",
                "user_lookup",
                List(ParamSpec("id", TypeRef.IntT)),
                ReturnShape.Struct(us)
            )),
            structs = List(us)
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("""result.selectDynamic("name").asInstanceOf[String]"""))
        assert(src.contains("kyo.example.User("))
    }

    "by-value struct return uses the out-pointer-FIRST ABI: struct out-buffer is allocated, passed FIRST, koffi return is void" in {
        val pt = StructSpec(
            "kyo.example.Point",
            "Point",
            List(StructField("x", TypeRef.IntT), StructField("y", TypeRef.IntT)),
            packed = false
        )
        val spec = mkTrait(
            "Geo",
            "kyo_geo",
            List(mkMethod(
                "makePoint",
                "make_point",
                List(ParamSpec("seed", TypeRef.IntT)),
                ReturnShape.Struct(pt)
            )),
            structs = List(pt)
        )
        val src = JsEmitter.emit(spec)
        // A struct out-buffer is allocated from the koffi-registered struct name and passed FIRST.
        assert(src.contains("""val __kyoStructOut$ = KoffiFacade.outStruct("Point")"""))
        assert(src.contains("facade.makePoint(__kyoStructOut$.buf, seed)"))
        // The filled buffer is decoded via the shared struct-decode-from-bytes path (NOT koffi's native object decode).
        assert(src.contains("""val result = __kyoStructOut$.read()"""))
        // The koffi descriptor gains a leading struct out-pointer and a void return.
        assert(src.contains(
            """KoffiFn("makePoint", "make_point", "void", Seq[js.Any]("Point*".asInstanceOf[js.Any], "int".asInstanceOf[js.Any]))"""
        ))
    }

    "emitted source for packed + nested + return-struct parses under Scala 3" in {
        val inner = StructSpec(
            "kyo.example.Timeval",
            "Timeval",
            List(StructField("sec", TypeRef.LongT), StructField("usec", TypeRef.LongT)),
            packed = false
        )
        val outer = StructSpec(
            "kyo.example.Rusage",
            "Rusage",
            List(
                StructField("utime", TypeRef.StructT(inner.fqcn)),
                StructField("maxrss", TypeRef.LongT)
            ),
            packed = false
        )
        val packed = StructSpec(
            "kyo.example.Wire",
            "Wire",
            List(StructField("flag", TypeRef.ByteT), StructField("value", TypeRef.IntT)),
            packed = true
        )
        val spec = mkTrait(
            "Mix",
            "kyo_mix",
            List(
                mkMethod(
                    "push",
                    "push_ru",
                    List(ParamSpec("r", TypeRef.StructT(outer.fqcn))),
                    ReturnShape.Primitive(TypeRef.IntT)
                ),
                mkMethod(
                    "readRu",
                    "read_ru",
                    Nil,
                    ReturnShape.Struct(outer)
                ),
                mkMethod(
                    "sendW",
                    "send_w",
                    List(ParamSpec("w", TypeRef.StructT(packed.fqcn))),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            ),
            structs = List(outer, inner, packed)
        )
        val src        = JsEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -------------------------------------------------------------------------
    // Section: reserved-name backticking
    // -------------------------------------------------------------------------

    "Scala 3 keywords used as parameter names are backticked in the emitted method signature" in {
        val spec = mkTrait(
            "ResvJs",
            "kyo_resv",
            List(
                mkMethod(
                    "kw",
                    "kw",
                    List(
                        ParamSpec("then", TypeRef.IntT),
                        ParamSpec("given", TypeRef.IntT),
                        ParamSpec("using", TypeRef.IntT),
                        ParamSpec("export", TypeRef.IntT),
                        ParamSpec("opaque", TypeRef.IntT),
                        ParamSpec("extension", TypeRef.IntT),
                        ParamSpec("derives", TypeRef.IntT),
                        ParamSpec("enum", TypeRef.IntT),
                        ParamSpec("throws", TypeRef.IntT)
                    ),
                    ReturnShape.Void
                )
            )
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("`then`: Int"))
        assert(src.contains("`given`: Int"))
        assert(src.contains("`using`: Int"))
        assert(src.contains("`export`: Int"))
        assert(src.contains("`opaque`: Int"))
        assert(src.contains("`extension`: Int"))
        assert(src.contains("`derives`: Int"))
        assert(src.contains("`enum`: Int"))
        assert(src.contains("`throws`: Int"))
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -------------------------------------------------------------------------
    // Section: multi-value out-param call pattern
    // -------------------------------------------------------------------------

    "multi-value return wires up KoffiFacade.outInt/outLong/outPointer allocators per trailing field" in {
        val cr = StructSpec(
            "kyo.example.MV",
            "MV",
            List(
                StructField("code", TypeRef.IntT),   // head (C return)
                StructField("count", TypeRef.IntT),  // int → outInt
                StructField("len", TypeRef.LongT),   // long → outLong
                StructField("name", TypeRef.StringT) // pointer → outPointer
            ),
            packed = false
        )
        val spec = mkTrait(
            "MVFn",
            "kyo_mv",
            List(
                mkMethod("call", "mv_call", Nil, ReturnShape.MultiValue(cr))
            ),
            structs = List(cr)
        )
        val src = JsEmitter.emit(spec)
        // Allocators are emitted one per out-field via the outAllocator mapping.
        assert(src.contains("val countOut = KoffiFacade.outInt()"))
        assert(src.contains("val lenOut = KoffiFacade.outLong()"))
        assert(src.contains("val nameOut = KoffiFacade.outPointer()"))
        // Each cell's `.buf` is passed to facade.call(...) as the trailing out-pointer argument.
        assert(src.contains("facade.call(countOut.buf, lenOut.buf, nameOut.buf)"))
        // Each cell's `.read()` is decoded with the right per-field cast.
        assert(src.contains("countOut.read().asInstanceOf[Int]"))
        assert(src.contains("lenOut.read().asInstanceOf[js.BigInt].toString.toLong"))
        assert(src.contains("nameOut.read().asInstanceOf[String]"))
    }

    // -------------------------------------------------------------------------
    // Section: variadic function support
    // -------------------------------------------------------------------------

    "variadic method emits KoffiFn with `...` variadic marker and accepts args: Any*" in {
        val spec = mkTrait(
            "VariadicLib",
            "kyo_variadic",
            List(
                mkMethod(
                    "vsum",
                    "kyo_it_sum_varargs",
                    List(ParamSpec("count", TypeRef.IntT)),
                    ReturnShape.Primitive(TypeRef.IntT),
                    hasVarargs = true
                )
            )
        )
        val src = JsEmitter.emit(spec)
        // Generated signature accepts args: Any* and the binding tier's trailing `(using kyo.AllowUnsafe)`.
        assert(src.contains("def vsum(count: Int, args: Any*)(using kyo.AllowUnsafe): Int"))
        // KoffiFn registration carries the `...` marker as an arg-type entry so koffi treats the call as variadic.
        assert(src.contains(""""...""""))
        // Runtime dispatch helper routes Any values to the appropriate koffi type at call time.
        assert(src.contains("JsVariadicMarshaller"))
    }

    // -------------------------------------------------------------------------
    // Section: Handle[A] pointer support
    // -------------------------------------------------------------------------

    "emit pointer koffi type for Handle param" in {
        val spec = mkTrait(
            "OpaqueBindings",
            "kyo_opaque",
            List(
                mkMethod(
                    "readHandle",
                    "read_handle",
                    List(ParamSpec("h", TypeRef.HandleT("test.Handle"))),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            )
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("\"void*\""))
    }

    "emit Handle return with FfiNullPointer throw for bare Handle on JS" in {
        val spec = mkTrait(
            "OpaqueBindings",
            "kyo_opaque",
            List(
                mkMethod("createHandle", "create_handle", List(ParamSpec("v", TypeRef.IntT)), ReturnShape.HandleReturn("test.Handle"))
            )
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("Ffi.Handle.wrap"))
        assert(src.contains("FfiNullPointer"))
        assert(!src.contains("Ffi.Handle.nil"))
    }

    "emit Maybe Handle return with Absent/Present wrapping on JS" in {
        val spec = mkTrait(
            "OpaqueBindings",
            "kyo_opaque",
            List(
                mkMethod("nullHandle", "null_handle", Nil, ReturnShape.HandleReturn("test.Handle", nullable = true))
            )
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("kyo.Absent"))
        assert(src.contains("kyo.Present"))
        assert(src.contains("Ffi.Handle.wrap"))
        assert(src.contains("kyo.Maybe[Ffi.Handle[test.Handle]]"))
        assert(!src.contains("FfiNullPointer"))
    }

    // -------------------------------------------------------------------------
    // Section: Enum support
    // -------------------------------------------------------------------------

    "emit int koffi type for enum param" in {
        val spec = mkTrait(
            "EnumTest",
            "enum_test",
            List(
                mkMethod(
                    "setColor",
                    "set_color",
                    List(ParamSpec("c", TypeRef.EnumT("kyo.example.Color"))),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            ),
            enums = List(EnumSpec("kyo.example.Color", "Color"))
        )
        val src = JsEmitter.emit(spec)
        // KoffiFn should declare "int" for the enum arg.
        assert(src.contains("\"int\""))
        // Marshalling should extract .value.
        assert(src.contains("c.value"))
    }

    "emit fromInt for enum return" in {
        val spec = mkTrait(
            "EnumTest",
            "enum_test",
            List(
                mkMethod(
                    "getColor",
                    "get_color",
                    List(ParamSpec("index", TypeRef.IntT)),
                    ReturnShape.EnumReturn("kyo.example.Color")
                )
            ),
            enums = List(EnumSpec("kyo.example.Color", "Color"))
        )
        val src = JsEmitter.emit(spec)
        assert(src.contains("kyo.example.Color.fromInt("))
    }

    // -------------------------------------------------------------------------
    // Section: Outcome errno capture
    // -------------------------------------------------------------------------

    "Outcome from Int return emits KoffiFacade.errno and Ffi.Outcome packing" in {
        val m = mkMethod(
            "riskyOp",
            "risky_op",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT),
            withError = true
        )
        val spec = mkTrait("ErrnoTest", "errno_test", List(m))
        val src  = JsEmitter.emit(spec)
        assert(src.contains("KoffiFacade.errno()"))
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("Ffi.Outcome"))
    }

    "Outcome from Long return emits KoffiFacade.errno and Ffi.Outcome packing" in {
        val m = mkMethod(
            "riskyLong",
            "risky_long",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.LongT),
            withError = true
        )
        val spec = mkTrait("ErrnoTestLong", "errno_test_long", List(m))
        val src  = JsEmitter.emit(spec)
        assert(src.contains("KoffiFacade.errno()"))
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("Ffi.Outcome"))
    }

    "Outcome from Double return emits KoffiFacade.errno and Ffi.Outcome packing" in {
        val m = mkMethod(
            "riskyDouble",
            "risky_double",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.DoubleT),
            withError = true
        )
        val spec = mkTrait("ErrnoTestDouble", "errno_test_double", List(m))
        val src  = JsEmitter.emit(spec)
        assert(src.contains("KoffiFacade.errno()"))
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("Ffi.Outcome"))
    }

    "Outcome from Boolean return emits KoffiFacade.errno and Ffi.Outcome packing" in {
        val m = mkMethod(
            "riskyBool",
            "risky_bool",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.BooleanT),
            withError = true
        )
        val spec = mkTrait("ErrnoTestBool", "errno_test_bool", List(m))
        val src  = JsEmitter.emit(spec)
        assert(src.contains("KoffiFacade.errno()"))
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("Ffi.Outcome"))
    }

    "Outcome from void return emits KoffiFacade.errno and Ffi.Outcome packing" in {
        val m = mkMethod(
            "riskyVoid",
            "risky_void",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Void,
            withError = true
        )
        val spec = mkTrait("ErrnoTestVoid", "errno_test_void", List(m))
        val src  = JsEmitter.emit(spec)
        assert(src.contains("KoffiFacade.errno()"))
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("Ffi.Outcome"))
    }

    "plain Int return does NOT emit Outcome or KoffiFacade.errno" in {
        val m = mkMethod(
            "safeOp",
            "safe_op",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT)
        )
        val spec = mkTrait("PlainTest", "plain_test", List(m))
        val src  = JsEmitter.emit(spec)
        assert(!src.contains("Ffi.Outcome.fromValueErrno("))
        assert(!src.contains("__errno"))
        assert(!src.contains("Ffi.Outcome"))
        assert(!src.contains("KoffiFacade.errno()"))
    }

    "plain void return does NOT emit Outcome or KoffiFacade.errno" in {
        val m = mkMethod(
            "safeVoid",
            "safe_void",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Void
        )
        val spec = mkTrait("PlainVoidTest", "plain_void_test", List(m))
        val src  = JsEmitter.emit(spec)
        assert(!src.contains("Ffi.Outcome.fromValueErrno("))
        assert(!src.contains("__errno"))
        assert(!src.contains("Ffi.Outcome"))
        assert(!src.contains("KoffiFacade.errno()"))
    }

    "plain Handle return does NOT emit Outcome or KoffiFacade.errno" in {
        val m = mkMethod(
            "getHandle",
            "get_handle",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.HandleReturn("kyo.example.MyHandle")
        )
        val spec = mkTrait("PlainHandleTest", "plain_handle_test", List(m))
        val src  = JsEmitter.emit(spec)
        assert(!src.contains("Ffi.Outcome.fromValueErrno("))
        assert(!src.contains("__errno"))
        assert(!src.contains("Ffi.Outcome"))
        assert(!src.contains("KoffiFacade.errno()"))
    }

    "trait with both Outcome and plain methods emits errno only for Outcome method" in {
        val riskyM = mkMethod(
            "riskyOp",
            "risky_op",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT),
            withError = true
        )
        val safeM = mkMethod(
            "safeOp",
            "safe_op",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT)
        )
        val spec = mkTrait("MixedErrnoTest", "mixed_errno_test", List(riskyM, safeM))
        val src  = JsEmitter.emit(spec)
        assert(src.contains(": Ffi.Outcome[Int] ="))
        val safeDefLine = src.linesIterator.find(_.contains("def safeOp")).getOrElse(fail("safeOp def not found"))
        assert(!safeDefLine.contains("Outcome"))
        assert(safeDefLine.contains(": Int ="))
    }

    "Outcome with Handle return emits KoffiFacade.errno and Handle wrapping" in {
        val m = mkMethod(
            "riskyHandle",
            "risky_handle",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.HandleReturn("kyo.example.MyHandle"),
            withError = true
        )
        val spec = mkTrait("HandleErrnoTest", "handle_errno_test", List(m))
        val src  = JsEmitter.emit(spec)
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("KoffiFacade.errno()"))
        assert(src.contains("Ffi.Handle.wrap"))
    }

    "Outcome with BorrowedString return emits KoffiFacade.errno and Borrowed wrapping" in {
        val m = mkMethod(
            "riskyBorrowed",
            "risky_borrowed",
            List(ParamSpec("name", TypeRef.StringT)),
            ReturnShape.BorrowedString(4096),
            withError = true
        )
        val spec = mkTrait("BorrowedErrnoTest", "borrowed_errno_test", List(m))
        val src  = JsEmitter.emit(spec)
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("KoffiFacade.errno()"))
        assert(src.contains("Ffi.Borrowed.wrap"))
    }

    "trait with Handle and Outcome on different methods emits errno only for Outcome method" in {
        val handleM = mkMethod(
            "getHandle",
            "get_handle",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.HandleReturn("kyo.example.MyHandle")
        )
        val riskyM = mkMethod(
            "riskyOp",
            "risky_op",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT),
            withError = true
        )
        val spec = mkTrait("HandleMixedTest", "handle_mixed_test", List(handleM, riskyM))
        val src  = JsEmitter.emit(spec)
        assert(src.contains(": Ffi.Outcome[Int] ="))
        val handleDefLine = src.linesIterator.find(_.contains("def getHandle")).getOrElse(fail("getHandle def not found"))
        assert(!handleDefLine.contains("Outcome"))
    }

end JsEmitterTest
