package kyo.ffi.codegen.emitters

import EmitterFixtures.*
import kyo.ffi.codegen.model.*

class JvmEmitterTest extends kyo.test.Test[Any]:

    // -------------------------------------------------------------------------
    // Section 1: header + companion basics
    // -------------------------------------------------------------------------

    "emits an AUTO-GENERATED banner and package clause" in {
        val spec = mkTrait(
            "Simple",
            "simple",
            List(
                mkMethod("noop", "noop", Nil, ReturnShape.Void)
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.startsWith("// AUTO-GENERATED by kyo-ffi-codegen"))
        assert(src.contains("package kyo.example"))
        assert(src.contains("import java.lang.foreign.*"))
        assert(src.contains("import kyo.ffi.*"))
        assert(src.contains(
            "import kyo.ffi.internal.{AbiCheck, NativeLoader, Scratch, Layouts, StructAbiCheck, UpcallBridge}"
        ))
    }

    "companion loads the named library, calls AbiCheck.verify, and defines the capture Linker.Option" in {
        val spec = mkTrait(
            "Simple",
            "kyo_simple",
            List(
                // Non-blocking + Array → critOn emitted at companion scope.
                mkMethod("f", "f", List(ParamSpec("x", TypeRef.ArrayT(TypeRef.IntT))), ReturnShape.Primitive(TypeRef.IntT))
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("""AbiCheck.verify(1, "kyo.example.Simple")"""))
        assert(src.contains(""" NativeLoader.load("kyo_simple")"""))
        assert(src.contains("""Linker.Option.captureCallState("errno")"""))
        // critOff is JDK 22+ and is no longer emitted in the no-array path; critOn appears only when needed.
        assert(src.contains("Linker.Option.critical(true)"))
    }

    // -------------------------------------------------------------------------
    // Section 2: Linker.Option matrix (§4.6)
    // -------------------------------------------------------------------------

    "non-blocking + no array → capture only (critOff is JDK 22+, default downcall is equivalent on JDK 21)" in {
        val m = mkMethod("f", "f", List(ParamSpec("x", TypeRef.IntT)), ReturnShape.Primitive(TypeRef.IntT))
        assert(JvmEmitter.emitLinkerOptions(m) == "capture")
    }

    "non-blocking + array param → capture, critOn" in {
        val m = mkMethod(
            "f",
            "f",
            List(ParamSpec("a", TypeRef.ArrayT(TypeRef.ByteT)), ParamSpec("n", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT)
        )
        assert(JvmEmitter.emitLinkerOptions(m) == "capture, critOn")
    }

    "blocking + no array → capture only" in {
        val m = mkMethod(
            "f",
            "f",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT),
            blocking = true
        )
        assert(JvmEmitter.emitLinkerOptions(m) == "capture")
    }

    "blocking + array → capture only" in {
        val m = mkMethod(
            "f",
            "f",
            List(ParamSpec("a", TypeRef.ArrayT(TypeRef.ByteT)), ParamSpec("n", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT),
            blocking = true
        )
        assert(JvmEmitter.emitLinkerOptions(m) == "capture")
    }

    // -------------------------------------------------------------------------
    // Section 3: FunctionDescriptor emission
    // -------------------------------------------------------------------------

    "void-return uses FunctionDescriptor.ofVoid" in {
        val spec = mkTrait(
            "Simple",
            "simple",
            List(
                mkMethod("close", "tcp_close", List(ParamSpec("fd", TypeRef.IntT)), ReturnShape.Void)
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("FunctionDescriptor.ofVoid(JAVA_INT)"))
    }

    "multi-value return's FunctionDescriptor has ADDRESS trailing out-params" in {
        val cr = StructSpec(
            "kyo.example.ConnectResult",
            "ConnectResult",
            List(StructField("fd", TypeRef.IntT), StructField("pending", TypeRef.IntT)),
            packed = false
        )
        val spec = mkTrait(
            "Tcp",
            "kyo_tcp",
            List(mkMethod(
                "tcpConnect",
                "tcp_connect",
                List(ParamSpec("host", TypeRef.StringT), ParamSpec("port", TypeRef.IntT)),
                ReturnShape.MultiValue(cr),
                blocking = true
            )),
            structs = List(cr)
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, ADDRESS)"))
    }

    // -------------------------------------------------------------------------
    // Section 4: method body / marshalling
    // -------------------------------------------------------------------------

    "String param body calls __kyoScratch$.allocUtf8 and passes the segment" in {
        val spec = mkTrait(
            "Log",
            "kyo_log",
            List(
                mkMethod(
                    "log",
                    "log_line",
                    List(ParamSpec("msg", TypeRef.StringT)),
                    ReturnShape.Void
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        // The allocUtf8 call threads binding FQN + method name so the diagnostic in `FfiErrors.scratchSpilled`
        // names the origin when the oversized-spill log is enabled.
        assert(src.contains("""val msgSeg = __kyoScratch$.allocUtf8(msg, "kyo.example.Log", "log")"""))
        assert(src.contains("logMH.invokeExact(errnoSeg, msgSeg)"))
    }

    "Buffer param body casts .raw to MemorySegment" in {
        val spec = mkTrait(
            "Tcp",
            "kyo_tcp",
            List(
                mkMethod(
                    "tcpRead",
                    "tcp_read",
                    List(
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("maxLen", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        // `Buffer.Raw` unwrap routes through `FfiUnsafe.expect` with binding + method context so alien
        // `Buffer.Raw` implementations produce a diagnostic instead of a silent `ClassCastException`.
        assert(src.contains(
            """val bufSeg = kyo.ffi.internal.FfiUnsafe.expect[MemorySegment](buf.raw.asInstanceOf[AnyRef], classOf[MemorySegment], "MemorySegment on JVM", "kyo.example.Tcp", "tcpRead")"""
        ))
        assert(src.contains("tcpReadMH.invokeExact(errnoSeg, fd, bufSeg, maxLen)"))
    }

    "Array + blocking → copy loop into scratch" in {
        val spec = mkTrait(
            "Hash",
            "kyo_hash",
            List(
                mkMethod(
                    "digestBlocking",
                    "digest_blocking",
                    List(
                        ParamSpec("data", TypeRef.ArrayT(TypeRef.ByteT)),
                        ParamSpec("len", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("val dataBps = 1L"))
        // alloc takes binding FQN + method name for spill diagnostics.
        assert(src.contains(
            """val dataSeg = __kyoScratch$.alloc(data.length.toLong * dataBps, dataBps, "kyo.example.Hash", "digestBlocking")"""
        ))
        assert(src.contains("val dataRaw = dataSeg.asInstanceOf[Buffer.Raw]"))
        assert(src.contains("while dataI < data.length do"))
        assert(src.contains("Layouts.byteL.write(dataRaw"))
    }

    "Array + non-blocking → MemorySegment.ofArray" in {
        val spec = mkTrait(
            "Hash",
            "kyo_hash",
            List(
                mkMethod(
                    "digestFast",
                    "digest_fast",
                    List(
                        ParamSpec("data", TypeRef.ArrayT(TypeRef.ByteT)),
                        ParamSpec("len", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("val dataSeg = MemorySegment.ofArray(data)"))
        assert(src.contains("capture, critOn"))
    }

    "multi-value return allocates a single coalesced out-segment block and slices per field" in {
        val cr = StructSpec(
            "kyo.example.ConnectResult",
            "ConnectResult",
            List(StructField("fd", TypeRef.IntT), StructField("pending", TypeRef.IntT)),
            packed = false
        )
        val spec = mkTrait(
            "Tcp",
            "kyo_tcp",
            List(mkMethod(
                "tcpConnect",
                "tcp_connect",
                List(ParamSpec("host", TypeRef.StringT), ParamSpec("port", TypeRef.IntT)),
                ReturnShape.MultiValue(cr),
                blocking = true
            )),
            structs = List(cr)
        )
        val src = JvmEmitter.emit(spec)
        // Out-params are coalesced into a single scratch allocation. There is NO per-field
        // `val pendingOut = __kyoScratch$.alloc(...)`, the former per-field allocator is replaced by a
        // single `__kyoMultiOut$` block and per-field `asSlice` views anchored at a fixed offset.
        assert(!src.contains("""val pendingOut = __kyoScratch$.alloc"""))
        assert(src.contains("""val __kyoMultiOut$ = __kyoScratch$.alloc(4L, 4L, "kyo.example.Tcp", "tcpConnect")"""))
        assert(src.contains("""val pendingOut = __kyoMultiOut$.asSlice(0L, 4L)"""))
        assert(src.contains("kyo.example.ConnectResult(retVal, pendingOut.get(JAVA_INT, 0L))"))
    }

    "multi-value return with 5 trailing out-params uses exactly one __kyoScratch$.alloc for the out-param block" in {
        // 5 trailing fields = 6 total fields in the MultiValue case class; head is primitive-returned, remaining
        // 5 are out-pointer writes. The emitter coalesces them into a single block with per-field offset slices.
        val fiveOut = StructSpec(
            "kyo.example.FiveOut",
            "FiveOut",
            List(
                StructField("head", TypeRef.IntT),
                StructField("a", TypeRef.IntT),
                StructField("b", TypeRef.LongT),
                StructField("c", TypeRef.DoubleT),
                StructField("d", TypeRef.IntT),
                StructField("e", TypeRef.LongT)
            ),
            packed = false
        )
        val spec = mkTrait(
            "Five",
            "kyo_five",
            List(mkMethod(
                "call",
                "five_call",
                Nil,
                ReturnShape.MultiValue(fiveOut)
            )),
            structs = List(fiveOut)
        )
        val src = JvmEmitter.emit(spec)
        val allocSites =
            raw"__kyoScratch\$$\.alloc\b".r.findAllMatchIn(src).size
        // 1 for errnoSeg + 1 coalesced multi-out block = 2 total. The former 5-per-field count would be 6.
        assert(allocSites == 2)
        // Single coalesced block is allocated to hold 5 fields (4 + 8 + 8 + 4 + 8 = 32 bytes natural-aligned).
        assert(src.contains("""val __kyoMultiOut$ = __kyoScratch$.alloc("""))
        // Per-field slices anchored on the coalesced block at their natural-alignment offsets.
        assert(src.contains("""val aOut = __kyoMultiOut$.asSlice(0L, 4L)"""))
        // `b: Long` is 8-aligned → offset 8 (after 4-byte `a` + 4 bytes of padding).
        assert(src.contains("""val bOut = __kyoMultiOut$.asSlice(8L, 8L)"""))
        // `c: Double` is 8-aligned → offset 16.
        assert(src.contains("""val cOut = __kyoMultiOut$.asSlice(16L, 8L)"""))
        // `d: Int` → offset 24.
        assert(src.contains("""val dOut = __kyoMultiOut$.asSlice(24L, 4L)"""))
        // `e: Long` → offset 32 (after 4-byte `d` + 4 bytes of padding).
        assert(src.contains("""val eOut = __kyoMultiOut$.asSlice(32L, 8L)"""))
    }

    "packed struct-by-value uses byte-aligned offsets (no padding between fields)" in {
        val ps = StructSpec(
            "kyo.example.Packed",
            "Packed",
            List(StructField("flag", TypeRef.ByteT), StructField("value", TypeRef.IntT)),
            packed = true
        )
        val spec = mkTrait(
            "PackedTrait",
            "kyo_packed",
            List(mkMethod(
                "send",
                "send_packed",
                List(ParamSpec("p", TypeRef.StructT(ps.fqcn))),
                ReturnShape.Primitive(TypeRef.IntT)
            )),
            structs = List(ps)
        )
        val src = JvmEmitter.emit(spec)
        // Layout uses .withByteAlignment(1L) per field.
        assert(src.contains("JAVA_BYTE.withByteAlignment(1L)"))
        assert(src.contains("JAVA_INT.withByteAlignment(1L)"))
        // Byte field is at offset 0, Int field follows immediately at offset 1 (no padding).
        assert(src.contains("pSeg.set(JAVA_BYTE, 0L, p.flag)"))
        assert(src.contains("pSeg.set(JAVA_INT, 1L, p.value)"))
        // Sanity: should NOT pad to offset 4.
        assert(!src.contains("pSeg.set(JAVA_INT, 4L, p.value)"))
    }

    "non-packed struct-by-value uses natural alignment (padding inserted)" in {
        val us = StructSpec(
            "kyo.example.Unpacked",
            "Unpacked",
            List(StructField("flag", TypeRef.ByteT), StructField("value", TypeRef.IntT)),
            packed = false
        )
        val spec = mkTrait(
            "UnpackedTrait",
            "kyo_unpacked",
            List(mkMethod(
                "send",
                "send_unpacked",
                List(ParamSpec("u", TypeRef.StructT(us.fqcn))),
                ReturnShape.Primitive(TypeRef.IntT)
            )),
            structs = List(us)
        )
        val src = JvmEmitter.emit(spec)
        // Byte at 0, Int padded to offset 4.
        assert(src.contains("uSeg.set(JAVA_BYTE, 0L, u.flag)"))
        assert(src.contains("uSeg.set(JAVA_INT, 4L, u.value)"))
    }

    "nested-struct param with a String field emits a legal local identifier (not a dotted member selection)" in {
        // Regression for #1683: a struct param containing a nested struct that contains a String field made the
        // emitter build the scratch-temp name from the dotted access path (`contact.address`), producing
        // `val contact.address_city_cs = ...` which the parser reads as a member selection on `contact`.
        val address = StructSpec(
            "kyo.example.Address",
            "Address",
            List(StructField("zip", TypeRef.IntT), StructField("city", TypeRef.StringT)),
            packed = false
        )
        val contact = StructSpec(
            "kyo.example.Contact",
            "Contact",
            List(
                StructField("id", TypeRef.IntT),
                StructField("name", TypeRef.StringT),
                StructField("address", TypeRef.StructT(address.fqcn))
            ),
            packed = false
        )
        val spec = mkTrait(
            "ContactBindings",
            "contacts",
            List(mkMethod(
                "contactsRouteCode",
                "contacts_route_code",
                List(ParamSpec("contact", TypeRef.StructT(contact.fqcn))),
                ReturnShape.Primitive(TypeRef.IntT)
            )),
            structs = List(address, contact)
        )
        val src = JvmEmitter.emit(spec)
        // The temp for the nested String field uses underscores throughout, and the allocUtf8 still reads from the
        // real dotted access expression `contact.address.city`.
        assert(src.contains(
            """val contact_address_city_cs = __kyoScratch$.allocUtf8(contact.address.city, "kyo.example.ContactBindings", "contactsRouteCode")"""
        ))
        // The top-level String field keeps its existing flat name.
        assert(src.contains(
            """val contact_name_cs = __kyoScratch$.allocUtf8(contact.name, "kyo.example.ContactBindings", "contactsRouteCode")"""
        ))
        // The broken dotted local name must not appear.
        assert(!src.contains("val contact.address_city_cs"))
        // And the whole thing parses.
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    "struct-by-value param allocates scratch and writes each field" in {
        val ts = StructSpec(
            "kyo.example.Timespec",
            "Timespec",
            List(StructField("sec", TypeRef.LongT), StructField("nsec", TypeRef.LongT)),
            packed = false
        )
        val spec = mkTrait(
            "Time",
            "kyo_time",
            List(mkMethod(
                "sleep",
                "sleep_ts",
                List(ParamSpec("ts", TypeRef.StructT(ts.fqcn))),
                ReturnShape.Primitive(TypeRef.IntT)
            )),
            structs = List(ts)
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains(
            """val tsSeg = __kyoScratch$.alloc(timespecLayout.byteSize(), timespecLayout.byteAlignment(), "kyo.example.Time", "sleep")"""
        ))
        assert(src.contains("tsSeg.set(JAVA_LONG, 0L, ts.sec)"))
        assert(src.contains("tsSeg.set(JAVA_LONG, 8L, ts.nsec)"))
    }

    "small (16-byte) simple-primitive struct uses the default field-by-field write path, NOT writeBulk" in {
        val small = StructSpec(
            "kyo.example.Small",
            "Small",
            // 16 bytes: Long + Long, under the default 128 B threshold.
            List(StructField("a", TypeRef.LongT), StructField("b", TypeRef.LongT)),
            packed = false
        )
        val spec = mkTrait(
            "SmallStructTrait",
            "kyo_small",
            List(mkMethod(
                "take",
                "take_small",
                List(ParamSpec("s", TypeRef.StructT(small.fqcn))),
                ReturnShape.Primitive(TypeRef.IntT)
            )),
            structs = List(small)
        )
        val src = JvmEmitter.emit(spec)
        // The bulk-write marker + helper invocation must NOT appear for small structs.
        assert(!src.contains("writeBulk"))
        // The standard field-by-field writes remain.
        assert(src.contains("sSeg.set(JAVA_LONG, 0L, s.a)"))
        assert(src.contains("sSeg.set(JAVA_LONG, 8L, s.b)"))
    }

    "large (256-byte) simple-primitive struct emits the writeBulk marker path" in {
        // 256 bytes = 32 Long fields (8 bytes each). All primitives, no nested / String / Buffer fields,
        // so the struct qualifies for the bulk-write path. The default threshold is 128 bytes.
        val fields = (1 to 32).map(i => StructField(s"f$i", TypeRef.LongT)).toList
        val big = StructSpec(
            "kyo.example.Big",
            "Big",
            fields,
            packed = false
        )
        val spec = mkTrait(
            "BigStructTrait",
            "kyo_big",
            List(mkMethod(
                "take",
                "take_big",
                List(ParamSpec("b", TypeRef.StructT(big.fqcn))),
                ReturnShape.Primitive(TypeRef.IntT)
            )),
            structs = List(big)
        )
        val src = JvmEmitter.emit(spec)
        // The emitter annotates the bulk-write path with a marker comment naming the struct's FQN and byte
        // size so codegen tests and human readers can spot the path selection. The marker is stable across
        // regen so snapshots don't churn.
        assert(src.contains("// __kyoStructBulkWrite$: kyo.example.Big (256 bytes)"))
        // Field writes still happen, the bulk path is a marker + predictable field sequence, not a
        // behavioural change. All 32 fields must still be written to the scratch segment.
        assert(src.contains("bSeg.set(JAVA_LONG, 0L, b.f1)"))
        assert(src.contains("bSeg.set(JAVA_LONG, 248L, b.f32)"))
    }

    "struct with a String field is NOT eligible for writeBulk even when above the threshold" in {
        // Even at ≥128 bytes, a struct containing non-primitive fields (here a trailing String / C char*)
        // falls back to the field-by-field path, the bulk pattern only applies to strictly primitive
        // layouts because pointer fields require per-field allocUtf8 setup.
        val mixedFields = (1 to 16).map(i => StructField(s"f$i", TypeRef.LongT)).toList :+
            StructField("name", TypeRef.StringT) // 128 + 8 = 136 bytes
        val mixed = StructSpec(
            "kyo.example.Mixed",
            "Mixed",
            mixedFields,
            packed = false
        )
        val spec = mkTrait(
            "MixedStructTrait",
            "kyo_mixed",
            List(mkMethod(
                "take",
                "take_mixed",
                List(ParamSpec("m", TypeRef.StructT(mixed.fqcn))),
                ReturnShape.Primitive(TypeRef.IntT)
            )),
            structs = List(mixed)
        )
        val src = JvmEmitter.emit(spec)
        assert(!src.contains("writeBulk"))
    }

    "Unit-return method emits invokeExact without asInstanceOf" in {
        val spec = mkTrait(
            "Simple",
            "simple",
            List(
                mkMethod("close", "tcp_close", List(ParamSpec("fd", TypeRef.IntT)), ReturnShape.Void)
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("closeMH.invokeExact(errnoSeg, fd)"))
        assert(!src.contains(".asInstanceOf[Unit]"))
    }

    "method-handle block references lib.find and the computed descriptor" in {
        val spec = mkTrait(
            "Simple",
            "simple",
            List(
                mkMethod(
                    "add",
                    "add_ints",
                    List(ParamSpec("a", TypeRef.IntT), ParamSpec("b", TypeRef.IntT)),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("""lib.find("add_ints").orElseThrow()"""))
        assert(src.contains("FunctionDescriptor.of(JAVA_INT, JAVA_INT, JAVA_INT)"))
        assert(src.contains("private val addMH: MethodHandle = linker.downcallHandle("))
    }

    // -------------------------------------------------------------------------
    // Section 5: callback stubs (JVM implementation)
    // -------------------------------------------------------------------------

    "transient callback → per-call Arena.ofConfined closed in finally" in {
        val spec = mkTrait(
            "Sort",
            "kyo_sort",
            List(
                mkMethod(
                    "qsort",
                    "qsort",
                    List(
                        ParamSpec("base", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("count", TypeRef.IntT),
                        ParamSpec("elemSize", TypeRef.IntT),
                        ParamSpec("cmp", TypeRef.FnPtrT(List(TypeRef.IntT, TypeRef.IntT), TypeRef.IntT))
                    ),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        // Per-call Arena allocation.
        assert(src.contains("val cbArena = Arena.ofConfined().nn"))
        // II_I shape (the qsort comparator) is in the JVM-safe catalog so the emitter routes
        // it to the specialised bridge that skips the generic `MethodHandle.asType` boxing adapter.
        assert(src.contains("UpcallBridge.stubShape_II_I(cmp,"))
        assert(src.contains("cbQsortCmpDesc"))
        // cbArena.close() in finally after scratch reset.
        assert(src.contains("cbArena.close()"))
        assert(src.contains("__kyoScratch$.reset(__kyoMark$)"))
        assert(src.contains("qsortMH.invokeExact(errnoSeg, baseSeg, count, elemSize, cmpStub)"))
        // No TransientStubCache references.
        assert(!src.contains("TransientStubCache"))
        assert(!src.contains("__cbSlot_"))
    }

    "retained callback → cbArena derived from JvmGuard.unsafeArena; finally keeps single-line reset" in {
        val spec = mkTrait(
            "Epoll",
            "kyo_epoll",
            List(
                mkMethod(
                    "epollAdd",
                    "epoll_add",
                    List(
                        ParamSpec("guard", TypeRef.GuardT),
                        ParamSpec("epfd", TypeRef.IntT),
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("onEvent", TypeRef.FnPtrT(List(TypeRef.IntT), TypeRef.UnitT))
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    kind = CallbackKind.Retained
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("val cbArena = guard.asInstanceOf[kyo.ffi.internal.JvmGuard].unsafeArena"))
        // I_U shape → specialised bridge, no generic `asType` boxing chain.
        assert(src.contains("UpcallBridge.stubShape_I_U(onEvent,"))
        assert(src.contains("cbEpollAddOnEventDesc"))
        // The guard does NOT appear in the invokeExact args, only in the arena lookup.
        assert(src.contains("epollAddMH.invokeExact(errnoSeg, epfd, fd, onEventStub)"))
        // No Arena.ofConfined for retained methods; the guard owns the arena.
        assert(!src.contains("Arena.ofConfined"))
        // Finally remains the single-line form (no cbArena.close(), the guard owns lifetime).
        assert(src.contains("finally __kyoScratch$.reset(__kyoMark$)"))
    }

    "transient callback companion emits MethodHandle with ADDRESS for the function-pointer param" in {
        val spec = mkTrait(
            "Sort",
            "kyo_sort",
            List(
                mkMethod(
                    "qsort",
                    "qsort",
                    List(
                        ParamSpec("base", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("count", TypeRef.IntT),
                        ParamSpec("elemSize", TypeRef.IntT),
                        ParamSpec("cmp", TypeRef.FnPtrT(List(TypeRef.IntT, TypeRef.IntT), TypeRef.IntT))
                    ),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("private val qsortMH: MethodHandle = linker.downcallHandle("))
        // The C-level descriptor is (ptr, int, int, fn*)->void, the callback slot is an ADDRESS.
        assert(src.contains("FunctionDescriptor.ofVoid(ADDRESS, JAVA_INT, JAVA_INT, ADDRESS)"))
    }

    "transient callback companion emits FunctionDescriptor val for each callback param" in {
        val spec = mkTrait(
            "Sort",
            "kyo_sort",
            List(
                mkMethod(
                    "qsort",
                    "qsort",
                    List(
                        ParamSpec("base", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("count", TypeRef.IntT),
                        ParamSpec("elemSize", TypeRef.IntT),
                        ParamSpec("cmp", TypeRef.FnPtrT(List(TypeRef.IntT, TypeRef.IntT), TypeRef.IntT))
                    ),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("private val cbQsortCmpDesc: FunctionDescriptor = FunctionDescriptor.of(JAVA_INT, JAVA_INT, JAVA_INT)"))
    }

    "retained callback companion emits MethodHandle with ADDRESS for callback param and no Guard slot" in {
        val spec = mkTrait(
            "Epoll",
            "kyo_epoll",
            List(
                mkMethod(
                    "epollAdd",
                    "epoll_add",
                    List(
                        ParamSpec("guard", TypeRef.GuardT),
                        ParamSpec("epfd", TypeRef.IntT),
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("onEvent", TypeRef.FnPtrT(List(TypeRef.IntT), TypeRef.UnitT))
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    kind = CallbackKind.Retained
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("private val epollAddMH: MethodHandle = linker.downcallHandle("))
        // Descriptor: C-level signature is (int epfd, int fd, void* onEvent) -> int. Guard is NOT in the descriptor.
        assert(src.contains("FunctionDescriptor.of(JAVA_INT, JAVA_INT, JAVA_INT, ADDRESS)"))
        // Callback descriptor for onEvent: void(int).
        assert(src.contains("private val cbEpollAddOnEventDesc: FunctionDescriptor = FunctionDescriptor.ofVoid(JAVA_INT)"))
    }

    "transient callback passes binding/method/kind tag to UpcallBridge.stub" in {
        val spec = mkTrait(
            "Sort",
            "kyo_sort",
            List(
                mkMethod(
                    "qsort",
                    "qsort",
                    List(
                        ParamSpec("base", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("count", TypeRef.IntT),
                        ParamSpec("elemSize", TypeRef.IntT),
                        ParamSpec("cmp", TypeRef.FnPtrT(List(TypeRef.IntT, TypeRef.IntT), TypeRef.IntT))
                    ),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        // Transient stubs use the per-call `cbArena`.
        assert(src.contains("""UpcallBridge.stubShape_II_I(cmp, cbQsortCmpDesc, cbArena, "kyo.example.Sort", "qsort", "transient")"""))
    }

    "retained callback passes binding/method/kind=retained tag to UpcallBridge.stub" in {
        val spec = mkTrait(
            "Epoll",
            "kyo_epoll",
            List(
                mkMethod(
                    "epollAdd",
                    "epoll_add",
                    List(
                        ParamSpec("guard", TypeRef.GuardT),
                        ParamSpec("epfd", TypeRef.IntT),
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("onEvent", TypeRef.FnPtrT(List(TypeRef.IntT), TypeRef.UnitT))
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    kind = CallbackKind.Retained
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains(
            """UpcallBridge.stubShape_I_U(onEvent, cbEpollAddOnEventDesc, cbArena, "kyo.example.Epoll", "epollAdd", "retained")"""
        ))
    }

    "transient callback emitted source parses under the Scala 3 parser" in {
        val spec = mkTrait(
            "Sort",
            "kyo_sort",
            List(
                mkMethod(
                    "qsort",
                    "qsort",
                    List(
                        ParamSpec("base", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("count", TypeRef.IntT),
                        ParamSpec("elemSize", TypeRef.IntT),
                        ParamSpec("cmp", TypeRef.FnPtrT(List(TypeRef.IntT, TypeRef.IntT), TypeRef.IntT))
                    ),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src        = JvmEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -----------------------------------------------------------------
    // Specialised JVM upcall bridges for catalog shapes.
    // -----------------------------------------------------------------

    "JVM-safe catalog shapes dispatch to specialised UpcallBridge.stubShape_<SHAPE>" in {
        // Each of the 5 primitive-only JVM-safe shapes (V_U, I_U, I_I, II_I, JJ_I) maps to the matching
        // specialised bridge. A single binding with 5 methods lets one spec cover the full catalog.
        val spec = mkTrait(
            "Shapes",
            "kyo_shapes",
            List(
                mkMethod(
                    "callV",
                    "call_v",
                    List(ParamSpec("cb", TypeRef.FnPtrT(Nil, TypeRef.UnitT))),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                ),
                mkMethod(
                    "callIU",
                    "call_iu",
                    List(ParamSpec("cb", TypeRef.FnPtrT(List(TypeRef.IntT), TypeRef.UnitT))),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                ),
                mkMethod(
                    "callII",
                    "call_ii",
                    List(ParamSpec("cb", TypeRef.FnPtrT(List(TypeRef.IntT), TypeRef.IntT))),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                ),
                mkMethod(
                    "callIII",
                    "call_iii",
                    List(ParamSpec("cb", TypeRef.FnPtrT(List(TypeRef.IntT, TypeRef.IntT), TypeRef.IntT))),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                ),
                mkMethod(
                    "callJJI",
                    "call_jji",
                    List(ParamSpec("cb", TypeRef.FnPtrT(List(TypeRef.LongT, TypeRef.LongT), TypeRef.IntT))),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("UpcallBridge.stubShape_V_U(cb,"))
        assert(src.contains("UpcallBridge.stubShape_I_U(cb,"))
        assert(src.contains("UpcallBridge.stubShape_I_I(cb,"))
        assert(src.contains("UpcallBridge.stubShape_II_I(cb,"))
        assert(src.contains("UpcallBridge.stubShape_JJ_I(cb,"))
        // Generic stub path must NOT be emitted for these catalog shapes.
        assert(!src.contains("UpcallBridge.stub0(cb,"))
        assert(!src.contains("UpcallBridge.stub1(cb,"))
        assert(!src.contains("UpcallBridge.stub2(cb,"))
    }

    "non-catalog callback shape falls back to the generic UpcallBridge.stubN path" in {
        // `(Float, Double) => Boolean` is not in the Native-Callback catalog, so JVM emission falls through
        // to `UpcallBridge.stub2`. The generic path preserves correctness at a documented perf cost.
        val spec = mkTrait(
            "Odd",
            "kyo_odd",
            List(
                mkMethod(
                    "callOdd",
                    "call_odd",
                    List(ParamSpec("cb", TypeRef.FnPtrT(List(TypeRef.FloatT, TypeRef.DoubleT), TypeRef.BooleanT))),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("UpcallBridge.stub2(cb,"))
        assert(!src.contains("UpcallBridge.stubShape_"))
    }

    "new JVM-safe catalog shapes (J_J, J_U, D_D, II_U, JJ_J) dispatch to specialised bridges" in {
        val spec = mkTrait(
            "NewShapes",
            "kyo_newshapes",
            List(
                mkMethod(
                    "callJJ",
                    "call_jj",
                    List(ParamSpec("cb", TypeRef.FnPtrT(List(TypeRef.LongT), TypeRef.LongT))),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                ),
                mkMethod(
                    "callJU",
                    "call_ju",
                    List(ParamSpec("cb", TypeRef.FnPtrT(List(TypeRef.LongT), TypeRef.UnitT))),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                ),
                mkMethod(
                    "callDD",
                    "call_dd",
                    List(ParamSpec("cb", TypeRef.FnPtrT(List(TypeRef.DoubleT), TypeRef.DoubleT))),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                ),
                mkMethod(
                    "callIIU",
                    "call_iiu",
                    List(ParamSpec("cb", TypeRef.FnPtrT(List(TypeRef.IntT, TypeRef.IntT), TypeRef.UnitT))),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                ),
                mkMethod(
                    "callJJJ",
                    "call_jjj",
                    List(ParamSpec("cb", TypeRef.FnPtrT(List(TypeRef.LongT, TypeRef.LongT), TypeRef.LongT))),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("UpcallBridge.stubShape_J_J(cb,"))
        assert(src.contains("UpcallBridge.stubShape_J_U(cb,"))
        assert(src.contains("UpcallBridge.stubShape_D_D(cb,"))
        assert(src.contains("UpcallBridge.stubShape_II_U(cb,"))
        assert(src.contains("UpcallBridge.stubShape_JJ_J(cb,"))
        // Generic stub path must NOT be emitted for these catalog shapes.
        assert(!src.contains("UpcallBridge.stub1(cb,"))
        assert(!src.contains("UpcallBridge.stub2(cb,"))
    }

    "Buffer-typed pointer callbacks keep the generic stubN path on JVM" in {
        // The catalog's P_U shape matches on the codegen side, but Buffer[A] ≠ MemorySegment at the Scala type
        // level, so the JVM emitter intentionally excludes pointer-involving shapes from the specialised
        // dispatch. A Buffer-taking callback falls back to the generic stubN path unchanged.
        val spec = mkTrait(
            "BufCb",
            "kyo_bufcb",
            List(
                mkMethod(
                    "call",
                    "call",
                    List(ParamSpec("cb", TypeRef.FnPtrT(List(TypeRef.BufferT(TypeRef.ByteT)), TypeRef.UnitT))),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("UpcallBridge.stub1(cb,"))
        assert(!src.contains("UpcallBridge.stubShape_"))
    }

    "retained callback emitted source parses under the Scala 3 parser" in {
        val spec = mkTrait(
            "Epoll",
            "kyo_epoll",
            List(
                mkMethod(
                    "epollAdd",
                    "epoll_add",
                    List(
                        ParamSpec("guard", TypeRef.GuardT),
                        ParamSpec("epfd", TypeRef.IntT),
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("onEvent", TypeRef.FnPtrT(List(TypeRef.IntT), TypeRef.UnitT))
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    kind = CallbackKind.Retained
                )
            )
        )
        val src        = JvmEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -------------------------------------------------------------------------
    // Section 6: full TcpBindings fixture matches the shape of DESIGN §9.1
    // -------------------------------------------------------------------------

    "TcpBindings fixture emits all four methods with expected shapes" in {
        val cr = StructSpec(
            "kyo.example.ConnectResult",
            "ConnectResult",
            List(StructField("fd", TypeRef.IntT), StructField("pending", TypeRef.IntT)),
            packed = false
        )
        val spec = mkTrait(
            "TcpBindings",
            "kyo_tcp",
            List(
                mkMethod(
                    "tcpConnect",
                    "tcp_connect",
                    List(ParamSpec("host", TypeRef.StringT), ParamSpec("port", TypeRef.IntT)),
                    ReturnShape.MultiValue(cr),
                    blocking = true
                ),
                mkMethod(
                    "tcpClose",
                    "tcp_close",
                    List(ParamSpec("fd", TypeRef.IntT)),
                    ReturnShape.Void
                ),
                mkMethod(
                    "tcpRead",
                    "tcp_read",
                    List(
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("maxLen", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                ),
                mkMethod(
                    "tcpWrite",
                    "tcp_write",
                    List(
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("len", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                )
            ),
            structs = List(cr)
        )

        val src = JvmEmitter.emit(spec)

        // Impl class skeleton.
        assert(src.contains("final class TcpBindingsImpl extends TcpBindings:"))
        assert(src.contains("    import TcpBindingsImpl.*"))
        assert(src.contains("end TcpBindingsImpl"))

        // Each method appears in the impl. Every binding method takes a trailing `(using kyo.AllowUnsafe)`; the three
        // @Ffi.blocking methods return `kyo.Fiber.Unsafe[…, Any]`; tcpClose is non-blocking and returns a plain value.
        assert(src.contains(
            "def tcpConnect(host: String, port: Int)(using kyo.AllowUnsafe): kyo.Fiber.Unsafe[kyo.example.ConnectResult, Any] ="
        ))
        assert(src.contains("def tcpClose(fd: Int)(using kyo.AllowUnsafe): Unit ="))
        assert(src.contains("def tcpRead(fd: Int, buf: Buffer[Byte], maxLen: Int)(using kyo.AllowUnsafe): kyo.Fiber.Unsafe[Int, Any] ="))
        assert(src.contains("def tcpWrite(fd: Int, buf: Buffer[Byte], len: Int)(using kyo.AllowUnsafe): kyo.Fiber.Unsafe[Int, Any] ="))

        // Companion with MH bindings.
        assert(src.contains("private val tcpConnectMH: MethodHandle = linker.downcallHandle("))
        assert(src.contains("private val tcpCloseMH: MethodHandle = linker.downcallHandle("))
        assert(src.contains("private val tcpReadMH: MethodHandle = linker.downcallHandle("))
        assert(src.contains("private val tcpWriteMH: MethodHandle = linker.downcallHandle("))

        // tcpClose: not @Ffi.blocking, no Array → capture only (critOff dropped for JDK 21 compat).
        val closeMhBlock = extractMhBlock(src, "tcpClose")
        assert(closeMhBlock.contains("FunctionDescriptor.ofVoid(JAVA_INT)"))
        assert(closeMhBlock.contains("capture"))
        assert(!closeMhBlock.contains("critOff"))

        // tcpConnect: @Ffi.blocking, multi-value → capture only
        val connectBlock = extractMhBlock(src, "tcpConnect")
        assert(connectBlock.contains("capture"))
        assert(!connectBlock.contains("critOn"))
        assert(!connectBlock.contains("critOff"))
    }

    // -------------------------------------------------------------------------
    // Section 7: compile-time syntax validation via Scala 3 parser
    // -------------------------------------------------------------------------

    "emitted source parses under the Scala 3 parser (smoke)" in {
        val cr = StructSpec(
            "kyo.example.ConnectResult",
            "ConnectResult",
            List(StructField("fd", TypeRef.IntT), StructField("pending", TypeRef.IntT)),
            packed = false
        )
        val spec = mkTrait(
            "TcpBindings",
            "kyo_tcp",
            List(
                mkMethod(
                    "tcpConnect",
                    "tcp_connect",
                    List(ParamSpec("host", TypeRef.StringT), ParamSpec("port", TypeRef.IntT)),
                    ReturnShape.MultiValue(cr),
                    blocking = true
                ),
                mkMethod(
                    "tcpClose",
                    "tcp_close",
                    List(ParamSpec("fd", TypeRef.IntT)),
                    ReturnShape.Void
                )
            ),
            structs = List(cr)
        )
        val src        = JvmEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    "emitted source for an Array + blocking method parses" in {
        val spec = mkTrait(
            "Hash",
            "kyo_hash",
            List(
                mkMethod(
                    "digestBlocking",
                    "digest_blocking",
                    List(
                        ParamSpec("data", TypeRef.ArrayT(TypeRef.ByteT)),
                        ParamSpec("len", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                )
            )
        )
        val src        = JvmEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -------------------------------------------------------------------------
    // Section 8: pointer + String fields in return-position structs
    // -------------------------------------------------------------------------

    "String field in return-position struct is decoded via bounded Scratch.readCStringBounded" in {
        val us = StructSpec(
            "kyo.example.User",
            "User",
            List(StructField("id", TypeRef.IntT), StructField("name", TypeRef.StringT)),
            packed = false
        )
        val spec = mkTrait(
            "Users",
            "kyo_users",
            List(mkMethod(
                "lookup",
                "user_lookup",
                List(ParamSpec("id", TypeRef.IntT)),
                ReturnShape.Struct(us)
            )),
            structs = List(us)
        )
        val src = JvmEmitter.emit(spec)
        // Bounded reinterpret (Scratch.stringFieldMaxBytes, default 64 KiB, override via -Dkyo.ffi.stringFieldMaxBytes=).
        assert(src.contains("Scratch.readCStringBounded(out.get(ADDRESS, 8L).reinterpret(Scratch.stringFieldMaxBytes), 0L, " +
            """Scratch.stringFieldMaxBytes, "kyo.example.Users", "lookup", "name")"""))
        assert(!src.contains("Long.MaxValue"))
        assert(src.contains("kyo.example.User("))
    }

    "by-value struct return uses the out-pointer-FIRST ABI: out is passed first (after errnoSeg), descriptor returns void" in {
        val pt = StructSpec(
            "kyo.example.Point",
            "Point",
            List(StructField("x", TypeRef.IntT), StructField("y", TypeRef.IntT)),
            packed = false
        )
        val spec = mkTrait(
            "Geo",
            "kyo_geo",
            List(mkMethod(
                "makePoint",
                "make_point",
                List(ParamSpec("seed", TypeRef.IntT)),
                ReturnShape.Struct(pt)
            )),
            structs = List(pt)
        )
        val src = JvmEmitter.emit(spec)
        // errnoSeg, then the struct out-segment FIRST among the C params, then the user args. C returns void.
        assert(src.contains("val _: Unit = makePointMH.invokeExact(errnoSeg, out, seed)"))
        // The downcall descriptor is void-returning with the struct out-ADDRESS as the leading parameter.
        assert(src.contains("FunctionDescriptor.ofVoid(ADDRESS, JAVA_INT)"))
    }

    "Buffer[A] field in return-position struct is wrapped as borrowed Buffer with bounded reinterpret" in {
        val iovec = StructSpec(
            "kyo.example.IoVec",
            "IoVec",
            List(StructField("base", TypeRef.BufferT(TypeRef.ByteT)), StructField("len", TypeRef.LongT)),
            packed = false
        )
        val spec = mkTrait(
            "Io",
            "kyo_io",
            List(mkMethod(
                "slice",
                "io_slice",
                List(ParamSpec("fd", TypeRef.IntT)),
                ReturnShape.Struct(iovec)
            )),
            structs = List(iovec)
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("Buffer.Unsafe.wrapBorrowed[Byte]("))
        assert(src.contains("out.get(ADDRESS, 0L).reinterpret(Scratch.stringFieldMaxBytes)"))
        assert(!src.contains("Long.MaxValue"))
        assert(src.contains("kyo.example.IoVec("))
    }

    "return-position struct with String + Buffer fields parses under Scala 3" in {
        val mix = StructSpec(
            "kyo.example.Mix",
            "Mix",
            List(
                StructField("id", TypeRef.IntT),
                StructField("name", TypeRef.StringT),
                StructField("data", TypeRef.BufferT(TypeRef.ByteT))
            ),
            packed = false
        )
        val spec = mkTrait(
            "Mixes",
            "kyo_mix",
            List(mkMethod(
                "build",
                "build_mix",
                List(ParamSpec("id", TypeRef.IntT)),
                ReturnShape.Struct(mix)
            )),
            structs = List(mix)
        )
        val src        = JvmEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -------------------------------------------------------------------------
    // Section 9: JDK 22+ critical-API gate
    // -------------------------------------------------------------------------

    "non-blocking + Array companion emits a runtime hasCriticalApi reflective gate" in {
        val spec = mkTrait(
            "Hash",
            "kyo_hash",
            List(
                mkMethod(
                    "digest",
                    "digest",
                    List(ParamSpec("data", TypeRef.ArrayT(TypeRef.ByteT)), ParamSpec("len", TypeRef.IntT)),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        // Reflective probe of the JDK 22+ method must be present.
        assert(src.contains("private val hasCriticalApi: Boolean"))
        assert(src.contains("classOf[Linker.Option].getMethod(\"critical\", classOf[Boolean])"))
        assert(src.contains("catch case _: Throwable => false"))
        // critOn becomes Linker.Option | Null and is conditionally initialized.
        assert(src.contains("private val critOn: Linker.Option | Null"))
        assert(src.contains("if hasCriticalApi then Linker.Option.critical(true) else null"))
        // mkOpts helper filters nullable options before passing to downcallHandle.
        assert(src.contains("private def mkOpts(opts: Linker.Option | Null*): Array[Linker.Option]"))
        // The downcall handle for the array-bearing method splats the filtered options.
        val mh = extractMhBlock(src, "digest")
        assert(mh.contains("mkOpts(capture, critOn)*"))
    }

    "blocking + no-array methods retain the simple capture form (no mkOpts splat)" in {
        val spec = mkTrait(
            "Misc",
            "kyo_misc",
            List(
                mkMethod(
                    "noopBlocking",
                    "noop_blocking",
                    List(ParamSpec("x", TypeRef.IntT)),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        // No critical-API probing, no mkOpts.
        assert(!src.contains("hasCriticalApi"))
        assert(!src.contains("mkOpts("))
        val mh = extractMhBlock(src, "noopBlocking")
        assert(mh.contains("capture"))
        assert(!mh.contains("critOn"))
    }

    "emitted source with the JDK gate parses under the Scala 3 parser" in {
        val spec = mkTrait(
            "Gate",
            "kyo_gate",
            List(
                mkMethod(
                    "scan",
                    "scan",
                    List(ParamSpec("buf", TypeRef.ArrayT(TypeRef.ByteT)), ParamSpec("len", TypeRef.IntT)),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            )
        )
        val src        = JvmEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -------------------------------------------------------------------------
    // Section: Scratch / arena lifetime
    // -------------------------------------------------------------------------

    "method body acquires per-binding scratch via Scratch.currentFor with the trait FQN" in {
        val spec = mkTrait(
            "FqnScratch",
            "fqn",
            List(mkMethod("noop", "noop", Nil, ReturnShape.Void))
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("""val __kyoScratch$ = Scratch.currentFor("kyo.example.FqnScratch", Scratch.configuredSize)"""))
    }

    "Ffi.Config.scratchSize = Some(n) emits the literal size into Scratch.currentFor" in {
        val cfg = ConfigSpec(
            library = "sized",
            symbolPrefix = "",
            symbols = Map.empty,
            packedStructs = Set.empty,
            scratchSize = Some(128 * 1024)
        )
        val spec = mkTrait(
            "SizedScratch",
            "sized",
            List(mkMethod("noop", "noop", Nil, ReturnShape.Void)),
            companion = Some(cfg)
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("""val __kyoScratch$ = Scratch.currentFor("kyo.example.SizedScratch", 131072L)"""))
    }

    "retained callback method promotes the scratch spill list to the Ffi.Guard" in {
        val spec = mkTrait(
            "Retain",
            "kyo_retain",
            List(
                mkMethod(
                    "register",
                    "register",
                    List(
                        ParamSpec("guard", TypeRef.GuardT),
                        ParamSpec("payload", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("cb", TypeRef.FnPtrT(List(TypeRef.IntT), TypeRef.UnitT))
                    ),
                    ReturnShape.Void,
                    kind = CallbackKind.Retained
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        // Spill list is drained AFTER the invoke and before result construction.
        assert(src.contains("val __kyoSpills$ = __kyoScratch$.takeSpills()"))
        assert(src.contains("adoptArena"))
        assert(src.contains("guard.asInstanceOf[kyo.ffi.internal.JvmGuard]"))
        // Transient + callback-free paths must NOT promote spills.
    }

    "transient callback method does NOT promote the scratch spill list to a guard" in {
        val spec = mkTrait(
            "Trans",
            "kyo_trans",
            List(
                mkMethod(
                    "qsort",
                    "qsort",
                    List(
                        ParamSpec("base", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("cmp", TypeRef.FnPtrT(List(TypeRef.IntT, TypeRef.IntT), TypeRef.IntT))
                    ),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(!src.contains("takeSpills"))
        assert(!src.contains("adoptArena"))
    }

    "callback-free method does NOT promote the scratch spill list" in {
        val spec = mkTrait(
            "Simple",
            "simple",
            List(
                mkMethod("f", "f", List(ParamSpec("x", TypeRef.IntT)), ReturnShape.Primitive(TypeRef.IntT))
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(!src.contains("takeSpills"))
        assert(!src.contains("adoptArena"))
    }

    "emitted retained-callback source with spill promotion parses under the Scala 3 parser" in {
        val spec = mkTrait(
            "Epoll",
            "kyo_epoll",
            List(
                mkMethod(
                    "epollAdd",
                    "epoll_add",
                    List(
                        ParamSpec("guard", TypeRef.GuardT),
                        ParamSpec("epfd", TypeRef.IntT),
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("onEvent", TypeRef.FnPtrT(List(TypeRef.IntT), TypeRef.UnitT))
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    kind = CallbackKind.Retained
                )
            )
        )
        val src        = JvmEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -------------------------------------------------------------------------
    // Section 10: reserved-name backticking
    // -------------------------------------------------------------------------

    "Scala 3 keywords used as parameter names are backticked in the emitted method signature" in {
        // Pick a representative subset of new Scala 3 keywords plus `throws` (the missing one).
        val spec = mkTrait(
            "ResvJvm",
            "kyo_resv",
            List(
                mkMethod(
                    "kw",
                    "kw",
                    List(
                        ParamSpec("then", TypeRef.IntT),
                        ParamSpec("given", TypeRef.IntT),
                        ParamSpec("using", TypeRef.IntT),
                        ParamSpec("export", TypeRef.IntT),
                        ParamSpec("opaque", TypeRef.IntT),
                        ParamSpec("extension", TypeRef.IntT),
                        ParamSpec("derives", TypeRef.IntT),
                        ParamSpec("enum", TypeRef.IntT),
                        ParamSpec("throws", TypeRef.IntT)
                    ),
                    ReturnShape.Void
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("`then`: Int"))
        assert(src.contains("`given`: Int"))
        assert(src.contains("`using`: Int"))
        assert(src.contains("`export`: Int"))
        assert(src.contains("`opaque`: Int"))
        assert(src.contains("`extension`: Int"))
        assert(src.contains("`derives`: Int"))
        assert(src.contains("`enum`: Int"))
        assert(src.contains("`throws`: Int"))
        // And the emitted source must parse under the Scala 3 parser.
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -------------------------------------------------------------------------
    // Section: variadic function support
    // -------------------------------------------------------------------------

    "variadic method emits FunctionDescriptor.of + firstVariadicArg + accepts args: Any*" in {
        val spec = mkTrait(
            "VariadicLib",
            "kyo_variadic",
            List(
                mkMethod(
                    "vsum",
                    "kyo_it_sum_varargs",
                    List(ParamSpec("count", TypeRef.IntT)),
                    ReturnShape.Primitive(TypeRef.IntT),
                    hasVarargs = true
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        // Generated method signature accepts args: Any* and the binding tier's trailing `(using kyo.AllowUnsafe)`.
        assert(src.contains("def vsum(count: Int, args: Any*)(using kyo.AllowUnsafe): Int"))
        // Panama requires `Linker.Option.firstVariadicArg(n)` to mark the fixed-arity boundary.
        assert(src.contains("Linker.Option.firstVariadicArg(1)"))
        // Dispatch helper routes Any values to the appropriate Panama ValueLayout at runtime.
        assert(src.contains("VariadicMarshaller"))
        // The emitted source must parse.
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -------------------------------------------------------------------------
    // helper
    // -------------------------------------------------------------------------

    /** Extract the full MH declaration block (up to and including the closing paren at indent 4) for a method. */
    private def extractMhBlock(src: String, scalaName: String)(using kyo.test.AssertScope): String =
        val mhDecl = s"private val ${scalaName}MH: MethodHandle = linker.downcallHandle("
        val start  = src.indexOf(mhDecl)
        if start < 0 then fail(s"MH declaration for $scalaName not found in emitted source")
        // The block ends at the first line containing just "    )" after start.
        val terminator = "\n    )"
        val endIdx     = src.indexOf(terminator, start)
        if endIdx < 0 then fail(s"MH block for $scalaName not closed in emitted source")
        src.substring(start, endIdx + terminator.length)
    end extractMhBlock

    // -------------------------------------------------------------------------
    // Section: Handle[A] pointer support
    // -------------------------------------------------------------------------

    "emit ADDRESS layout for Handle param in FunctionDescriptor" in {
        val spec = mkTrait(
            "OpaqueBindings",
            "kyo_opaque",
            List(
                mkMethod(
                    "readHandle",
                    "read_handle",
                    List(ParamSpec("h", TypeRef.HandleT("test.Handle"))),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        // FunctionDescriptor should include ADDRESS for the Handle param.
        assert(src.contains("ADDRESS"))
    }

    "emit Ffi.Handle.unwrap for Handle param marshalling" in {
        val spec = mkTrait(
            "OpaqueBindings",
            "kyo_opaque",
            List(
                mkMethod(
                    "readHandle",
                    "read_handle",
                    List(ParamSpec("h", TypeRef.HandleT("test.Handle"))),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("Ffi.Handle.unwrap(h)"))
    }

    "emit Handle return with FfiNullPointer throw for bare Handle" in {
        val spec = mkTrait(
            "OpaqueBindings",
            "kyo_opaque",
            List(
                mkMethod("createHandle", "create_handle", List(ParamSpec("v", TypeRef.IntT)), ReturnShape.HandleReturn("test.Handle"))
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("FfiNullPointer"))
        assert(src.contains("Ffi.Handle.wrap"))
        assert(!src.contains("Ffi.Handle.nil"))
    }

    "emit Maybe Handle return with Absent/Present wrapping" in {
        val spec = mkTrait(
            "OpaqueBindings",
            "kyo_opaque",
            List(
                mkMethod("nullHandle", "null_handle", Nil, ReturnShape.HandleReturn("test.Handle", nullable = true))
            )
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("kyo.Absent"))
        assert(src.contains("kyo.Present"))
        assert(src.contains("Ffi.Handle.wrap"))
        assert(src.contains("kyo.Maybe[Ffi.Handle[test.Handle]]"))
        assert(!src.contains("FfiNullPointer"))
    }

    // -------------------------------------------------------------------------
    // Section: Enum support
    // -------------------------------------------------------------------------

    "emit .value for enum param" in {
        val spec = mkTrait(
            "EnumTest",
            "enum_test",
            List(
                mkMethod(
                    "setColor",
                    "set_color",
                    List(ParamSpec("c", TypeRef.EnumT("kyo.example.Color"))),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            ),
            enums = List(EnumSpec("kyo.example.Color", "Color"))
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("c.value"))
    }

    "emit fromInt for enum return" in {
        val spec = mkTrait(
            "EnumTest",
            "enum_test",
            List(
                mkMethod(
                    "getColor",
                    "get_color",
                    List(ParamSpec("index", TypeRef.IntT)),
                    ReturnShape.EnumReturn("kyo.example.Color")
                )
            ),
            enums = List(EnumSpec("kyo.example.Color", "Color"))
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("kyo.example.Color.fromInt("))
    }

    "emit JAVA_INT layout for enum param" in {
        val m = mkMethod(
            "setColor",
            "set_color",
            List(ParamSpec("c", TypeRef.EnumT("kyo.example.Color"))),
            ReturnShape.Primitive(TypeRef.IntT)
        )
        val spec = mkTrait(
            "EnumTest",
            "enum_test",
            List(m),
            enums = List(EnumSpec("kyo.example.Color", "Color"))
        )
        val src = JvmEmitter.emit(spec)
        assert(src.contains("JAVA_INT"))
    }

    // -------------------------------------------------------------------------
    // Section: Outcome errno capture
    // -------------------------------------------------------------------------

    "Outcome from Int return emits errnoSeg capture and Ffi.Outcome packing" in {
        val m = mkMethod(
            "riskyOp",
            "risky_op",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT),
            withError = true
        )
        val spec = mkTrait("ErrnoTest", "errno_test", List(m))
        val src  = JvmEmitter.emit(spec)
        assert(src.contains("errnoSeg"))
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("Ffi.Outcome"))
    }

    "Outcome from Long return emits errnoSeg capture and Ffi.Outcome packing" in {
        val m = mkMethod(
            "riskyLong",
            "risky_long",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.LongT),
            withError = true
        )
        val spec = mkTrait("ErrnoTestLong", "errno_test_long", List(m))
        val src  = JvmEmitter.emit(spec)
        assert(src.contains("errnoSeg"))
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("Ffi.Outcome"))
    }

    "Outcome from Double return emits errnoSeg capture and Ffi.Outcome packing" in {
        val m = mkMethod(
            "riskyDouble",
            "risky_double",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.DoubleT),
            withError = true
        )
        val spec = mkTrait("ErrnoTestDouble", "errno_test_double", List(m))
        val src  = JvmEmitter.emit(spec)
        assert(src.contains("errnoSeg"))
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("Ffi.Outcome"))
    }

    "Outcome from Boolean return emits errnoSeg capture and Ffi.Outcome packing" in {
        val m = mkMethod(
            "riskyBool",
            "risky_bool",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.BooleanT),
            withError = true
        )
        val spec = mkTrait("ErrnoTestBool", "errno_test_bool", List(m))
        val src  = JvmEmitter.emit(spec)
        assert(src.contains("errnoSeg"))
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("Ffi.Outcome"))
    }

    "Outcome from void return emits errnoSeg capture and Ffi.Outcome packing" in {
        val m = mkMethod(
            "riskyVoid",
            "risky_void",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Void,
            withError = true
        )
        val spec = mkTrait("ErrnoTestVoid", "errno_test_void", List(m))
        val src  = JvmEmitter.emit(spec)
        assert(src.contains("errnoSeg"))
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("Ffi.Outcome"))
    }

    "Outcome on @Ffi.blocking method emits errnoSeg capture" in {
        val m = mkMethod(
            "blockingRisky",
            "blocking_risky",
            List(ParamSpec("fd", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT),
            blocking = true,
            withError = true
        )
        val spec = mkTrait("BlockingErrnoTest", "blocking_errno_test", List(m))
        val src  = JvmEmitter.emit(spec)
        assert(src.contains("errnoSeg"))
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
    }

    "plain Int return does NOT emit Outcome or __errno" in {
        val m = mkMethod(
            "safeOp",
            "safe_op",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT)
        )
        val spec = mkTrait("PlainTest", "plain_test", List(m))
        val src  = JvmEmitter.emit(spec)
        assert(!src.contains("Ffi.Outcome.fromValueErrno("))
        assert(!src.contains("__errno"))
        assert(!src.contains("Ffi.Outcome"))
    }

    "plain void return does NOT emit Outcome or __errno" in {
        val m = mkMethod(
            "safeVoid",
            "safe_void",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Void
        )
        val spec = mkTrait("PlainVoidTest", "plain_void_test", List(m))
        val src  = JvmEmitter.emit(spec)
        assert(!src.contains("Ffi.Outcome.fromValueErrno("))
        assert(!src.contains("__errno"))
        assert(!src.contains("Ffi.Outcome"))
    }

    "plain Handle return does NOT emit Outcome or __errno" in {
        val m = mkMethod(
            "getHandle",
            "get_handle",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.HandleReturn("kyo.example.MyHandle")
        )
        val spec = mkTrait("PlainHandleTest", "plain_handle_test", List(m))
        val src  = JvmEmitter.emit(spec)
        assert(!src.contains("Ffi.Outcome.fromValueErrno("))
        assert(!src.contains("__errno"))
        assert(!src.contains("Ffi.Outcome"))
    }

    "trait with both Outcome and plain methods emits errno only for Outcome method" in {
        val riskyM = mkMethod(
            "riskyOp",
            "risky_op",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT),
            withError = true
        )
        val safeM = mkMethod(
            "safeOp",
            "safe_op",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT)
        )
        val spec = mkTrait("MixedErrnoTest", "mixed_errno_test", List(riskyM, safeM))
        val src  = JvmEmitter.emit(spec)
        // The errno-capturing method renders the Outcome return type.
        assert(src.contains(": Ffi.Outcome[Int] ="))
        // Verify the safeOp method signature has the plain Int return type, not Outcome.
        val safeDefLine = src.linesIterator.find(_.contains("def safeOp")).getOrElse(fail("safeOp def not found"))
        assert(!safeDefLine.contains("Outcome"))
        assert(safeDefLine.contains(": Int ="))
    }

    "Outcome with Handle return emits errno capture and Handle wrapping" in {
        val m = mkMethod(
            "riskyHandle",
            "risky_handle",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.HandleReturn("kyo.example.MyHandle"),
            withError = true
        )
        val spec = mkTrait("HandleErrnoTest", "handle_errno_test", List(m))
        val src  = JvmEmitter.emit(spec)
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("errnoSeg"))
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Handle.wrap"))
    }

    "Outcome with BorrowedString return emits errno capture and Borrowed wrapping" in {
        val m = mkMethod(
            "riskyBorrowed",
            "risky_borrowed",
            List(ParamSpec("name", TypeRef.StringT)),
            ReturnShape.BorrowedString(4096),
            withError = true
        )
        val spec = mkTrait("BorrowedErrnoTest", "borrowed_errno_test", List(m))
        val src  = JvmEmitter.emit(spec)
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("errnoSeg"))
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Borrowed.wrap"))
    }

    "trait with Handle and Outcome on different methods emits errno only for Outcome method" in {
        val handleM = mkMethod(
            "getHandle",
            "get_handle",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.HandleReturn("kyo.example.MyHandle")
        )
        val riskyM = mkMethod(
            "riskyOp",
            "risky_op",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT),
            withError = true
        )
        val spec = mkTrait("HandleMixedTest", "handle_mixed_test", List(handleM, riskyM))
        val src  = JvmEmitter.emit(spec)
        // The riskyOp method renders the Outcome return type.
        assert(src.contains(": Ffi.Outcome[Int] ="))
        // The getHandle method should NOT have Outcome in its return type.
        val handleDefLine = src.linesIterator.find(_.contains("def getHandle")).getOrElse(fail("getHandle def not found"))
        assert(!handleDefLine.contains("Outcome"))
    }

end JvmEmitterTest
