package kyo.ffi.codegen.emitters

import EmitterFixtures.*
import kyo.ffi.codegen.model.*

class NativeEmitterTest extends kyo.test.Test[Any]:

    // -------------------------------------------------------------------------
    // Section 1: header / companion basics
    // -------------------------------------------------------------------------

    "emits an AUTO-GENERATED banner, package clause, and Native imports" in {
        val spec = mkTrait(
            "Simple",
            "simple",
            List(mkMethod("noop", "noop", Nil, ReturnShape.Void))
        )
        val src = NativeEmitter.emit(spec)
        assert(src.startsWith("// AUTO-GENERATED by kyo-ffi-codegen"))
        assert(src.contains("package kyo.example"))
        assert(src.contains("import scala.scalanative.unsafe.*"))
        assert(src.contains("import scala.scalanative.libc.errno.errno"))
        assert(src.contains("import scala.scalanative.reflect.annotation.EnableReflectiveInstantiation"))
        assert(src.contains("import kyo.ffi.*"))
        assert(src.contains("import kyo.ffi.internal.{AbiCheck, NativePtr, StructAbiCheck}"))
    }

    "impl class is annotated with @EnableReflectiveInstantiation so Ffi.load can reach it" in {
        val spec = mkTrait(
            "Simple",
            "simple",
            List(mkMethod("noop", "noop", Nil, ReturnShape.Void))
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("@EnableReflectiveInstantiation final class SimpleImpl extends Simple:"))
    }

    "companion calls AbiCheck.verify(1, <traitFqn>)" in {
        val spec = mkTrait(
            "Simple",
            "simple",
            List(mkMethod("noop", "noop", Nil, ReturnShape.Void))
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("""AbiCheck.verify(1, "kyo.example.Simple")"""))
        assert(src.contains("object SimpleImpl:"))
    }

    // -------------------------------------------------------------------------
    // Section 2: @extern object structure
    // -------------------------------------------------------------------------

    "emits a top-level @extern @link object with the trait's library id" in {
        val spec = mkTrait(
            "TcpBindings",
            "kyo_tcp",
            List(mkMethod("tcpClose", "tcp_close", List(ParamSpec("fd", TypeRef.IntT)), ReturnShape.Void))
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("@extern"))
        assert(src.contains("""@link("kyo_tcp")"""))
        assert(src.contains("object `TcpBindings$externs`"))
        assert(src.contains("def tcp_close(fd: CInt): Unit = extern"))
    }

    "omits @link for a nativeBundled binding (C is compiled into the Native binary)" in {
        val spec = mkTrait(
            "UringBindings",
            "kyonet_posix_uring",
            List(mkMethod("uringClose", "uring_close", List(ParamSpec("fd", TypeRef.IntT)), ReturnShape.Void)),
            nativeBundled = true
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("@extern"))
        assert(!src.contains("@link"))
        assert(src.contains("object `UringBindings$externs`"))
        assert(src.contains("def uring_close(fd: CInt): Unit = extern"))
    }

    "omits @link for a nativeBundled binding even when the extern object is empty (headers unavailable)" in {
        val spec = mkTrait(
            "UringBindings",
            "kyonet_posix_uring",
            List(mkMethod("uringClose", "uring_close", List(ParamSpec("fd", TypeRef.IntT)), ReturnShape.Void)),
            nativeBundled = true
        )
        val src = NativeEmitter.emit(spec, headersAvailable = false)
        assert(src.contains("@extern"))
        assert(!src.contains("@link"))
        assert(src.contains("object `UringBindings$externs`"))
    }

    "@blocking annotation propagates to the extern declaration for @Ffi.blocking methods" in {
        val spec = mkTrait(
            "TcpBindings",
            "kyo_tcp",
            List(
                mkMethod(
                    "tcpRead",
                    "tcp_read",
                    List(
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("maxLen", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                ),
                mkMethod(
                    "tcpClose",
                    "tcp_close",
                    List(ParamSpec("fd", TypeRef.IntT)),
                    ReturnShape.Void,
                    blocking = false
                )
            )
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("@blocking def tcp_read(fd: CInt, buf: Ptr[Byte], maxLen: CInt): CInt = extern"))
        // tcp_close is non-blocking -> no @blocking prefix.
        assert(src.contains("def tcp_close(fd: CInt): Unit = extern"))
        assert(!src.contains("@blocking def tcp_close"))
    }

    "two methods binding the same C symbol emit a single extern declaration (the @extern object is a C-symbol table)" in {
        // A `@Ffi.blocking` `send` and a synchronous `sendNow` (bound to the same `send` symbol via the `symbols` override) must not emit
        // two `def send` externs: Scala Native rejects two extern declarations with the same erased signature in one object. One extern,
        // marked @blocking because one of the two callers is blocking, serves both impl methods (each calls `ext.send`).
        val params = List(
            ParamSpec("fd", TypeRef.IntT),
            ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT)),
            ParamSpec("len", TypeRef.LongT),
            ParamSpec("flags", TypeRef.IntT)
        )
        val spec = mkTrait(
            "SockBindings",
            "c",
            List(
                mkMethod("send", "send", params, ReturnShape.Primitive(TypeRef.LongT), blocking = true),
                mkMethod("sendNow", "send", params, ReturnShape.Primitive(TypeRef.LongT), blocking = false)
            )
        )
        val src = NativeEmitter.emit(spec)
        // Exactly one extern declaration for the shared `send` symbol, and it is @blocking (any contributing method blocking wins). The
        // extern decls are the lines ending in `= extern`; the impl-class methods (`def send(fd: Int, ...)`) are excluded by that filter.
        val externDecls = src.linesIterator.filter(l => l.contains("def send(") && l.contains("= extern")).toList
        assert(externDecls.length == 1)
        assert(externDecls.head.contains("@blocking def send(fd: CInt, buf: Ptr[Byte], len: CLongLong, flags: CInt): CLongLong = extern"))
        // Both impl methods still exist and both call the single `ext.send` extern.
        assert(src.contains("def send(fd: Int, buf: Buffer[Byte], len: Long, flags: Int)(using kyo.AllowUnsafe)"))
        assert(src.contains("def sendNow(fd: Int, buf: Buffer[Byte], len: Long, flags: Int)(using kyo.AllowUnsafe)"))
        assert(src.linesIterator.count(_.contains("ext.send(")) == 2)
    }

    // -------------------------------------------------------------------------
    // Section 3: impl-class body, marshalling
    // -------------------------------------------------------------------------

    "primitive-only method body calls ext directly (no Zone, no errno capture for plain returns)" in {
        val spec = mkTrait(
            "Math",
            "kyo_math",
            List(
                mkMethod(
                    "add",
                    "add_ints",
                    List(ParamSpec("a", TypeRef.IntT), ParamSpec("b", TypeRef.IntT)),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            )
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("def add(a: Int, b: Int)(using kyo.AllowUnsafe): Int ="))
        assert(src.contains("val retVal = ext.add_ints(a, b)"))
        assert(!src.contains("val __errno = errno"))
        assert(!src.contains("Zone.acquire"))
    }

    "String param method body wraps in Zone.acquire and calls toCString" in {
        val spec = mkTrait(
            "Log",
            "kyo_log",
            List(
                mkMethod(
                    "log",
                    "log_line",
                    List(ParamSpec("msg", TypeRef.StringT)),
                    ReturnShape.Void
                )
            )
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("Zone.acquire { implicit z =>"))
        assert(src.contains("val msgC = toCString(msg)"))
        assert(src.contains("ext.log_line(msgC)"))
    }

    "Buffer param unwraps .raw via NativePtr" in {
        val spec = mkTrait(
            "TcpBindings",
            "kyo_tcp",
            List(
                mkMethod(
                    "tcpRead",
                    "tcp_read",
                    List(
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("maxLen", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                )
            )
        )
        val src = NativeEmitter.emit(spec)
        // `Buffer.Raw` unwrap routes through `FfiUnsafe.expect`.
        assert(src.contains(
            """val bufPtr = kyo.ffi.internal.FfiUnsafe.expect[NativePtr](buf.raw.asInstanceOf[AnyRef], classOf[NativePtr], "NativePtr on Native", "kyo.example.TcpBindings", "tcpRead").ptr"""
        ))
        assert(src.contains("ext.tcp_read(fd, bufPtr, maxLen)"))
    }

    "Array + @blocking copies into Zone-allocated buffer" in {
        val spec = mkTrait(
            "Hash",
            "kyo_hash",
            List(
                mkMethod(
                    "digestBlocking",
                    "digest_blocking",
                    List(
                        ParamSpec("data", TypeRef.ArrayT(TypeRef.ByteT)),
                        ParamSpec("len", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                )
            )
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("Zone.acquire { implicit z =>"))
        assert(src.contains("val dataPtr = alloc[CChar](data.length)"))
        assert(src.contains("while dataI < data.length do"))
        assert(src.contains("ext.digest_blocking(dataPtr, len)"))
    }

    "multi-value return allocates out-cells inside the Zone and reads them post-call" in {
        val cr = StructSpec(
            "kyo.example.ConnectResult",
            "ConnectResult",
            List(StructField("fd", TypeRef.IntT), StructField("pending", TypeRef.IntT)),
            packed = false
        )
        val spec = mkTrait(
            "TcpBindings",
            "kyo_tcp",
            List(mkMethod(
                "tcpConnect",
                "tcp_connect",
                List(ParamSpec("host", TypeRef.StringT), ParamSpec("port", TypeRef.IntT)),
                ReturnShape.MultiValue(cr),
                blocking = true
            )),
            structs = List(cr)
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("Zone.acquire { implicit z =>"))
        assert(src.contains("val hostC = toCString(host)"))
        assert(src.contains("val pendingOut = alloc[CInt](1)"))
        assert(src.contains("val retVal = ext.tcp_connect(hostC, port, pendingOut)"))
        assert(src.contains("kyo.example.ConnectResult(retVal, !pendingOut)"))
        // extern signature contains the out-pointer as trailing param
        assert(src.contains("@blocking def tcp_connect(host: CString, port: CInt, pendingOut: Ptr[CInt]): CInt = extern"))
    }

    "struct param allocates a CStruct in the zone and writes fields before the call" in {
        val ts = StructSpec(
            "kyo.example.Timespec",
            "Timespec",
            List(StructField("sec", TypeRef.LongT), StructField("nsec", TypeRef.LongT)),
            packed = false
        )
        val spec = mkTrait(
            "Time",
            "kyo_time",
            List(mkMethod(
                "sleep",
                "sleep_ts",
                List(ParamSpec("ts", TypeRef.StructT(ts.fqcn))),
                ReturnShape.Primitive(TypeRef.IntT)
            )),
            structs = List(ts)
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("Zone.acquire { implicit z =>"))
        assert(src.contains("val tsPtr = alloc[CStruct2[CLongLong, CLongLong]](1)"))
        assert(src.contains("(!tsPtr)._1 = ts.sec"))
        assert(src.contains("(!tsPtr)._2 = ts.nsec"))
        // Struct params are passed as POINTERS (tsPtr, not !tsPtr) to match the JVM emitter's
        // ADDRESS convention, C signatures stay `int fn(const Timespec *ts)` across platforms.
        assert(src.contains("ext.sleep_ts(tsPtr)"))
    }

    "Unit-return method calls ext and then `()`, no retVal" in {
        val spec = mkTrait(
            "Simple",
            "simple",
            List(mkMethod("close", "do_close", List(ParamSpec("fd", TypeRef.IntT)), ReturnShape.Void))
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("ext.do_close(fd)"))
        assert(!src.contains("val retVal ="))
    }

    // -------------------------------------------------------------------------
    // Section 3b: callback emission (transient + retained)
    // -------------------------------------------------------------------------

    "transient callback body routes through CallbackRegistry push/pop and a top-level trampoline" in {
        val spec = mkTrait(
            "Sort",
            "kyo_sort",
            List(
                mkMethod(
                    "qsort",
                    "qsort",
                    List(
                        ParamSpec("base", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("count", TypeRef.IntT),
                        ParamSpec("elemSize", TypeRef.IntT),
                        ParamSpec("cmp", TypeRef.FnPtrT(List(TypeRef.IntT, TypeRef.IntT), TypeRef.IntT))
                    ),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src = NativeEmitter.emit(spec)
        // The CFuncPtr val wraps the top-level trampoline (NOT the user callback directly, Scala Native's fromScalaFunction rejects
        // closures over local state). Eta-expansion keeps the trampoline reference non-capturing.
        assert(src.contains(
            "val cmpPtr: CFuncPtr2[CInt, CInt, CInt] = CFuncPtr2.fromScalaFunction(kyo.ffi.internal.CallbackRegistry.trampolineT_II_I)"
        ))
        // The user callback is pushed on the per-shape transient stack before the FFI call and popped in a finally afterwards.
        assert(src.contains("""kyo.ffi.internal.CallbackRegistry.pushTransient_II_I("kyo.example.Sort", "qsort", cmp)"""))
        assert(src.contains("kyo.ffi.internal.CallbackRegistry.popTransient_II_I()"))
        assert(src.contains("try"))
        assert(src.contains("finally"))
        // The extern is called with the CFuncPtrN val, not the raw Scala function.
        assert(src.contains("ext.qsort(basePtr, count, elemSize, cmpPtr)"))
        // Transient: no guard plumbing.
        assert(!src.contains("unsafeRetain"))
        assert(!src.contains("unsafeRetainCleanup"))
        // No Zone is required for a callback-only body (Buffer .raw is pointer-direct).
        assert(!src.contains("Zone.acquire"))
    }

    "retained callback body claims a CallbackRegistry slot and registers a close-time release on the guard" in {
        val spec = mkTrait(
            "Epoll",
            "kyo_epoll",
            List(
                mkMethod(
                    "epollAdd",
                    "epoll_add",
                    List(
                        ParamSpec("guard", TypeRef.GuardT),
                        ParamSpec("epfd", TypeRef.IntT),
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("onEvent", TypeRef.FnPtrT(List(TypeRef.IntT), TypeRef.UnitT))
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    kind = CallbackKind.Retained
                )
            )
        )
        val src = NativeEmitter.emit(spec)
        // Pool slot + pre-built CFuncPtr are obtained via claimRetainedSlot_<SHAPE>, which claims any free slot from the
        // global pool. The guard's token is passed as the first argument.
        assert(src.contains(
            """val (onEventSlot, onEventPtr) = kyo.ffi.internal.CallbackRegistry.claimRetainedSlot_I_U(guard.asInstanceOf[kyo.ffi.internal.NativeGuard].guardToken, "kyo.example.Epoll", "epollAdd", onEvent)"""
        ))
        // The guard-scoped cleanup releases the slot at guard close AND records it with the leak detector so a leaked guard still
        // frees the pool slot (routed through a single entry point on NativeGuard).
        assert(src.contains(
            """guard.asInstanceOf[kyo.ffi.internal.NativeGuard].unsafeRetainRetainedSlot("I_U", onEventSlot)"""
        ))
        // Guard does NOT cross into the extern call.
        assert(src.contains("val retVal = ext.epoll_add(epfd, fd, onEventPtr)"))
        assert(!src.contains("ext.epoll_add(guard,"))
        // Retained doesn't use the transient push/pop stack.
        assert(!src.contains("pushTransient_"))
        assert(!src.contains("popTransient_"))
    }

    "transient callback extern object declares the CFuncPtrN[...] slot (no Guard slot)" in {
        val spec = mkTrait(
            "Sort",
            "kyo_sort",
            List(
                mkMethod(
                    "qsort",
                    "qsort",
                    List(
                        ParamSpec("base", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("count", TypeRef.IntT),
                        ParamSpec("elemSize", TypeRef.IntT),
                        ParamSpec("cmp", TypeRef.FnPtrT(List(TypeRef.IntT, TypeRef.IntT), TypeRef.IntT))
                    ),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains(
            "def qsort(base: Ptr[Byte], count: CInt, elemSize: CInt, cmp: CFuncPtr2[CInt, CInt, CInt]): Unit = extern"
        ))
    }

    "retained callback extern object declares the CFuncPtrN slot and omits Ffi.Guard entirely" in {
        val spec = mkTrait(
            "Epoll",
            "kyo_epoll",
            List(
                mkMethod(
                    "epollAdd",
                    "epoll_add",
                    List(
                        ParamSpec("guard", TypeRef.GuardT),
                        ParamSpec("epfd", TypeRef.IntT),
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("onEvent", TypeRef.FnPtrT(List(TypeRef.IntT), TypeRef.UnitT))
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    kind = CallbackKind.Retained
                )
            )
        )
        val src = NativeEmitter.emit(spec)
        // Guard is NOT in the extern signature, stripped. Extract the extern block and check it explicitly.
        assert(src.contains("def epoll_add(epfd: CInt, fd: CInt, onEvent: CFuncPtr1[CInt, Unit]): CInt = extern"))
        val externBlock = src.substring(src.indexOf("@extern"))
        assert(!externBlock.contains("guard:"))
    }

    "CFuncPtrN types are reachable via the scala.scalanative.unsafe wildcard import" in {
        // The header imports `scala.scalanative.unsafe.*`, `CFuncPtr0..CFuncPtr22` all live in that package, so the generated
        // `CFuncPtrN[...]` type references resolve without any additional explicit import.
        val spec = mkTrait(
            "CbImport",
            "kyo_cb",
            List(
                mkMethod(
                    "fire",
                    "fire_cb",
                    List(ParamSpec("cb", TypeRef.FnPtrT(Nil, TypeRef.UnitT))),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("import scala.scalanative.unsafe.*"))
        assert(src.contains("CFuncPtr0[Unit]"))
    }

    "callback arity 0 emits CFuncPtr0[ret]" in {
        // Arity 0 with a non-Unit return (`() => Int`) is not currently in the transient-shape catalog (see
        // NativeCallbackCatalog, V_U / V_U covers `() => Unit` only). We use the catalog's `() => Unit` shape
        // to verify the arity-0 branch instead.
        val spec = mkTrait(
            "Zero",
            "kyo_zero",
            List(
                mkMethod(
                    "run",
                    "run_cb",
                    List(ParamSpec("cb", TypeRef.FnPtrT(Nil, TypeRef.UnitT))),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains(
            "val cbPtr: CFuncPtr0[Unit] = CFuncPtr0.fromScalaFunction(kyo.ffi.internal.CallbackRegistry.trampolineT_V_U)"
        ))
        assert(src.contains("def run_cb(cb: CFuncPtr0[Unit]): Unit = extern"))
    }

    "transient callback emitted source parses under the Scala 3 parser" in {
        val spec = mkTrait(
            "Sort",
            "kyo_sort",
            List(
                mkMethod(
                    "qsort",
                    "qsort",
                    List(
                        ParamSpec("base", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("count", TypeRef.IntT),
                        ParamSpec("elemSize", TypeRef.IntT),
                        ParamSpec("cmp", TypeRef.FnPtrT(List(TypeRef.IntT, TypeRef.IntT), TypeRef.IntT))
                    ),
                    ReturnShape.Void,
                    kind = CallbackKind.Transient
                )
            )
        )
        val src        = NativeEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    "retained callback emitted source parses under the Scala 3 parser" in {
        val spec = mkTrait(
            "Epoll",
            "kyo_epoll",
            List(
                mkMethod(
                    "epollAdd",
                    "epoll_add",
                    List(
                        ParamSpec("guard", TypeRef.GuardT),
                        ParamSpec("epfd", TypeRef.IntT),
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("onEvent", TypeRef.FnPtrT(List(TypeRef.IntT), TypeRef.UnitT))
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    kind = CallbackKind.Retained
                )
            )
        )
        val src        = NativeEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -------------------------------------------------------------------------
    // Section 4: TcpBindings full fixture
    // -------------------------------------------------------------------------

    "TcpBindings fixture emits all four methods with expected shapes" in {
        val cr = StructSpec(
            "kyo.example.ConnectResult",
            "ConnectResult",
            List(StructField("fd", TypeRef.IntT), StructField("pending", TypeRef.IntT)),
            packed = false
        )
        val spec = mkTrait(
            "TcpBindings",
            "kyo_tcp",
            List(
                mkMethod(
                    "tcpConnect",
                    "tcp_connect",
                    List(ParamSpec("host", TypeRef.StringT), ParamSpec("port", TypeRef.IntT)),
                    ReturnShape.MultiValue(cr),
                    blocking = true
                ),
                mkMethod(
                    "tcpClose",
                    "tcp_close",
                    List(ParamSpec("fd", TypeRef.IntT)),
                    ReturnShape.Void
                ),
                mkMethod(
                    "tcpRead",
                    "tcp_read",
                    List(
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("maxLen", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                ),
                mkMethod(
                    "tcpWrite",
                    "tcp_write",
                    List(
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("len", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                )
            ),
            structs = List(cr)
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("final class TcpBindingsImpl extends TcpBindings:"))
        assert(src.contains("import `TcpBindings$externs` as ext"))
        assert(src.contains("end TcpBindingsImpl"))

        // Every binding method takes a trailing `(using kyo.AllowUnsafe)`; the three @Ffi.blocking methods return
        // `kyo.Fiber.Unsafe[…, Any]`; tcpClose is non-blocking and returns a plain value.
        assert(src.contains(
            "def tcpConnect(host: String, port: Int)(using kyo.AllowUnsafe): kyo.Fiber.Unsafe[kyo.example.ConnectResult, Any] ="
        ))
        assert(src.contains("def tcpClose(fd: Int)(using kyo.AllowUnsafe): Unit ="))
        assert(src.contains("def tcpRead(fd: Int, buf: Buffer[Byte], maxLen: Int)(using kyo.AllowUnsafe): kyo.Fiber.Unsafe[Int, Any] ="))
        assert(src.contains("def tcpWrite(fd: Int, buf: Buffer[Byte], len: Int)(using kyo.AllowUnsafe): kyo.Fiber.Unsafe[Int, Any] ="))

        assert(src.contains("@blocking def tcp_connect(host: CString, port: CInt, pendingOut: Ptr[CInt]): CInt = extern"))
        assert(src.contains("@blocking def tcp_read(fd: CInt, buf: Ptr[Byte], maxLen: CInt): CInt = extern"))
        assert(src.contains("@blocking def tcp_write(fd: CInt, buf: Ptr[Byte], len: CInt): CInt = extern"))
        assert(src.contains("def tcp_close(fd: CInt): Unit = extern"))
    }

    // -------------------------------------------------------------------------
    // Section 5: Scala-parser syntactic validation
    // -------------------------------------------------------------------------

    "emitted source parses under the Scala 3 parser (smoke)" in {
        val cr = StructSpec(
            "kyo.example.ConnectResult",
            "ConnectResult",
            List(StructField("fd", TypeRef.IntT), StructField("pending", TypeRef.IntT)),
            packed = false
        )
        val spec = mkTrait(
            "TcpBindings",
            "kyo_tcp",
            List(
                mkMethod(
                    "tcpConnect",
                    "tcp_connect",
                    List(ParamSpec("host", TypeRef.StringT), ParamSpec("port", TypeRef.IntT)),
                    ReturnShape.MultiValue(cr),
                    blocking = true
                ),
                mkMethod(
                    "tcpClose",
                    "tcp_close",
                    List(ParamSpec("fd", TypeRef.IntT)),
                    ReturnShape.Void
                ),
                mkMethod(
                    "tcpRead",
                    "tcp_read",
                    List(
                        ParamSpec("fd", TypeRef.IntT),
                        ParamSpec("buf", TypeRef.BufferT(TypeRef.ByteT)),
                        ParamSpec("maxLen", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                )
            ),
            structs = List(cr)
        )
        val src        = NativeEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    "emitted source for an Array + blocking method parses" in {
        val spec = mkTrait(
            "Hash",
            "kyo_hash",
            List(
                mkMethod(
                    "digestBlocking",
                    "digest_blocking",
                    List(
                        ParamSpec("data", TypeRef.ArrayT(TypeRef.ByteT)),
                        ParamSpec("len", TypeRef.IntT)
                    ),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                )
            )
        )
        val src        = NativeEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -------------------------------------------------------------------------
    // Section 6: nested struct, @packed, pointer + String in return struct
    // -------------------------------------------------------------------------

    "nested struct param writes fields via at{N} recursion" in {
        val inner = StructSpec(
            "kyo.example.Timeval",
            "Timeval",
            List(StructField("sec", TypeRef.LongT), StructField("usec", TypeRef.LongT)),
            packed = false
        )
        val outer = StructSpec(
            "kyo.example.Rusage",
            "Rusage",
            List(
                StructField("utime", TypeRef.StructT(inner.fqcn)),
                StructField("stime", TypeRef.StructT(inner.fqcn)),
                StructField("maxrss", TypeRef.LongT)
            ),
            packed = false
        )
        val spec = mkTrait(
            "Rusages",
            "kyo_rusage",
            List(mkMethod(
                "push",
                "push_rusage",
                List(ParamSpec("r", TypeRef.StructT(outer.fqcn))),
                ReturnShape.Primitive(TypeRef.IntT)
            )),
            structs = List(outer, inner)
        )
        val src = NativeEmitter.emit(spec)
        // Outer pointer allocation references the nested-expanded CStruct type.
        assert(src.contains("val rPtr = alloc[CStruct3[CStruct2[CLongLong, CLongLong], CStruct2[CLongLong, CLongLong], CLongLong]](1)"))
        // Inner fields written via at{N} pointer + `(!ptr)._K = ...` per-sub-field
        assert(src.contains("val r_utime_ptr = rPtr.at1"))
        assert(src.contains("(!r_utime_ptr)._1 = r.utime.sec"))
        assert(src.contains("(!r_utime_ptr)._2 = r.utime.usec"))
        assert(src.contains("val r_stime_ptr = rPtr.at2"))
        assert(src.contains("(!r_stime_ptr)._1 = r.stime.sec"))
        assert(src.contains("(!rPtr)._3 = r.maxrss"))
    }

    "nested struct in return position reads via at{N} recursion" in {
        val inner = StructSpec(
            "kyo.example.Timeval",
            "Timeval",
            List(StructField("sec", TypeRef.LongT), StructField("usec", TypeRef.LongT)),
            packed = false
        )
        val outer = StructSpec(
            "kyo.example.Rusage",
            "Rusage",
            List(
                StructField("utime", TypeRef.StructT(inner.fqcn)),
                StructField("maxrss", TypeRef.LongT)
            ),
            packed = false
        )
        val spec = mkTrait(
            "Rusages",
            "kyo_rusage",
            List(mkMethod(
                "current",
                "get_rusage",
                Nil,
                ReturnShape.Struct(outer)
            )),
            structs = List(outer, inner)
        )
        val src = NativeEmitter.emit(spec)
        // Outer read constructs the nested Timeval by recursing into `out.at1`.
        assert(src.contains("kyo.example.Rusage(kyo.example.Timeval((!out.at1)._1, (!out.at1)._2), (!out)._2)"))
    }

    "packed struct uses raw Ptr[Byte] with offset-based access (no @packed annotation)" in {
        val ps = StructSpec(
            "kyo.example.Packed",
            "Packed",
            List(StructField("flag", TypeRef.ByteT), StructField("value", TypeRef.IntT)),
            packed = true
        )
        val spec = mkTrait(
            "PackedTrait",
            "kyo_packed",
            List(mkMethod(
                "send",
                "send_packed",
                List(ParamSpec("p", TypeRef.StructT(ps.fqcn))),
                ReturnShape.Primitive(TypeRef.IntT)
            )),
            structs = List(ps)
        )
        val src = NativeEmitter.emit(spec)
        // Packed struct byte-size constant in companion (1 byte + 4 bytes = 5 bytes packed).
        assert(src.contains("inline val Packed_packedSize = 5"))
        // Alloc uses raw byte allocation with the packed byte size.
        assert(src.contains("val pPtr = alloc[Byte](Packed_packedSize)"))
        // Extern decl uses Ptr[Byte] for packed structs (no CStruct type).
        assert(src.contains("def send_packed(p: Ptr[Byte]): CInt = extern"))
        // Field writes use byte-offset pointer arithmetic.
        assert(src.contains("!(pPtr + 0) = p.flag"))
        assert(src.contains("!(pPtr + 1).asInstanceOf[Ptr[CInt]] = p.value"))
        // No @packed annotation anywhere.
        assert(!src.contains("@packed"))
    }

    "pointer field (Buffer[A]) in return-position struct is wrapped as borrowed Buffer with inferred sibling size" in {
        val iov = StructSpec(
            "kyo.example.IoVec",
            "IoVec",
            List(StructField("base", TypeRef.BufferT(TypeRef.ByteT)), StructField("len", TypeRef.LongT)),
            packed = false
        )
        val spec = mkTrait(
            "Io",
            "kyo_io",
            List(mkMethod(
                "slice",
                "io_slice",
                List(ParamSpec("fd", TypeRef.IntT)),
                ReturnShape.Struct(iov)
            )),
            structs = List(iov)
        )
        val src = NativeEmitter.emit(spec)
        // Size is read from the sole Int/Long sibling (`len`, at CStruct positional index 2 → `._2`, narrowed to Int).
        assert(src.contains("Buffer.Unsafe.wrapBorrowed[Byte](new NativePtr((!out)._1), (!out)._2.toInt)"))
        assert(!src.contains("Int.MaxValue"))
        assert(src.contains("kyo.example.IoVec("))
    }

    "String field in return-position struct decodes via fromCString" in {
        val us = StructSpec(
            "kyo.example.User",
            "User",
            List(StructField("id", TypeRef.IntT), StructField("name", TypeRef.StringT)),
            packed = false
        )
        val spec = mkTrait(
            "Users",
            "kyo_users",
            List(mkMethod(
                "lookup",
                "user_lookup",
                List(ParamSpec("id", TypeRef.IntT)),
                ReturnShape.Struct(us)
            )),
            structs = List(us)
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("fromCString((!out)._2)"))
        assert(src.contains("kyo.example.User("))
    }

    "by-value struct return uses the out-pointer-FIRST ABI: out is the leading extern + call argument, C returns Unit" in {
        val pt = StructSpec(
            "kyo.example.Point",
            "Point",
            List(StructField("x", TypeRef.IntT), StructField("y", TypeRef.IntT)),
            packed = false
        )
        val spec = mkTrait(
            "Geo",
            "kyo_geo",
            List(mkMethod(
                "makePoint",
                "make_point",
                List(ParamSpec("seed", TypeRef.IntT)),
                ReturnShape.Struct(pt)
            )),
            structs = List(pt)
        )
        val src = NativeEmitter.emit(spec)
        // The struct out-pointer is the FIRST extern parameter and the C function returns Unit (void), matching JVM.
        assert(src.contains("def make_point(out: Ptr[CStruct2[CInt, CInt]], seed: CInt): Unit = extern"))
        // The call passes `out` FIRST, before the user args.
        assert(src.contains("ext.make_point(out, seed)"))
    }

    "emitted source for a packed struct parses under Scala 3" in {
        val ps = StructSpec(
            "kyo.example.Packed",
            "Packed",
            List(StructField("flag", TypeRef.ByteT), StructField("value", TypeRef.IntT)),
            packed = true
        )
        val spec = mkTrait(
            "PackedTrait",
            "kyo_packed",
            List(mkMethod(
                "send",
                "send_packed",
                List(ParamSpec("p", TypeRef.StructT(ps.fqcn))),
                ReturnShape.Primitive(TypeRef.IntT)
            )),
            structs = List(ps)
        )
        val src        = NativeEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    "emitted source for a nested struct parses under Scala 3" in {
        val inner = StructSpec(
            "kyo.example.Timeval",
            "Timeval",
            List(StructField("sec", TypeRef.LongT), StructField("usec", TypeRef.LongT)),
            packed = false
        )
        val outer = StructSpec(
            "kyo.example.Rusage",
            "Rusage",
            List(
                StructField("utime", TypeRef.StructT(inner.fqcn)),
                StructField("stime", TypeRef.StructT(inner.fqcn)),
                StructField("maxrss", TypeRef.LongT)
            ),
            packed = false
        )
        val spec = mkTrait(
            "Rusages",
            "kyo_rusage",
            List(
                mkMethod(
                    "push",
                    "push_rusage",
                    List(ParamSpec("r", TypeRef.StructT(outer.fqcn))),
                    ReturnShape.Primitive(TypeRef.IntT)
                ),
                mkMethod("current", "get_rusage", Nil, ReturnShape.Struct(outer))
            ),
            structs = List(outer, inner)
        )
        val src        = NativeEmitter.emit(spec)
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -------------------------------------------------------------------------
    // Section: reserved-name backticking
    // -------------------------------------------------------------------------

    "Scala 3 keywords used as parameter names are backticked in the emitted method signature" in {
        val spec = mkTrait(
            "ResvNative",
            "kyo_resv",
            List(
                mkMethod(
                    "kw",
                    "kw",
                    List(
                        ParamSpec("then", TypeRef.IntT),
                        ParamSpec("given", TypeRef.IntT),
                        ParamSpec("using", TypeRef.IntT),
                        ParamSpec("export", TypeRef.IntT),
                        ParamSpec("opaque", TypeRef.IntT),
                        ParamSpec("extension", TypeRef.IntT),
                        ParamSpec("derives", TypeRef.IntT),
                        ParamSpec("enum", TypeRef.IntT),
                        ParamSpec("throws", TypeRef.IntT)
                    ),
                    ReturnShape.Void
                )
            )
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("`then`: CInt"))
        assert(src.contains("`given`: CInt"))
        assert(src.contains("`using`: CInt"))
        assert(src.contains("`export`: CInt"))
        assert(src.contains("`opaque`: CInt"))
        assert(src.contains("`extension`: CInt"))
        assert(src.contains("`derives`: CInt"))
        assert(src.contains("`enum`: CInt"))
        assert(src.contains("`throws`: CInt"))
        val (ok, errs) = ScalaParseProbe.parses(src)
        assert(ok == true, s"emitted source did not parse:\n$src\n\nerrors:\n$errs\n")
    }

    // -------------------------------------------------------------------------
    // Section: variadic function support
    // -------------------------------------------------------------------------

    "variadic method emits a runtime stub instead of @extern (Scala Native cannot express varargs)" in {
        val spec = mkTrait(
            "VariadicLib",
            "kyo_variadic",
            List(
                mkMethod(
                    "vsum",
                    "kyo_it_sum_varargs",
                    List(ParamSpec("count", TypeRef.IntT)),
                    ReturnShape.Primitive(TypeRef.IntT),
                    hasVarargs = true
                )
            )
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("def vsum(count: Int, args: Any*)(using kyo.AllowUnsafe): Int ="))
        assert(src.contains("UnsupportedOperationException"))
        assert(src.contains("Variadic method 'vsum' is not supported on Scala Native."))
        // Varargs method must NOT appear in the extern object.
        val externBlock = src.substring(src.indexOf("@extern"))
        assert(!externBlock.contains("kyo_it_sum_varargs"))
        assert(!externBlock.contains("= extern"))
    }

    // -------------------------------------------------------------------------
    // Section: header-gated conditional emission
    // -------------------------------------------------------------------------

    "headers unavailable, all methods become runtime stubs" in {
        val spec = mkTrait(
            "EpollBindings",
            "c",
            List(
                mkMethod(
                    "epollCreate1",
                    "epoll_create1",
                    List(ParamSpec("flags", TypeRef.IntT)),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            )
        ).copy(headers = Seq("sys/epoll.h"))
        val src = NativeEmitter.emit(spec, headersAvailable = false)
        assert(src.contains("UnsupportedOperationException"))
        assert(src.contains("not available on this platform"))
        assert(src.contains("sys/epoll.h"))
        assert(!src.contains("= extern"))
    }

    "headers available, normal @extern emission" in {
        val spec = mkTrait(
            "EpollBindings",
            "c",
            List(
                mkMethod(
                    "epollCreate1",
                    "epoll_create1",
                    List(ParamSpec("flags", TypeRef.IntT)),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            )
        ).copy(headers = Seq("sys/epoll.h"))
        val src = NativeEmitter.emit(spec, headersAvailable = true)
        assert(src.contains("= extern"))
        assert(src.contains("ext.epoll_create1(flags)"))
        assert(!src.contains("UnsupportedOperationException"))
    }

    "headers unavailable, extern object is emitted empty (no method declarations)" in {
        val spec = mkTrait(
            "EpollBindings",
            "c",
            List(
                mkMethod(
                    "epollCreate1",
                    "epoll_create1",
                    List(ParamSpec("flags", TypeRef.IntT)),
                    ReturnShape.Primitive(TypeRef.IntT)
                ),
                mkMethod(
                    "epollWait",
                    "epoll_wait",
                    List(ParamSpec("epfd", TypeRef.IntT)),
                    ReturnShape.Primitive(TypeRef.IntT),
                    blocking = true
                )
            )
        ).copy(headers = Seq("sys/epoll.h"))
        val src = NativeEmitter.emit(spec, headersAvailable = false)
        // The extern object exists but has no method declarations.
        assert(src.contains("object `EpollBindings$externs`:"))
        assert(src.contains("end `EpollBindings$externs`"))
        assert(!src.contains("= extern"))
    }

    "headers unavailable, companion AbiCheck is still emitted" in {
        val spec = mkTrait(
            "EpollBindings",
            "c",
            List(
                mkMethod(
                    "epollCreate1",
                    "epoll_create1",
                    List(ParamSpec("flags", TypeRef.IntT)),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            )
        ).copy(headers = Seq("sys/epoll.h"))
        val src = NativeEmitter.emit(spec, headersAvailable = false)
        assert(src.contains("""AbiCheck.verify(1, "kyo.example.EpollBindings")"""))
    }

    "headers unavailable, varargs method stub uses header message, not varargs message" in {
        val spec = mkTrait(
            "VariadicLib",
            "kyo_variadic",
            List(
                mkMethod(
                    "vsum",
                    "kyo_it_sum_varargs",
                    List(ParamSpec("count", TypeRef.IntT)),
                    ReturnShape.Primitive(TypeRef.IntT),
                    hasVarargs = true
                )
            )
        ).copy(headers = Seq("my_header.h"))
        val src = NativeEmitter.emit(spec, headersAvailable = false)
        assert(src.contains("def vsum(count: Int, args: Any*)(using kyo.AllowUnsafe): Int ="))
        assert(src.contains("UnsupportedOperationException"))
        assert(src.contains("not available on this platform"))
        assert(src.contains("my_header.h"))
    }

    // -------------------------------------------------------------------------
    // Section: Handle[A] pointer support
    // -------------------------------------------------------------------------

    "emit Ptr[Byte] for Handle param in extern declaration" in {
        val spec = mkTrait(
            "OpaqueBindings",
            "kyo_opaque",
            List(
                mkMethod(
                    "readHandle",
                    "read_handle",
                    List(ParamSpec("h", TypeRef.HandleT("test.Handle"))),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            )
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("Ptr[Byte]"))
    }

    "emit Handle return with FfiNullPointer throw for bare Handle" in {
        val spec = mkTrait(
            "OpaqueBindings",
            "kyo_opaque",
            List(
                mkMethod("createHandle", "create_handle", List(ParamSpec("v", TypeRef.IntT)), ReturnShape.HandleReturn("test.Handle"))
            )
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("NativePtr"))
        assert(src.contains("Ffi.Handle.wrap"))
        assert(src.contains("FfiNullPointer"))
        assert(!src.contains("Ffi.Handle.nil"))
    }

    "emit Maybe Handle return with Absent/Present wrapping" in {
        val spec = mkTrait(
            "OpaqueBindings",
            "kyo_opaque",
            List(
                mkMethod("nullHandle", "null_handle", Nil, ReturnShape.HandleReturn("test.Handle", nullable = true))
            )
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("kyo.Absent"))
        assert(src.contains("kyo.Present"))
        assert(src.contains("Ffi.Handle.wrap"))
        assert(src.contains("kyo.Maybe[Ffi.Handle[test.Handle]]"))
        assert(!src.contains("FfiNullPointer"))
    }

    // -------------------------------------------------------------------------
    // Section: Enum support
    // -------------------------------------------------------------------------

    "emit CInt extern type for enum param" in {
        val spec = mkTrait(
            "EnumTest",
            "enum_test",
            List(
                mkMethod(
                    "setColor",
                    "set_color",
                    List(ParamSpec("c", TypeRef.EnumT("kyo.example.Color"))),
                    ReturnShape.Primitive(TypeRef.IntT)
                )
            ),
            enums = List(EnumSpec("kyo.example.Color", "Color"))
        )
        val src = NativeEmitter.emit(spec)
        // Extern declaration should use CInt for the enum param.
        assert(src.contains("CInt"))
        // Marshalling should extract .value.
        assert(src.contains("c.value"))
    }

    "emit fromInt for enum return" in {
        val spec = mkTrait(
            "EnumTest",
            "enum_test",
            List(
                mkMethod(
                    "getColor",
                    "get_color",
                    List(ParamSpec("index", TypeRef.IntT)),
                    ReturnShape.EnumReturn("kyo.example.Color")
                )
            ),
            enums = List(EnumSpec("kyo.example.Color", "Color"))
        )
        val src = NativeEmitter.emit(spec)
        assert(src.contains("kyo.example.Color.fromInt("))
    }

    // -------------------------------------------------------------------------
    // Section: Outcome errno capture
    // -------------------------------------------------------------------------

    "Outcome from Int return emits errno capture and Ffi.Outcome packing" in {
        val m = mkMethod(
            "riskyOp",
            "risky_op",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT),
            withError = true
        )
        val spec = mkTrait("ErrnoTest", "errno_test", List(m))
        val src  = NativeEmitter.emit(spec)
        assert(src.contains("__errno"))
        assert(src.contains("errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("Ffi.Outcome"))
    }

    "Outcome from Long return emits errno capture and Ffi.Outcome packing" in {
        val m = mkMethod(
            "riskyLong",
            "risky_long",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.LongT),
            withError = true
        )
        val spec = mkTrait("ErrnoTestLong", "errno_test_long", List(m))
        val src  = NativeEmitter.emit(spec)
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("Ffi.Outcome"))
    }

    "Outcome from Double return emits errno capture and Ffi.Outcome packing" in {
        val m = mkMethod(
            "riskyDouble",
            "risky_double",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.DoubleT),
            withError = true
        )
        val spec = mkTrait("ErrnoTestDouble", "errno_test_double", List(m))
        val src  = NativeEmitter.emit(spec)
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("Ffi.Outcome"))
    }

    "Outcome from Boolean return emits errno capture and Ffi.Outcome packing" in {
        val m = mkMethod(
            "riskyBool",
            "risky_bool",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.BooleanT),
            withError = true
        )
        val spec = mkTrait("ErrnoTestBool", "errno_test_bool", List(m))
        val src  = NativeEmitter.emit(spec)
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("Ffi.Outcome"))
    }

    "Outcome from void return emits errno capture and Ffi.Outcome packing" in {
        val m = mkMethod(
            "riskyVoid",
            "risky_void",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Void,
            withError = true
        )
        val spec = mkTrait("ErrnoTestVoid", "errno_test_void", List(m))
        val src  = NativeEmitter.emit(spec)
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("Ffi.Outcome"))
    }

    "Outcome on @Ffi.blocking method emits errno capture" in {
        val m = mkMethod(
            "blockingRisky",
            "blocking_risky",
            List(ParamSpec("fd", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT),
            blocking = true,
            withError = true
        )
        val spec = mkTrait("BlockingErrnoTest", "blocking_errno_test", List(m))
        val src  = NativeEmitter.emit(spec)
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
    }

    "plain Int return does NOT emit Outcome or __errno" in {
        val m = mkMethod(
            "safeOp",
            "safe_op",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT)
        )
        val spec = mkTrait("PlainTest", "plain_test", List(m))
        val src  = NativeEmitter.emit(spec)
        assert(!src.contains("Ffi.Outcome.fromValueErrno("))
        assert(!src.contains("__errno"))
        assert(!src.contains("Ffi.Outcome"))
    }

    "plain void return does NOT emit Outcome or __errno" in {
        val m = mkMethod(
            "safeVoid",
            "safe_void",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Void
        )
        val spec = mkTrait("PlainVoidTest", "plain_void_test", List(m))
        val src  = NativeEmitter.emit(spec)
        assert(!src.contains("Ffi.Outcome.fromValueErrno("))
        assert(!src.contains("__errno"))
        assert(!src.contains("Ffi.Outcome"))
    }

    "plain Handle return does NOT emit Outcome or __errno" in {
        val m = mkMethod(
            "getHandle",
            "get_handle",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.HandleReturn("kyo.example.MyHandle")
        )
        val spec = mkTrait("PlainHandleTest", "plain_handle_test", List(m))
        val src  = NativeEmitter.emit(spec)
        assert(!src.contains("Ffi.Outcome.fromValueErrno("))
        assert(!src.contains("__errno"))
        assert(!src.contains("Ffi.Outcome"))
    }

    "trait with both Outcome and plain methods emits errno only for Outcome method" in {
        val riskyM = mkMethod(
            "riskyOp",
            "risky_op",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT),
            withError = true
        )
        val safeM = mkMethod(
            "safeOp",
            "safe_op",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT)
        )
        val spec = mkTrait("MixedErrnoTest", "mixed_errno_test", List(riskyM, safeM))
        val src  = NativeEmitter.emit(spec)
        assert(src.contains(": Ffi.Outcome[Int] ="))
        val safeDefLine = src.linesIterator.find(_.contains("def safeOp")).getOrElse(fail("safeOp def not found"))
        assert(!safeDefLine.contains("Outcome"))
        assert(safeDefLine.contains(": Int ="))
    }

    "Outcome with Handle return emits errno capture and Handle wrapping" in {
        val m = mkMethod(
            "riskyHandle",
            "risky_handle",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.HandleReturn("kyo.example.MyHandle"),
            withError = true
        )
        val spec = mkTrait("HandleErrnoTest", "handle_errno_test", List(m))
        val src  = NativeEmitter.emit(spec)
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Handle.wrap"))
    }

    "Outcome with BorrowedString return emits errno capture and Borrowed wrapping" in {
        val m = mkMethod(
            "riskyBorrowed",
            "risky_borrowed",
            List(ParamSpec("name", TypeRef.StringT)),
            ReturnShape.BorrowedString(4096),
            withError = true
        )
        val spec = mkTrait("BorrowedErrnoTest", "borrowed_errno_test", List(m))
        val src  = NativeEmitter.emit(spec)
        assert(src.contains("Ffi.Outcome.fromValueErrno("))
        assert(src.contains("__errno"))
        assert(src.contains("Ffi.Borrowed.wrap"))
    }

    "trait with Handle and Outcome on different methods emits errno only for Outcome method" in {
        val handleM = mkMethod(
            "getHandle",
            "get_handle",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.HandleReturn("kyo.example.MyHandle")
        )
        val riskyM = mkMethod(
            "riskyOp",
            "risky_op",
            List(ParamSpec("x", TypeRef.IntT)),
            ReturnShape.Primitive(TypeRef.IntT),
            withError = true
        )
        val spec = mkTrait("HandleMixedTest", "handle_mixed_test", List(handleM, riskyM))
        val src  = NativeEmitter.emit(spec)
        assert(src.contains(": Ffi.Outcome[Int] ="))
        val handleDefLine = src.linesIterator.find(_.contains("def getHandle")).getOrElse(fail("getHandle def not found"))
        assert(!handleDefLine.contains("Outcome"))
    }

end NativeEmitterTest
