package kyo.internal.charset

import java.nio.charset.StandardCharsets
import kyo.*
import kyo.charset.Charset

/** The inputs the JDK differential test decodes with both decoders: every valid sequence the encoding's index defines (or, for the
  * Unicode encodings, every scalar value) and every single byte, and a fixed set of generated byte strings drawn from a seeded
  * generator, so the set is the same on every run.
  */
object CharsetJdkInputs:

    val GeneratedPerEncoding = 200

    /** Generated strings for every encoding with malformed input. A single-byte encoding has none and decodes each byte alone, so every
      * byte value covers it and generated strings would only repeat those bytes.
      */
    def generatedFor(charset: Charset): Seq[Span[Byte]] =
        if isSingleByte(charset) then Seq.empty else generated(charset)

    def isSingleByte(charset: Charset): Boolean = IndexTableFixtures.singleByte.exists(_.charset == charset)

    def valid(charset: Charset): Seq[Span[Byte]] =
        charset match
            case Charset.Utf8                    => scalarChunks.map(s => span(s.getBytes(StandardCharsets.UTF_8)))
            case Charset.Utf16Be                 => scalarChunks.map(s => span(s.getBytes(StandardCharsets.UTF_16BE)))
            case Charset.Utf16                   => scalarChunks.map(s => span(s.getBytes(StandardCharsets.UTF_16BE))) ++ marked
            case Charset.Utf16Le                 => scalarChunks.map(s => span(s.getBytes(StandardCharsets.UTF_16LE)))
            case Charset.Utf32Be | Charset.Utf32 => scalarChunks.map(s => span(utf32(s, bigEndian = true)))
            case Charset.Utf32Le                 => scalarChunks.map(s => span(utf32(s, bigEndian = false)))
            case Charset.Gb18030 | Charset.Gbk   => gb18030TwoByte ++ gb18030FourByte ++ singleBytes
            case Charset.Big5                    => big5 ++ singleBytes
            case Charset.EucJp                   => eucJp ++ singleBytes
            case Charset.ShiftJis                => shiftJis
            case Charset.EucKr                   => eucKr ++ singleBytes
            case Charset.Iso2022Jp               => iso2022Jp
            case Charset.Iso2022Kr               => iso2022Kr
            case Charset.HzGb2312                => hz
            case Charset.Utf7                    => scalarChunks.take(16).map(s => span(utf7(s)))
            case _                               => singleBytes

    /** 16-bit text with no mark, with FE FF and with FF FE: what a bare `UTF-16` and the `iso-10646-ucs-2` label read. */
    lazy val marked: Seq[Span[Byte]] = Seq(
        bytes(0x00, 0x61, 0x04, 0x30),
        bytes(0xfe, 0xff, 0x00, 0x61, 0x04, 0x30),
        bytes(0xff, 0xfe, 0x61, 0x00, 0x30, 0x04)
    )

    /** Every GB 2312 pair as EUC-CN bytes, first byte 0xA1 to 0xF7 and second 0xA1 to 0xFE, for the gb2312 label. */
    lazy val gb2312: Seq[Span[Byte]] =
        for
            first  <- 0xa1 to 0xf7
            second <- 0xa1 to 0xfe
        yield bytes(first, second)

    private lazy val singleBytes: Seq[Span[Byte]] = (0 to 0xff).map(b => bytes(b))

    /** Byte strings of 1 to 12 bytes from a generator seeded by the charset's ordinal, each byte drawn uniformly or, three times in ten,
      * from the bytes that start, shift or end sequences in the stateful and multi-byte encodings.
      */
    private def generated(charset: Charset): Seq[Span[Byte]] =
        val random  = new java.util.Random(0x6b796f + charset.ordinal)
        val shaping = Array(0x1b, 0x0e, 0x0f, '~', '{', '}', '+', '-', '$', '(', ')', 'B', 'J', 'I', '@', 'C', 0x0a, 0x80, 0x81, 0x8e,
            0x8f, 0xa1, 0xfe, 0xff, 0x30, 0x39, 0xd8, 0xdc, 0xef, 0xbb, 0xbf, 0x00)
        Seq.fill(GeneratedPerEncoding) {
            val length = 1 + random.nextInt(12)
            span(Array.fill(length)(
                (if random.nextInt(10) < 3 then shaping(random.nextInt(shaping.length)) else random.nextInt(256)).toByte
            ))
        }
    end generated

    private def span(a: Array[Byte]): Span[Byte] = Span.from(a)
    private def bytes(values: Int*): Span[Byte]  = Span.from(values.map(_.toByte).toArray)

    // Every Unicode scalar value, 128 to a string.
    private lazy val scalarChunks: Seq[String] = (0 to 0x10ffff).filterNot(c => c >= 0xd800 && c <= 0xdfff).grouped(128).map(g =>
        g.map(c => new String(Character.toChars(c))).mkString
    ).toSeq

    private def utf32(s: String, bigEndian: Boolean): Array[Byte] =
        s.codePoints().toArray.flatMap { c =>
            val be = Array((c >>> 24).toByte, (c >>> 16).toByte, (c >>> 8).toByte, c.toByte)
            if bigEndian then be else be.reverse
        }

    private def utf7(s: String): Array[Byte] =
        val alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
        val bits     = s.flatMap(c => (15 to 0 by -1).map(k => (c >> k) & 1))
        ("+" + bits.grouped(6).map(g => alphabet.charAt((g ++ Seq.fill(6 - g.size)(0)).foldLeft(0)(_ * 2 + _))).mkString + "-").getBytes(
            "US-ASCII"
        )
    end utf7

    private def entries(raw: String): Seq[Int] = IndexTableFixtures.entries(raw).keys.toSeq.sorted

    private lazy val gb18030TwoByte: Seq[Span[Byte]] = entries(EmbeddedIndexGb18030.text).map { p =>
        val t = p % 190
        bytes(p / 190 + 0x81, t + (if t < 0x3f then 0x40 else 0x41))
    }

    // Every four-byte sequence, 1260 to an input: one input per first and second byte.
    private lazy val gb18030FourByte: Seq[Span[Byte]] = (0 until 126 * 10).map { head =>
        span((0 until 1260).flatMap { tail =>
            val p = head * 1260 + tail
            Seq(p / 12600 + 0x81, p % 12600 / 1260 + 0x30, p % 1260 / 10 + 0x81, p % 10 + 0x30).map(_.toByte)
        }.toArray)
    }

    private lazy val big5: Seq[Span[Byte]] = (entries(EmbeddedIndexBig5.text) ++ Seq(1133, 1135, 1164, 1166)).map { p =>
        val t = p % 157
        bytes(p / 157 + 0x81, t + (if t < 0x3f then 0x40 else 0x62))
    }

    private lazy val eucJp: Seq[Span[Byte]] =
        entries(EmbeddedIndexJis0208.text).filter(_ < 8836).map(p => bytes(p / 94 + 0xa1, p % 94 + 0xa1)) ++
            entries(EmbeddedIndexJis0212.text).map(p => bytes(0x8f, p / 94 + 0xa1, p % 94 + 0xa1)) ++
            (0xa1 to 0xdf).map(b => bytes(0x8e, b))

    private lazy val shiftJis: Seq[Span[Byte]] = (entries(EmbeddedIndexJis0208.text) ++ (8836 to 10715)).map { p =>
        val r = p / 188
        val t = p % 188
        bytes(r + (if r < 0x1f then 0x81 else 0xc1), t + (if t < 0x3f then 0x40 else 0x41))
    } ++ singleBytes

    private lazy val eucKr: Seq[Span[Byte]] = entries(EmbeddedIndexEucKr.text).map(p => bytes(p / 190 + 0x81, p % 190 + 0x41))

    private lazy val iso2022Jp: Seq[Span[Byte]] =
        entries(EmbeddedIndexJis0208.text).filter(_ < 8836).map(p =>
            bytes(0x1b, 0x24, 0x42, p / 94 + 0x21, p % 94 + 0x21, 0x1b, 0x28, 0x42)
        ) ++
            (0x21 to 0x5f).map(b => bytes(0x1b, 0x28, 0x49, b, 0x1b, 0x28, 0x42)) ++
            (0x21 to 0x7e).map(b => bytes(0x1b, 0x28, 0x4a, b, 0x1b, 0x28, 0x42)) ++
            (0x00 to 0x7f).filterNot(b => b == 0x0e || b == 0x0f || b == 0x1b).map(b => bytes(b))

    private lazy val iso2022Kr: Seq[Span[Byte]] =
        entries(EmbeddedIndexEucKr.text).filter(p => p / 190 >= 0x20 && p % 190 + 0x41 >= 0xa1).map { p =>
            bytes(0x1b, 0x24, 0x29, 0x43, 0x0e, p / 190 + 0x81 - 0x80, p % 190 + 0x41 - 0x80, 0x0f)
        }

    private lazy val hz: Seq[Span[Byte]] =
        for
            first  <- 0x21 to 0x77
            second <- 0x21 to 0x7e
        yield bytes('~', '{', first, second, '~', '}')

end CharsetJdkInputs
