export declare class HttpResponse {
  addField<N, V>(name: N, value: V): HttpResponse<Fields & Field<unknown, V>>;
  addFields<Fields2>(r: Record<Fields2>): HttpResponse<Fields & Fields2>;
  addHeader(name: string, value: string): HttpResponse<Fields>;
  cacheControl(directive: string): HttpResponse<Fields>;
  contentDisposition(filename: string, isInline: boolean): HttpResponse<Fields>;
  etag(value: string): HttpResponse<Fields>;
  readonly fields: Record<Fields>;
  halt(): Kyo<never, Abort<Halt>>;
  readonly headers: HttpHeaders;
  readonly noCache: HttpResponse<Fields>;
  readonly noStore: HttpResponse<Fields>;
  setHeader(name: string, value: string): HttpResponse<Fields>;
  readonly status: HttpStatus;

  readonly accepted: HttpResponse<unknown>;
  static acceptedJson<A>(body: A): HttpResponse<Field<"body", A>>;
  readonly badRequest: HttpResponse<unknown>;
  static badRequestJson<A>(body: A): HttpResponse<Field<"body", A>>;
  readonly conflict: HttpResponse<unknown>;
  static conflictJson<A>(body: A): HttpResponse<Field<"body", A>>;
  readonly created: HttpResponse<unknown>;
  static createdJson<A>(body: A): HttpResponse<Field<"body", A>>;
  readonly forbidden: HttpResponse<unknown>;
  static forbiddenJson<A>(body: A): HttpResponse<Field<"body", A>>;
  readonly noContent: HttpResponse<unknown>;
  readonly notFound: HttpResponse<unknown>;
  static notFoundJson<A>(body: A): HttpResponse<Field<"body", A>>;
  readonly notModified: HttpResponse<unknown>;
  readonly ok: HttpResponse<unknown>;
  static okJson<A>(body: A): HttpResponse<Field<"body", A>>;
  readonly serverError: HttpResponse<unknown>;
  static serverErrorJson<A>(body: A): HttpResponse<Field<"body", A>>;
  readonly serviceUnavailable: HttpResponse<unknown>;
  static serviceUnavailableJson<A>(body: A): HttpResponse<Field<"body", A>>;
  readonly tooManyRequests: HttpResponse<unknown>;
  static tooManyRequestsJson<A>(body: A): HttpResponse<Field<"body", A>>;
  readonly unauthorized: HttpResponse<unknown>;
  static unauthorizedJson<A>(body: A): HttpResponse<Field<"body", A>>;
  readonly unprocessableEntity: HttpResponse<unknown>;
  static unprocessableEntityJson<A>(body: A): HttpResponse<Field<"body", A>>;
};