package kyo

import kyo.internal.tasty.scala2.InflateHook
import kyo.internal.tasty.scala2.PortableInflate

/** Tests for InflateHook and PortableInflate on all platforms (JVM, JS via PortableInflate, Native).
  *
  * ZLIB envelope for "hello kyo" (9 bytes): 0x78 0x9c (ZLIB header, default compression)
  * + deflate bitstream + 4-byte Adler-32 checksum. Total: 17 bytes.
  */
class InflateHookTest extends kyo.test.Test[Any]:

    private val zlibCompressed: Array[Byte] = Array(
        0x78.toByte,
        0x9c.toByte,
        0xcb.toByte,
        0x48.toByte,
        0xcd.toByte,
        0xc9.toByte,
        0xc9.toByte,
        0x57.toByte,
        0xc8.toByte,
        0xae.toByte,
        0xcc.toByte,
        0x07.toByte,
        0x00.toByte,
        0x11.toByte,
        0xa2.toByte,
        0x03.toByte,
        0x88.toByte
    )

    private val expectedBytes: Array[Byte] =
        "hello kyo".getBytes(java.nio.charset.StandardCharsets.UTF_8)

    "InflateHook.inflate decompresses a known ZLIB envelope to the original bytes" in {
        Abort.run[TastyError](InflateHook.inflate(zlibCompressed)).map:
            case Result.Success(bytes) =>
                assert(
                    bytes.sameElements(expectedBytes),
                    s"Expected ${expectedBytes.toSeq} but got ${bytes.toSeq}"
                )
            case Result.Failure(e) =>
                fail(s"Expected success but got failure: $e")
            case Result.Panic(t) =>
                throw t
    }

    "InflateHook.inflate returns a TastyError failure for a corrupted ZLIB header (bad CMF byte)" in {
        // CMF byte 0x00: compression method bits = 0x0 (not deflate), triggers an error on all platforms.
        // JS/Native (PortableInflate) returns MalformedSection; JVM (InflaterInputStream) returns CorruptedFile.
        val badCmf: Array[Byte] = Array(
            0x00.toByte, // CMF: CM=0 (invalid), CINFO=0
            0x00.toByte, // FLG
            0x00.toByte,
            0x00.toByte,
            0x00.toByte,
            0x00.toByte // padding to reach min length
        )
        Abort.run[TastyError](InflateHook.inflate(badCmf)).map:
            case Result.Failure(_: TastyError) =>
                succeed
            case Result.Success(_) =>
                fail("Expected failure for corrupted ZLIB header, but got success")
            case Result.Panic(t) =>
                throw t
    }

    "InflateHook.inflate decompresses a minimal empty-payload ZLIB stream to Array.emptyByteArray" in {
        // Minimal valid ZLIB stream encoding an empty payload, 8 bytes total:
        //   0x78 0x9C -- CMF/FLG header: CM=8 (deflate), CINFO=7, (0x789C % 31 == 0 checksum OK)
        //   0x03 0x00 -- DEFLATE fixed-Huffman block: BFINAL=1 BTYPE=01, then EOB symbol 256
        //                 (7 bits = 0000000 in LSB-first order, packed with the 3 header bits)
        //   0x00 0x00 0x00 0x01 -- Adler-32 big-endian for empty input = 1
        // Generated by java.util.zip.DeflaterOutputStream compressing an empty byte array.
        val emptyZlib: Array[Byte] = Array(
            0x78.toByte,
            0x9c.toByte,
            0x03.toByte,
            0x00.toByte,
            0x00.toByte,
            0x00.toByte,
            0x00.toByte,
            0x01.toByte
        )
        Abort.run[TastyError](InflateHook.inflate(emptyZlib)).map:
            case Result.Success(bytes) =>
                assert(bytes.length == 0, s"Expected empty array but got ${bytes.length} bytes: ${bytes.toSeq}")
            case Result.Failure(e) =>
                fail(s"Expected success for valid empty-payload ZLIB stream but got failure: $e")
            case Result.Panic(t) =>
                throw t
    }

    // JS InflateHook delegates to PortableInflate. Output must be byte-equal
    // to a direct PortableInflate.inflate call on the same input.
    "JS InflateHook output is byte-equal to direct PortableInflate.inflate".onlyJs in {
        import AllowUnsafe.embrace.danger
        val directResult =
            try PortableInflate.inflate(zlibCompressed)
            catch
                case ex: PortableInflate.InflateException =>
                    fail(s"PortableInflate.inflate threw unexpectedly: ${ex.getMessage}")
                    Array.emptyByteArray
        Abort.run[TastyError](InflateHook.inflate(zlibCompressed)).map:
            case Result.Success(bytes) =>
                assert(
                    bytes.sameElements(directResult),
                    s"InflateHook output differs from PortableInflate: hook=${bytes.toSeq} direct=${directResult.toSeq}"
                )
            case Result.Failure(e) =>
                fail(s"InflateHook.inflate failed on JS: $e")
            case Result.Panic(t) =>
                throw t
    }

end InflateHookTest
