name: build-pr
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      os-matrix: '["linux", "macos", "windows"]'
      test-command: testDiff
