name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: build
    timeout-minutes: 15
    env:
      JAVA_OPTS: -Xms15G -Xmx15G -Xss10M -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms15G -Xmx15G -Xss10M -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0
    - uses: olafurpg/setup-scala@v13
      with:
          java-version: openjdk@21.0.2=tgz+https://download.java.net/java/GA/jdk21.0.2/f2283984656d49d69e91c558476027ac/13/GPL/openjdk-21.0.2_linux-x64_bin.tar.gz

    - name: Build JVM
      run: |
        sbt 'kyo-bench/test' 'kyo-cache/test' 'kyo-core/test' 'kyo-direct/test' 'kyo-examples/test' 'kyo-os-lib/test' 'kyo-stats-otel/test' 'kyo-sttp/test' 'kyo-tapir/test'

    - name: Build JS
      run: |
        sbt 'kyo-coreJS/test' 'kyo-directJS/test' 'kyo-sttpJS/test' 
