name: readme
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  readme:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Dfile.encoding=UTF-8
      JVM_OPTS: -Xms2G -Xmx2G -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v8.1.0
      - uses: coursier/setup-action@v3.0.0
        with:
          jvm: corretto:24
          apps: sbt
      - run: sbt checkReadme
