name: scalafmt
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Dfile.encoding=UTF-8
      JVM_OPTS: -Xms2G -Xmx2G -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: coursier/cache-action@v8.1.0
      - uses: coursier/setup-action@v3.0.0
        with:
          jvm: corretto:24
          apps: sbt
      - name: Check formatting
        run: |
          sbt scalafmtAll scalafmtSbt
          if ! git diff --quiet; then
            echo "::error::Files are not formatted. Run 'sbt scalafmtAll scalafmtSbt' locally."
            git diff
            exit 1
          fi
